### ISSUE TITLE
Reference cases need to be updated

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1131]
```
Traceback (most recent call last):
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 208, in <module>
    main(cea.config.Configuration())
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 193, in main
    demand_calculation(locator=locator, gv=cea.globalvar.GlobalVariables(), config=config)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 109, in demand_calculation
    format_output)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 153, in calc_demand_singleprocessing
    format_output)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 119, in calc_thermal_loads
    hourly_procedure_heating_cooling_system_load.calc_heating_cooling_loads(bpr, tsd, t)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\hourly_procedure_heating_cooling_system_load.py", line 97, in calc_heating_cooling_loads
    rc_model_temperatures = calc_cool_loads_central_ac(bpr, t, tsd)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\hourly_procedure_heating_cooling_system_load.py", line 462, in calc_cool_loads_central_ac
    g_dhu_demand_aru = latent_loads.calc_dehumidification_moisture_load(bpr, tsd, t)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\latent_loads.py", line 95, in calc_dehumidification_moisture_load
    x_set_max = calc_max_moisture_set_point(bpr, tsd, t)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\latent_loads.py", line 162, in calc_max_moisture_set_point
    phi_int_set_dhu = bpr.comfort['rhum_max_pc']
KeyError: 'rhum_max_pc'
```

I believe this variable was added by @gabriel-happle in his latest commit. This needs to be added to 'architecture.dbf' on each reference case. This can be done by running the data helper, however in scenarios where data was inputted manually (e.g. Zug and Zurich) this is unfortunately not an option.

I have already done this for the Zurich scenario, but the others are still missing.

**Comment by martin-mosteiro** [comment]
Mind if I make you responsible, @gabriel-happle? :innocent:

**Comment by gabriel-happle** [comment]
The easiest way to manipulate the dbf files:
Thanks @martin-mosteiro 
from cea.utilities.dbf import dbf_to_dataframe 
from cea.utilities.dbf import dataframe_to_dbf
import numpy as np

df = dbf_to_dataframe(r'C:\Users\User\Documents\GitHub\cea-reference-case\reference-case-zug\baseline\inputs\building-properties\indoor_comfort.dbf')
df['rhum_min_pc'] = np.ones(len(df.index.values))*30
df['rhum_max_pc'] = np.ones(len(df.index.values))*70
dataframe_to_dbf(df, r'C:\Users\User\Documents\GitHub\cea-reference-case\reference-case-zug\baseline\inputs\building-properties\indoor_comfort.dbf')

**Comment by gabriel-happle** [comment]
should I do it for all the case studies in the case study repository?
Or where are we keeping the most up to date case studies @JIMENOFONSECA ?
I think for most of them its easiest just to run the `data_helper`

**Comment by martin-mosteiro** [comment]
Don't do it for Zurich ;) There's a separate PR for that.

**Comment by gabriel-happle** [comment]
PR created in case study repository
