### ISSUE TITLE
Optimization - AttributeError: 'numpy.float64' object has no attribute 'get_supply_systems'

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1202]
Just ran accross this bug in master...

I haven't really debugged it, but I'm guessing someone changed the list of parameters to a function and now some float is being assigned to the `locator` parameter...

@BhargavaKrishnaSreepathi this is blocking me. Could you take a look?

```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (master)
(cea) λ cea optimization
3
PRE-PROCESSING + SINGLE BUILDING OPTIMIZATION
Solar features extraction
Run substation model for each building separately
B01
B02
B03
B04
B05
B07
B08
B09
B06
7.47108071166 seconds process time for the Substation Routine.
Run decentralized model for buildings
B01
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 113, in main
    moo_optimization(locator=locator, weather_file=weather_file, gv=gv, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 56, in moo_optimization
    prices)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\preprocessing_main.py", line 85, in preproccessing
    disconnected_buildings_heating.disconnected_buildings_heating_main(locator, building_names, gv, config, prices)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\disconnected_buildings_heating.py", line 219, in disconnected_buildings_heating_main
    Capex_a_Boiler, Opex_Boiler = Boiler.calc_Cinv_boiler(QnomBoiler, QannualB_GHP[i][0], locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\boiler.py", line 189, in calc_Cinv_boiler
    boiler_cost_data = pd.read_excel(locator.get_supply_systems(config.region), sheetname="Boiler")
AttributeError: 'numpy.float64' object has no attribute 'get_supply_systems'
```

**Comment by BhargavaKrishnaSreepathi** [comment]
PR #1203 will solve the problem. You are correct that the list of variables have been changed and it leads to the error, further after fixing this there are few other errors, which all are now fixed in the PR.
