### ISSUE TITLE
Photovoltaic thermal is not working in master

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1217]
This is the error I am getting. @shanshanhsieh: do you know what is happening? The problem is repeated in both mine and Zhongming's systems

C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\technologies\solar\solar_collector.py:570: RuntimeWarning: overflow encountered in multiply
  1]  # heat production from solar collector, eq.(5)
C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\technologies\solar\solar_collector.py:570: RuntimeWarning: invalid value encountered in subtract
  1]  # heat production from solar collector, eq.(5)
C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\technologies\solar\solar_collector.py:584: RuntimeWarning: invalid value encountered in less
  if abs(qdiff < 0.1):
C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py:455: RuntimeWarning: invalid value encountered in greater
  if abs(q_balance_error) > 1:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 639, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 617, in main
    latitude=latitude, longitude=longitude, weather_path=config.weather, building_name=building)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 103, in calc_PVT
    panel_properties_SC, panel_properties_PV, settings)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 231, in calc_PVT_generation
    absorbed_radiation_PV_Wperm2, T_cell_C, module_area_per_group_m2)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 531, in calc_PVT_module
    mcp_kWperK[5][x] = 0
TypeError: 'numpy.float64' object does not support item assignment

**Comment by JIMENOFONSECA** [comment]
I get the same...

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi @shizhongming , please try to run PVT again in branch `i1217` with the respective reference cases that you encounter the errors

**Comment by JIMENOFONSECA** [comment]
should there be a PR to test?

________________________________
