### ISSUE TITLE
key Error 'SINGLE_RES' in mobility.py of LCA

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1294]
I get the following error message:

`Running mobility with scenario = C:\Users\LennyRo\Dropbox\ETH\Master HS16\Master Thesis\Master-Thesis-LR\reference-case-WTP\RES_high_density\baseline
Traceback (most recent call last):
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/analysis/lca/mobility.py", line 90, in <module>
    main(cea.config.Configuration())
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/analysis/lca/mobility.py", line 87, in main
    lca_mobility(locator=locator, config=config)
  File "C:/Users/LennyRo/Documents/CityEnergyAnalyst/cea/analysis/lca/mobility.py", line 74, in lca_mobility
    mobility[fields_to_plot[3]] += mobility[occupancy_type[i]] * non_renewable_energy[i]
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "C:\Users\LennyRo\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: u'SINGLE_RES'`

**Comment by gabriel-happle** [comment]
Same for me when running my test scenario from ArcGIS interface.

**Comment by martin-mosteiro** [comment]
Strange. I am not able to replicate the issue on Pycharm. Does the issue only happen for you when you are running it from ArcGIS?

**Comment by roglen** [comment]
I got the issue running from Pycharm. 
Both Gabriel and I have fresh installs of CEA though, so it might be a library issue? We recently updated the libraries installed with CEA so this might be causing the issue.

**Comment by gabriel-happle** [comment]
I'm running in ArcGIS.
and we are talking about the new Singapore WTP case studies here.
My case study for testing is number 03.

**Comment by martin-mosteiro** [comment]
I'll do a fresh install of CEA as well, see what happens.

**Comment by martin-mosteiro** [comment]
Okay, I have now been able to replicate the error. I can now look into fixing it.

**Comment by martin-mosteiro** [comment]
Okay, easy peasy fix. The error only occurred for the Singapore case because there are less occupancy types in the reference case. I've fixed the error now (see #1304).
