### ISSUE TITLE
Key Error in Optimization plot

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1333]
```Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\plots\plots_main.py", line 76, in main
    plots_main(config)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\plots\plots_main.py", line 56, in plots_main
    plots_optimization(locator, config)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\plots\optimization\main.py", line 50, in plots_main
    plots.individual_cooling_activation_curve()
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\plots\optimization\main.py", line 388, in individual_cooling_activation_curve
    plot = individual_activation_curve(data, anlysis_fields_loads, self.analysis_fields_cooling, title, output_path)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\plots\optimization\individual_activation_curve.py", line 11, in individual_activation_curve
    traces_graph = calc_graph(analysis_fields, analysis_fields_loads, data_frame)
  File "c:\users\gabriel\documents\github\ceaforarcgis\cea\plots\optimization\individual_activation_curve.py", line 29, in calc_graph
    trace = go.Bar(x=data.index, y=y, name=field, marker=dict(color=COLOR[field]))
KeyError: 'Q_from_Lake_W'


Traceback (most recent call last):
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 68, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 155, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (Plots).
Failed at Wed May 16 15:27:18 2018 (Elapsed Time: 2.79 seconds)``

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed in PR #1358
