### ISSUE TITLE
import arcgisscripting ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1335]
I am trying to run the Heatmaps tool on ArcScene 10.5.1 but I get the following error:
```
Executing: HeatmapsTool C:\reference-case-WTP\CBD_low_density Total_demand.csv Qcs_lat_ahu_MWhyr
Start Time: Wed May 16 10:53:30 2018
Running script HeatmapsTool...
Executing: C:\Users\User\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli heatmaps --analysis-fields Qcs_lat_ahu_MWhyr --file-to-analyze C:\reference-case-WTP\CBD_low_density\outputs\data\demand\Total_demand.csv --scenario C:\reference-case-WTP\CBD_low_density
Traceback (most recent call last):
  File "C:\Users\User\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\User\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\user\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\user\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 32, in main
    script_module = importlib.import_module(module_path)
  File "C:\Users\User\Miniconda2\envs\cea\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\user\documents\github\cityenergyanalyst\cea\plots\heatmaps.py", line 11, in <module>
    from cea.interfaces.arcgis.modules import arcpy
  File "c:\users\user\documents\github\cityenergyanalyst\cea\interfaces\arcgis\modules.py", line 34, in <module>
    import arcpy
  File "c:\program files (x86)\arcgis\desktop10.5\ArcPy\arcpy\__init__.py", line 22, in <module>
    from arcpy.geoprocessing import gp
  File "c:\program files (x86)\arcgis\desktop10.5\ArcPy\arcpy\geoprocessing\__init__.py", line 14, in <module>
    from _base import *
  File "c:\program files (x86)\arcgis\desktop10.5\ArcPy\arcpy\geoprocessing\_base.py", line 14, in <module>
    import arcgisscripting
ImportError: DLL load failed: %1 is not a valid Win32 application.


Traceback (most recent call last):
  File "<string>", line 274, in execute
  File "C:\Users\User\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 68, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\User\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 155, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (HeatmapsTool).
Failed at Wed May 16 10:53:32 2018 (Elapsed Time: 2.37 seconds)
```
@shizhongming and @roglen provided a solution: installing background geoprocessing with a file they provided. Unfortunately this file is for ArcGIS 10.5, not 10.5.1. I reinstalled Background GP for 10.5.1 but I still get the same error.
@daren-thomas importing arcgisscripting in the ArcGIS Python console surprisingly does work... but it just does not seem to work when called from the Heatmaps tool. Any ideas?

**Comment by martin-mosteiro** [comment]
As pointed out by @shizhongming, I can successfully run the heatmaps tool from Pycharm... just not ArcGIS
```
C:\Users\User\Miniconda2\envs\cea\python.exe C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/plots/heatmaps.py
Running heatmaps with scenario = C:\reference-case-WTP\CBD_low_density
Running heatmaps with file-to-analyze = C:\reference-case-WTP\CBD_low_density\outputs\data\demand\Total_demand.csv
Running heatmaps with analysis-fields = ['Qcs_MWhyr', 'Qhs_MWhyr']

Process finished with exit code 0
```

**Comment by daren-thomas** [comment]
I'll be in the office tomorrow and will have a look at it then.

**Comment by daren-thomas** [comment]
@martin-mosteiro - Is this still an issue?

**Comment by martin-mosteiro** [comment]
@daren-thomas Yep, there have been no updates since a week ago from my side so the problem is still there. Basically, to summarize:
- I have ArcGIS 10.5.1 with BackgroundGP for 10.5.1
- Some features don't work with this (`ImportError: DLL load failed: %1 is not a valid Win32 application.`)
- We know we can fix such issues for ArcGIS 10.5 using the file @roglen and @shizhongming provided, but it's not compatible with 10.5.1.

So that's still the status. Given that my presentation is done and we won't use my computer tomorrow, this is relatively low priority now, but we can give it another look next week if you're available.

**Comment by daren-thomas** [comment]
@martin-mosteiro is this still not working on your system? i'd like to give it another try. are you in tomorrow?

**Comment by daren-thomas** [comment]
This could be similar to the problem @gabriel-happle had in #1291 
Suggestion: re-install Anaconda but UNCHECK setting it as the default python...

**Comment by martin-mosteiro** [comment]
@daren-thomas Thanks for the suggestion, this unfortunately did *not* work, though :(

**Comment by daren-thomas** [comment]
huh... when do you have time to look at this this week?
