### ISSUE TITLE
Plots: LCA plots cannot run without running the cost analysis feature first

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1355]
When trying to generate the plots for LCA, I get the below error. This is because the tool asks me to run the cost analysis first, then the plots feature would run correctly. This is not urgent, but would be great to fix it.
@JIMENOFONSECA can you please take care of this issue?

```
Executing: PlotsTool C:\reference-case\reference-case-WTP\RES_low_density # # life_cycle 1;2;3 ind1 DH #
Start Time: Fri May 18 15:19:36 2018
Running script PlotsTool...
Executing: C:\ProgramData\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli plots --buildings  --network-names  --scenario C:\reference-case\reference-case-WTP\RES_low_density --network-type DH --scenarios  --individual ind1 --generations 1, 2, 3 --categories life_cycle
Running plots for the next categories = ['life_cycle']
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 76, in main
    plots_main(config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 50, in plots_main
    plots_lca(locator, config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\life_cycle\main.py", line 32, in plots_main
    plots = Plots(locator, buildings)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\life_cycle\main.py", line 58, in __init__
    self.data_processed = self.preprocessing_building_costs()
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\life_cycle\main.py", line 86, in preprocessing_building_costs
    data_raw = pd.read_csv(self.locator.get_costs_operation_file()).set_index('Name')
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\io\parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas\_libs\parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas\_libs\parsers.c:8873)
IOError: File C:\reference-case\reference-case-WTP\RES_low_density\outputs\data\costs\operation_costs.csv does not exist


Traceback (most recent call last):
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 77, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 164, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (PlotsTool).
Failed at Fri May 18 15:19:40 2018 (Elapsed Time: 4.25 seconds)

```

**Comment by JIMENOFONSECA** [comment]
@amraladdin yep, LCA also accounts for the costs. So according to the manual of CEA you need to run it.
