### ISSUE TITLE
Error in PVT script

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1373]
```
Running C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Running photovoltaic-thermal with scenario = C:\Users\Gabriel\Documents\GitHub\cea-reference-case\reference-case-WTP\03_MIX_medium_density\new baseline - Copy
Running photovoltaic-thermal with date-start = 2016-01-01 00:00:00
Running photovoltaic-thermal with dpl = 200.0
Running photovoltaic-thermal with eff-pumping = 0.6
Running photovoltaic-thermal with fcr = 1.3
Running photovoltaic-thermal with k-msc-max = 0.217
Running photovoltaic-thermal with annual-radiation-threshold = 1100000.0
Running photovoltaic-thermal with panel-on-roof = True
Running photovoltaic-thermal with panel-on-wall = True
Running photovoltaic-thermal with ro = 1000.0
Running photovoltaic-thermal with solar-window-solstice = 4
Running photovoltaic-thermal with t-in-pvt = 35.0
Running photovoltaic-thermal with t-in-sc = 75.0
Running photovoltaic-thermal with type-pvpanel = PV1
Running photovoltaic-thermal with type-scpanel = SC1

...

Building B006 done - time elapsed: 156.905952838  seconds
reading weather data done
calculating solar properties done
gathering properties of PVT collector panel
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py:413: RuntimeWarning: divide by zero encountered in double_scalars
  Tout = Tamb_C + q_rad_Wperm2 / (c1_pvt + 0.5)
C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py:450: RuntimeWarning: invalid value encountered in double_scalars
  q_fluid_Wperm2 = (ToutSeg - TinSeg) * Mfl_kgpers * Cp_fluid_JperkgK / Aseg_m2
C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py:458: RuntimeWarning: invalid value encountered in double_scalars
  q_out_kW = Mfl_kgpers * Cp_fluid_JperkgK * (ToutSeg - Tin_C) / 1000  # [kW]
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\technologies\solar\solar_collector.py:569: RuntimeWarning: invalid value encountered in add
  Tout = Tfl[1] + (qgain_Whperm2 * delts) / C_eff  # eq.(8)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 637, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 615, in main
    latitude=latitude, longitude=longitude, weather_path=config.weather, building_name=building)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 103, in calc_PVT
    panel_properties_SC, panel_properties_PV, settings)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 231, in calc_PVT_generation
    absorbed_radiation_PV_Wperm2, T_cell_C, module_area_per_group_m2)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/technologies/solar/photovoltaic_thermal.py", line 503, in calc_PVT_module
    aperture_area_m2)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\technologies\solar\solar_collector.py", line 777, in calc_optimal_mass_flow
    mass_flow_opt[time] = mass_flow_all_kgpers[ix_max_heat_production[0][0]]
IndexError: index 0 is out of bounds for axis 0 with size 0```

**Comment by gabriel-happle** [comment]
This error occurred when running my case study (03 Mix medium) from PyCharm.
When running the same script from ArcGIS interface, ArcGIS gets stuck (not responding without crashing).

**Comment by gabriel-happle** [comment]
I already have a branch with a workaround @shanshanhsieh 
same number as issue
