### ISSUE TITLE
Demand plots don't work

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1384]
After synchronizing to the latest master. Installing Toolbox for ArcGIS, tried to run the plots. Here are the results:
- "Solar potential" plots were generated successfully.
- "Solar technology potentials" plots were generated successfully.
- "LCA" plots ran successfully.
- **"Demand" plots did not run, due to the following error**:
```
Executing: PlotsTool SIN C:\reference-case\reference-case-WTP\RES_low_density inputs # energy_demand 1;2;3 ind1 DH #
Start Time: Wed May 23 16:37:05 2018
Running script PlotsTool...
Executing: C:\ProgramData\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli plots --buildings  --network-names  --scenario C:\reference-case\reference-case-WTP\RES_low_density --region SIN --network-type DH --scenarios inputs --individual ind1 --generations 1, 2, 3 --categories energy_demand
Running plots for the next categories = ['energy_demand']
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 33, in main
    script_module.main(config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 77, in main
    plots_main(config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\plots_main.py", line 44, in plots_main
    plots_demand(locator, config)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\demand\main.py", line 42, in plots_main
    plots = Plots(locator, config, buildings)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\demand\main.py", line 106, in __init__
    self.data_processed = self.preprocessing_building_demand()
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\demand\main.py", line 139, in preprocessing_building_demand
    df[field] = df[field].values + df2[field].values
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 'E_kWh'


Traceback (most recent call last):
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 77, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 164, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (PlotsTool).
Failed at Wed May 23 16:37:08 2018 (Elapsed Time: 3.47 seconds)
```

**Comment by gabriel-happle** [comment]
@amraladdin you have to re-run the demand calculation.
For the new plots some new columns from the output files are needed.
I checked the demand plots yesterday, they seemed fine.

**Comment by amraladdin** [comment]
@gabriel-happle I did, but it was too late and had to leave, so I didn't do the plots. It worked fine in the lab when I tried it, so I think that's the reason. I'll check again and update.

**Comment by gabriel-happle** [comment]
@amraladdin can this issue be closed?

**Comment by amraladdin** [comment]
Yes, sorry for the late reply :)
