### ISSUE TITLE
Thermal networks plots didn't work during test run

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1402]
1-The choice of heating or cooling network should not be hidden under "Advanced" options since it is necessary in order to run the thermal networks plots.
2-The following error occurred when running the plots for DC for the CBD_medium_density case study:
```
Executing: PlotsTool SIN C:\temp\reference-case-WTP\reference-case-WTP\01_CBD_medium_density 01_CBD_medium_density # thermal_network 1;2;3 ind1 DC #
Start Time: Fri May 25 13:39:17 2018
Running script PlotsTool...
Executing: C:\ProgramData\CityEnergyAnalyst\python.exe -u -m cea.interfaces.cli.cli plots --buildings  --network-names  --scenario C:\temp\reference-case-WTP\reference-case-WTP\01_CBD_medium_density --region SIN --network-type DC --scenarios 01_CBD_medium_density --individual ind1 --generations 1, 2, 3 --categories thermal_network
Running `cea plots` with the following parameters:
- general:region = SIN
- general:scenario = C:\temp\reference-case-WTP\reference-case-WTP\01_CBD_medium_density
- plots:scenarios = ['01_CBD_medium_density']
- plots:buildings = []
- plots:categories = ['thermal_network']
- plots:generations = ['1', '2', '3']
- plots:individual = ind1
- plots:network-type = DC
- plots:network-names = []
Running plots for the next categories = ['thermal_network']
Creating plots for network:
C:\ProgramData\CityEnergyAnalyst\lib\site-packages\numpy\core\fromnumeric.py:57: RuntimeWarning:

invalid value encountered in rint

This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.


Traceback (most recent call last):
  File "C:\Users\TEMP\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 90, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\TEMP\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 177, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (PlotsTool).
Failed at Fri May 25 13:39:29 2018 (Elapsed Time: 11.67 seconds)
```

**Comment by daren-thomas** [comment]
@martin-mosteiro does it work on your local computer?

**Comment by martin-mosteiro** [comment]
@daren-thomas Don't know. I'll test it and get back to you.

**Comment by martin-mosteiro** [comment]
@daren-thomas Interesting. Thermal network plots do work on my own computer.

**Comment by daren-thomas** [comment]
@martin-mosteiro what is the current status of this bug?

**Comment by martin-mosteiro** [comment]
I just updated you 14 minutes ago.

**Comment by martin-mosteiro** [comment]
I have not tested this issue on the computer room again and don't think it's worth it. If no one else has this issue, feel free to close it.
