### ISSUE TITLE
module import error for documentation analysis/clustering

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1407]
getting the following error message when trying to build the documentation for clustering:

``WARNING: autodoc: failed to import module u'cea.analysis.clustering.sax.clustering_main'; the following exception was raised:
Traceback (most recent call last):
  File "c:\users\assistenz\miniconda2\envs\cea\lib\site-packages\sphinx\ext\autodoc\importer.py", line 140, in import_module
    __import__(modname)
  File "c:\users\assistenz\documents\github\cityenergyanalyst\cea\analysis\clustering\sax\clustering_main.py", line 18, in <module>
    from cea.analysis.clustering.sax.sax_optimization import sax_optimization
  File "c:\users\assistenz\documents\github\cityenergyanalyst\cea\analysis\clustering\sax\sax_optimization.py", line 13, in <module>
    import deap.benchmarks.tools
RuntimeError: sys.path must be a list of directory names``

**Comment by daren-thomas** [comment]
@Jack-Hawthorne, please add the branch this is in and reproduction steps (I'm assuming you have excluded this module from the documentation build, so when we go to fix this error, we'll have to re-include it and having a paper trail would help)

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne @daren-thomas can we close this issue?
