### ISSUE TITLE
`cea test --reference-cases all` No such file or directory: cea_github.auth

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1417]
```
cea test --reference-cases all
Running `cea test` with the following parameters:
- test:reference-cases = ['all']
- test:tasks = ['all']
- test:verbosity = 1
Configuring task download_radiation
Configuring task run_embodied_energy
Configuring task run_heatmaps
Configuring task run_thermal_network_matrix
Configuring task run_emissions_mobility
Configuring task download_reference_cases
Configuring task run_calibration
Configuring task run_emissions_operation
Configuring task run_scenario_plots
Configuring task run_sensitivity
Configuring task run_unit_tests
Configuring task run_data_helper
Configuring task run_demand
.  download_reference_cases
########################################
TaskError - taskid:download_reference_cases
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\user\documents\github\cityenergyanalyst\cea\tests\dodo.py", line 124, in download_reference_cases
    r = requests.get(REPOSITORY_URL % REPOSITORY_NAME, auth=get_github_auth())
  File "c:\users\user\documents\github\cityenergyanalyst\cea\tests\dodo.py", line 90, in get_github_auth
    with open(os.path.expanduser('~/cea_github.auth')) as f:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\User/cea_github.auth'
```

@daren-thomas Is this the issue you referred to today when we discussed testing all scenarios locally?

**Comment by daren-thomas** [comment]
No, for running the `--reference-cases all` parameter, you need to set up an authentication token for GitHub. The documentation is here: http://city-energy-analyst.readthedocs.io/en/latest/how-to-test-the-cea.html#running-tests-locally

But note that it is old - the `--save` command doesn't work anymore. Instead, just create a text file with two lines, first is github user-name, second is the authentication token.

Also, please update the documentation to reflect this. Can I assign you the issue?

**Comment by daren-thomas** [comment]
@martin-mosteiro I just went ahead and updated the documentation online.
