### ISSUE TITLE
Running optimization for the first time gives an error corresponding to non existent folder

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1441]
electricity
Process-heat
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.3.3\helpers\pydev\pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 124, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 115, in main
    moo_optimization(locator=locator, weather_file=weather_file, gv=gv, config=config)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/optimization/optimization_main.py", line 56, in moo_optimization
    prices)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\optimization\preprocessing\preprocessing_main.py", line 106, in preproccessing
    results.to_csv(locator.get_preprocessing_costs(), index=False)
  File "C:\Users\Bhargava\Anaconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 1403, in to_csv
    formatter.save()
  File "C:\Users\Bhargava\Anaconda2\envs\cea\lib\site-packages\pandas\io\formats\format.py", line 1577, in save
    compression=self.compression)
  File "C:\Users\Bhargava\Anaconda2\envs\cea\lib\site-packages\pandas\io\common.py", line 379, in _get_handle
    f = open(path_or_buf, mode)
IOError: [Errno 2] No such file or directory: 'C:\\reference-case-WTP-reduced\\WTP_CBD_m\\outputs\\data\\optimization\\slave/preprocessing_costs.csv'

This is because of not ensuring the folder is present

**Comment by BhargavaKrishnaSreepathi** [comment]
fixed in PR #1443
