### ISSUE TITLE
Benchmark-graphs not working in master (KeyError: the label [PARKING] is not in the [index])

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1469]
When running the `cea benchmark-graphs` tool from master (572e2e78306d752500191d56eeb0e0999e083155) I get the following error:

```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (master)
λ cea benchmark-graphs
Running `cea benchmark-graphs` with the following parameters:
- benchmark-graphs:project = C:\reference-case-open
- benchmark-graphs:scenarios = ['baseline']
- benchmark-graphs:output-file = C:\reference-case-open/benchmark-graphs.pdf
Running benchmark-graphs with project = C:\reference-case-open
Running benchmark-graphs with scenarios = ['baseline']
Running benchmark-graphs with output-file = C:\reference-case-open/benchmark-graphs.pdf
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 48, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\benchmark.py", line 295, in main
    benchmark(locator_list=locator_list, output_file=config.benchmark_graphs.output_file, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\benchmark.py", line 61, in benchmark
    targets = calc_benchmark_targets(locator_list[0], config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\benchmark.py", line 180, in calc_benchmark_targets
    if factors.loc[use, 'NRE_target_retrofit'] > 0 and factors.loc[use, 'CO2_target_retrofit'] > 0:
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 836, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1551, in _getitem_axis
    self._has_valid_type(key, axis)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1442, in _has_valid_type
    error()
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: u'the label [PARKING] is not in the [index]'
```

I'm moving this to the M3 milestone as I don't think we'll be using this tool for the executive course...

**Comment by martin-mosteiro** [comment]
@daren-thomas Benchmark graphs are not even available in the ArcGIS interface, so this indeed is not a feature that will be used in the executive course. The fix should be easy.... provided the fix is what I think it is.

**Comment by daren-thomas** [comment]
@martin-mosteiro do you know anything about scenario-plots? do they need to work for the executive course?

**Comment by martin-mosteiro** [comment]
I believe the idea was for scenario-plots to supersede the benchmark graphs, but it's one of those features that hasn't been working for me (#1335), so I haven't been able to test it. Mañana. 
In the mean time, perhaps @JIMENOFONSECA can give some insight.

**Comment by JIMENOFONSECA** [comment]
Hi, so basically we need to run three scenarios and put them in the same folder of one case study. Then the scenario comparisons should work.

To test it, o just copy paste twice the current scenario i am working on
On 12 Jun 2018, 00:14 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

I believe the idea was for scenario-plots to supersede the benchmark graphs, but it's one of those features that hasn't been working for me (#1335<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1335>), so I haven't been able to test it. Mañana.
In the mean time, perhaps @JIMENOFONSECA<https://github.com/JIMENOFONSECA> can give some insight.

**Comment by JIMENOFONSECA** [comment]
this was fixed during the exectuive course of 2018
