### ISSUE TITLE
CEA network-layout does not work for `reference-case-open/baseline`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1479]
I tried running `cea network-layout` and got the following output:

```
λ cea network-layout
Running `cea network-layout` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
- network-layout:network-type = DC
- network-layout:pipe-diameter = 150
- network-layout:type-mat = T1
- network-layout:create-plant = True
- network-layout:allow-looped-networks = False
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 53, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\main.py", line 54, in main
    network_layout(config, locator)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\main.py", line 35, in network_layout
    calc_substation_location(input_buildings_shp, output_substations_shp)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\substations_location.py", line 34, in calc_substation_location
    poly = poly.to_crs(get_projected_coordinate_system(lat, lon))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\utilities\standarize_coordinates.py", line 53, in get_projected_coordinate_system
    utm_data = utm.from_latlon(lat, lon)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\utm\conversion.py", line 155, in from_latlon
    raise OutOfRangeError('latitude out of range (must be between 80 deg S and 84 deg N)')
utm.error.OutOfRangeError: latitude out of range (must be between 80 deg S and 84 deg N)
```

@JIMENOFONSECA  do you know who would best be suited to fixing this?

**Comment by JIMENOFONSECA** [comment]
I can check this out. Is this in master?
On 11 Jun 2018, 22:29 +0800, Daren Thomas <notifications@github.com>, wrote:

I tried running cea network-layout and got the following output:

λ cea network-layout
Running `cea network-layout` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
- network-layout:network-type = DC
- network-layout:pipe-diameter = 150
- network-layout:type-mat = T1
- network-layout:create-plant = True
- network-layout:allow-looped-networks = False
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 53, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\main.py", line 54, in main
    network_layout(config, locator)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\main.py", line 35, in network_layout
    calc_substation_location(input_buildings_shp, output_substations_shp)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\network_layout\substations_location.py", line 34, in calc_substation_location
    poly = poly.to_crs(get_projected_coordinate_system(lat, lon))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\utilities\standarize_coordinates.py", line 53, in get_projected_coordinate_system
    utm_data = utm.from_latlon(lat, lon)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\utm\conversion.py", line 155, in from_latlon
    raise OutOfRangeError('latitude out of range (must be between 80 deg S and 84 deg N)')
utm.error.OutOfRangeError: latitude out of range (must be between 80 deg S and 84 deg N)


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> do you know who would best be suited to fixing this?
