### ISSUE TITLE
cea optimization does not work for C:\reference-case-open\baseline (ValueError: A value in x_new is below the interpolation range.)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1480]
I get this error when running the `cea optimization` script with the scenario from `cea extract-reference-case`.

@BhargavaKrishnaSreepathi 

- do you know why this happens? 
- what should be done in this case? 
- could it in theory show up during the executive course?
- who should fix it?
- when should we fix it?

```
λ cea optimization
Running `cea optimization` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
- general:region = CH
- general:weather = c:\users\darthoma\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw
- thermal-network:network-type = DH
- thermal-network:network-names = []
- optimization:initialind = 3
- optimization:halloffame = 20
- optimization:ngen = 3
- optimization:fcheckpoint = 1
- optimization:maxtime = 604800
- optimization:iscooling = False
- optimization:isheating = True

[...]

Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 53, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, gv=gv, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 65, in moo_optimization
    network_features, gv, config, prices)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 183, in evolutionary_algo_main
    a = objective_function(i, ind, genCP)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 100, in objective_function
    network_features, gv, config, prices, individual_number, generation)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\evaluation.py", line 152, in evaluation_main
    solar_features, gv, config, prices)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\slave\slave_main.py", line 50, in slave_main
    solar_features, gv, prices, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\slave\least_cost.py", line 490, in least_cost_main
    KEV_RpPerkWhPV = calc_Crem_pv(Q_PowerPeakAvailablePV_kW * 1000.0)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\solar\photovoltaic.py", line 744, in calc_Crem_pv
    KEV_obtained_in_RpPerkWh = KEV_obtained_in_RpPerkWh + KEV_interpolated_kW(E_nom / 1000.0)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\scipy\interpolate\polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\scipy\interpolate\interpolate.py", line 610, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\scipy\interpolate\interpolate.py", line 639, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.
```

**Comment by BhargavaKrishnaSreepathi** [comment]
hey @daren-thomas, Can you tell me the process to get this error?

do you know why this happens?
We solved a similar error in another PR, it happens when the interpolation occurs outside of the range. 
what should be done in this case?
Either the range should be increased or multiple units are to be installed at a lower capacity
could it in theory show up during the executive course?
I am 99% confident that it will not show up in the executive course. The reason being, we have been running the cooling scenarios over and over to see if we get any bugs. A similar bug was encountered #1303 and was subsequently fixed
who should fix it?
Either me or shanshan needs to fix this, as we are familiar with this error.
when should we fix it?
Not sure

**Comment by daren-thomas** [comment]
hey @BhargavaKrishnaSreepathi the process to get this error:

```
λ cea optimization
Running `cea optimization` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
- general:region = CH
- general:weather = c:\users\darthoma\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw
- thermal-network:network-type = DH
- thermal-network:network-names = []
- optimization:initialind = 3
- optimization:halloffame = 20
- optimization:ngen = 3
- optimization:fcheckpoint = 1
- optimization:maxtime = 604800
- optimization:iscooling = False
- optimization:isheating = True
```
