### ISSUE TITLE
Error running optimization

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1498]
```
C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning: Falling back to the python version of hypervolume module. Expect this to be very slow.
  "module. Expect this to be very slow.", ImportWarning)
C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\matplotlib\backends\qt_compat.py:98: ImportWarning: Not importing directory 'C:\Users\darthoma\Miniconda2\envs\cea\sip': missing __init__.py
  import sip
Traceback (most recent call last):
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 121, in <module>
    main(cea.config.Configuration())
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 54, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 65, in moo_optimization
    
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 954, in evolutionary_algo_main
    
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 100, in objective_function
    
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\master\evaluation.py", line 170, in evaluation_main
    Flag=True)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\slave\cooling_main.py", line 259, in coolingMain
    T_ground_K[hour], prices, master_to_slave_vars, config, Q_cooling_req_W[hour], locator)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\slave\cooling_resource_activation.py", line 214, in cooling_resource_activator
    
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\slave\cooling_resource_activation.py", line 86, in calc_chiller_absorption_operation
    
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\chiller_absorption.py", line 70, in calc_chiller_main
    
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\io\excel.py", line 203, in read_excel
    
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\io\excel.py", line 260, in __init__
    
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\xlrd\__init__.py", line 396, in open_workbook
    
IOError: [Errno 22] Invalid argument
```

**Comment by BhargavaKrishnaSreepathi** [comment]
I suspect the error is because the excel file is open and this piece of code is trying to access it. Can you try running it again and see if the error is repeating

**Comment by daren-thomas** [comment]
can't reproduce the error. maybe that  really is what happened...
