### ISSUE TITLE
Fix ZeroDivisionError in calibration

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1509]
The following error shows up in calibration tests sometimes. The fix should be to check for this error (either check the log or `try/catch ZeroDivisionError`) and then do something sensible.

Any division that could lead to an unchecked `ZeroDivisionErrror` is to be considered a bug.

@JIMENOFONSECA can you please fix this?

```
TaskError - taskid:run_calibration
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\tests\dodo.py", line 358, in run_calibration
    calibration_sampling.sampling_main(locator=locator, config=config)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 80, in sampling_main
    simulation = simulate_demand_sample(locator, building_name, building_load, config)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 117, in simulate_demand_sample
    _ , time_series = demand_main.demand_calculation(locator, gv, config)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\demand_main.py", line 110, in demand_calculation
    format_output)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\demand_main.py", line 154, in calc_demand_singleprocessing
    format_output)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\thermal_loads.py", line 118, in calc_thermal_loads
    tsd = sensible_loads.calc_temperatures_emission_systems(bpr, tsd) # calculate temperatures
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\sensible_loads.py", line 333, in calc_temperatures_emission_systems
    Ta_sup_0, Ta_re_0, C_A)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\numpy\lib\function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\numpy\lib\function_base.py", line 2810, in _vectorize_call
    outputs = ufunc(*inputs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\technologies\heating_coils.py", line 129, in calc_cooling_coil
    dTm_0 = substation.calc_dTm_HEX(thi_0, tho_0, tci_0, tco_0, 'cool')
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\technologies\substation.py", line 754, in calc_dTm_HEX
    dTm = (dT2 - dT1) / scipy.log(dT2 / dT1)
ZeroDivisionError: float division by zero
```

**Comment by JIMENOFONSECA** [comment]
Sure, but i do not know how to catch the error. Is there a pyhton recipe for this you can teach me?, thanks!
On 18 Jun 2018, 15:44 +0800, Daren Thomas <notifications@github.com>, wrote:

The following error shows up in calibration tests sometimes. The fix should be to check for this error (either check the log or try/catch ZeroDivisionError) and then do something sensible.

Any division that could lead to an unchecked ZeroDivisionErrror is to be considered a bug.

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> can you please fix this?

TaskError - taskid:run_calibration
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\tests\dodo.py", line 358, in run_calibration
    calibration_sampling.sampling_main(locator=locator, config=config)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 80, in sampling_main
    simulation = simulate_demand_sample(locator, building_name, building_load, config)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\calibration\bayesian_calibrator\calibration_sampling.py", line 117, in simulate_demand_sample
    _ , time_series = demand_main.demand_calculation(locator, gv, config)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\demand_main.py", line 110, in demand_calculation
    format_output)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\demand_main.py", line 154, in calc_demand_singleprocessing
    format_output)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\thermal_loads.py", line 118, in calc_thermal_loads
    tsd = sensible_loads.calc_temperatures_emission_systems(bpr, tsd) # calculate temperatures
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\sensible_loads.py", line 333, in calc_temperatures_emission_systems
    Ta_sup_0, Ta_re_0, C_A)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\numpy\lib\function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\numpy\lib\function_base.py", line 2810, in _vectorize_call
    outputs = ufunc(*inputs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\technologies\heating_coils.py", line 129, in calc_cooling_coil
    dTm_0 = substation.calc_dTm_HEX(thi_0, tho_0, tci_0, tco_0, 'cool')
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\technologies\substation.py", line 754, in calc_dTm_HEX
    dTm = (dT2 - dT1) / scipy.log(dT2 / dT1)
ZeroDivisionError: float division by zero

**Comment by daren-thomas** [comment]
OK, so. There are basically two ways to do this. One is, to check the problematic line itself:

```
dTm = (dT2 - dT1) / scipy.log(dT2 / dT1)
```

The term `scipy.log(dT2 / dT1)` should never be zero. This can happen, though, if `dT2 / dT1` is 1.0. I'm guessing that happens when they are equal (or very close to equal, since we're dealing with floats).
Obviously, we need to provide a `dTm` for that case. Is it just `dT1`? idk. that's a domain specific question.

So... you can test `if scipy.log(dT2 / dT1) == 0.0: [...]` or `if dT1 == dT2: [...]` but that's a really bad idea for floats. Instead, we could use this:

```
dTm = dT1 if np.isclose(dT1, dT2) else (dT2 - dT1) / scipy.log(dT2 / dT1)
```

I like that version. More generally, the way to catch an error is like this:

```
try:
    dTm = (dT2 - dT1) / scipy.log(dT2 / dT1)
catch ZeroDivisionError:
    dTm = dT1
```

Normally, I'd say this is the way to go. Except here I think it is more explicit to actually define the boundary condition.
