### ISSUE TITLE
CEA does not support WWR=1.0

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1511]
When running the CEA with buildings with WWR=1 the demand calculation breaks.
Radiation works.

```
Running C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/demand_main.py
Backend Qt5Agg is interactive backend. Turning interactive mode on.
Running demand calculation for scenario C:\cea-case-studies-local-05-06-2018\reference-case-WTP-reduced\WTP_MIX_m
Running demand calculation with weather file C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\databases\weather\Singapore-2016.epw
Running demand calculation for region SIN
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=False
Running demand calculation with daysim radiation=True
Running demand calculation with stochastic occupancy=False
read input files
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/demand_main.py", line 211, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/demand_main.py", line 195, in main
    demand_calculation(locator=locator, gv=cea.globalvar.GlobalVariables(), config=config)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/demand_main.py", line 91, in demand_calculation
    override_variables)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/demand_main.py", line 133, in properties_and_schedule
    building_properties = BuildingProperties(locator, gv, use_daysim_radiation, region, override_variables)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\building_properties.py", line 94, in __init__
    prop_geometry, prop_HVAC_result, use_daysim_radiation)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\building_properties.py", line 268, in calc_prop_rc_model
    df = self.geometry_reader_radiation_daysim(locator, envelope, occupancy, geometry, H_F)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\demand\building_properties.py", line 364, in geometry_reader_radiation_daysim
    envelope.ix[building_name, 'Awall'] = geometry_data_sum.ix['walls', 'AREA_m2']
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexing.py", line 118, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexing.py", line 836, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1077, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexing.py", line 136, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pandas\core\generic.py", line 2032, in xs
    loc = self.index.get_loc(key)
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 'walls'
```

**Comment by JIMENOFONSECA** [comment]
to add an exception
