### ISSUE TITLE
test_schedules might be broken

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1522]
I can't run `test_schedules`. It tells me the something is wrong with the `config` file:

```
C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/test_schedules.py
read input files
done
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/test_schedules.py", line 142, in <module>
    create_test_data()
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/tests/test_schedules.py", line 132, in create_test_data
    if not config.has_section('test_mixed_use_schedules'):
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\config.py", line 50, in __getattr__
    raise AttributeError("Section or Parameter not found: %s" % item)
AttributeError: Section or Parameter not found: has_section

Process finished with exit code 1
```

**Comment by JIMENOFONSECA** [comment]
@GA
