### ISSUE TITLE
Check for `None` return value of `cea.utilities.standarize_coordinates.raster_to_WSG_and_UTM`

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1557]
this function is called from the New Project tool but can sometimes return `None`. This causes the tool to crash with the error message:

```
λ cea create-new-project
City Energy Analyst version 2.7.17
Running `cea create-new-project` with the following parameters:
- create-new-project:project = weimar-bauhaus
- create-new-project:scenario = fixed
- create-new-project:output-path = C:\
- create-new-project:zone = C:\weimar-bauhaus\baseline\inputs\building-geometry\zone.shp
- create-new-project:terrain = C:\weimar-bauhaus\baseline\inputs\topography\terrain.tif
- create-new-project:streets = C:\weimar-bauhaus\baseline\inputs\building-geometry\zone.shp
- create-new-project:district =
- create-new-project:occupancy =
- create-new-project:age =
Running create-new-project with project = weimar-bauhaus
Running create-new-project with scenario = fixed
Running create-new-project with occupancy-types =
Running create-new-project with zone = C:\weimar-bauhaus\baseline\inputs\building-geometry\zone.shp
Running create-new-project with terrain = C:\weimar-bauhaus\baseline\inputs\topography\terrain.tif
Running create-new-project with terrain = C:\weimar-bauhaus\baseline\inputs\topography\terrain.tif
Running create-new-project with output-path = C:\
Warning 1: Cannot find datum.csv or gdal_datum.csv
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 63, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\create_new_project.py", line 135, in main
    create_new_project(locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\datamanagement\create_new_project.py", line 56, in create_new_project
    driver.CreateCopy(locator.get_terrain(), terrain)
  File "c:\users\darthoma\appdata\local\conda\conda\envs\cea\lib\site-packages\osgeo\gdal.py", line 1546, in CreateCopy
    return _gdal.Driver_CreateCopy(self, *args, **kwargs)
ValueError: Received a NULL pointer.
```

**Comment by JIMENOFONSECA** [comment]
mm the terrain seems to not be working

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still an issue? I found the problem was the terrain

**Comment by JIMENOFONSECA** [comment]
@daren-thomas ??

**Comment by daren-thomas** [comment]
@JIMENOFONSECA yes, i think this is still an issue: the script should test for invalid input and provide a helpful error message.
