### ISSUE TITLE
Absorption chiller cooling (T25) cannot be modeled by thermal_loads.py

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1564]
```
Traceback (most recent call last):
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 211, in <module>
    main(cea.config.Configuration())
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 195, in main
    demand_calculation(locator=locator, gv=cea.globalvar.GlobalVariables(), config=config)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 110, in demand_calculation
    format_output, region)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 154, in calc_demand_singleprocessing
    format_output, region)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 128, in calc_thermal_loads
    tsd = calc_Qcs_sys(bpr, tsd) # final : including fuels and renewables
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 218, in calc_Qcs_sys
    raise Exception('check potential error in input database of LCA infrastructure / COOLING')
Exception: check potential error in input database of LCA infrastructure / COOLING

Process finished with exit code 1
```

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA The issue appears to be solved. I tested it locally and the results make sense to me now.
