### ISSUE TITLE
Fix the calibration tests for The Jenkins

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1609]
The Jenkins tests run the calibration tests in the task `run_calibration`. Sometimes it runs through. Sometimes it doesn't, producing this error:

```
TaskError - taskid:run_calibration
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\tests\dodo.py", line 366, in run_calibration
    calibration_main.calibration_main(locator=locator, config=config)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\calibration\bayesian_calibrator\calibration_main.py", line 81, in calibration_main
    mu = pm.Deterministic('mu', predict_y(var1, var2, var3, var4, var5, var6))
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\theano\gof\op.py", line 674, in __call__
    required = thunk()
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\theano\compile\ops.py", line 555, in perform
    outs = self.__fn(*inputs)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\cea\demand\calibration\bayesian_calibrator\calibration_main.py", line 58, in predict_y
    prediction = emulator.predict(input_sample)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\sklearn\gaussian_process\gpr.py", line 297, in predict
    X = check_array(X)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\sklearn\utils\validation.py", line 422, in check_array
    _assert_all_finite(array)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\ceatest\lib\site-packages\sklearn\utils\validation.py", line 43, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

Where does that error come from? I think it might be some combination of building properties that lead to the error happening. This probably only shows up because of some random seed not being the same for every run. Also, it is a symptom of a bug somewhere in our code (possibly in the demand calculations) - at the very least, a nicer error message should appear.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you take a look?
