### ISSUE TITLE
Mismatch in number of variables in different calibration scripts

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1619]
The `calibration_sampling` script states
```
    This script creates samples using a lating Hypercube sample of 5 variables of interest.
    then runs the demand calculation of CEA for all the samples. It delivers a json file storing
    the results of cv_rmse and rmse for each sample.
```
and even more specifically: `:param variables: input variables of CEA to sample. They must be 5!
`

However after running the sampling and gaussian emulator scripts with five variables, I reached `calibration_main` and got the following:
```
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/calibration/bayesian_calibrator/calibration_main.py", line 81, in calibration_main
    mu = pm.Deterministic('mu', predict_y(var1, var2, var3, var4, var5, var6))
NameError: global name 'var6' is not defined
```

So it seems calibration main script actually requires six variables!

@JIMENOFONSECA Any insight on this?

**Comment by martin-mosteiro** [comment]
After running the `calibration_sampling` with six variables specified, then running `calibration_gaussian_emulator`, and finally `calibration_main, I get the following error message when running the latter:
```
C:\Users\User\Miniconda2\envs\cea\python.exe C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/calibration/bayesian_calibrator/calibration_main.py
Traceback (most recent call last):
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/calibration/bayesian_calibrator/calibration_main.py", line 117, in <module>
    main(cea.config.Configuration())
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/calibration/bayesian_calibrator/calibration_main.py", line 113, in main
    calibration_main(locator, config)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/calibration/bayesian_calibrator/calibration_main.py", line 81, in calibration_main
    mu = pm.Deterministic('mu', predict_y(var1, var2, var3, var4, var5, var6))
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\theano\gof\op.py", line 674, in __call__
    required = thunk()
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\theano\compile\ops.py", line 555, in perform
    outs = self.__fn(*inputs)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/calibration/bayesian_calibrator/calibration_main.py", line 58, in predict_y
    prediction = emulator.predict(input_sample)
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\sklearn\gaussian_process\gpr.py", line 297, in predict
    X = check_array(X)
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\sklearn\utils\validation.py", line 422, in check_array
    _assert_all_finite(array)
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\sklearn\utils\validation.py", line 43, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Process finished with exit code 1
```

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro this issue is solved right?

**Comment by martin-mosteiro** [comment]
Yep!
