### ISSUE TITLE
Update plots to newest plotly release

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1634]
The plots do not seem compatible with plotly 3.2.1. Here is a stack trace found in the wild:

```
C:\Users\iA\Anaconda2\envs\cea\python.exe C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/plots/plots_main.py
Running plots for the next categories = ['demand', 'solar_potentials', 'solar_technology']
Traceback (most recent call last):
  File "C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/plots/plots_main.py", line 70, in <module>
    main(cea.config.Configuration())
  File "C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/plots/plots_main.py", line 66, in main
    plots_main(config)
  File "C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/plots/plots_main.py", line 32, in plots_main
    dashboard_solar(locator, config)
  File "C:\Users\iA\Documents\GitHub\CityEnergyAnalyst\cea\plots\solar_potential\main.py", line 48, in plots_main
    plots.solar_radiation_curve(category)
  File "C:\Users\iA\Documents\GitHub\CityEnergyAnalyst\cea\plots\solar_potential\main.py", line 149, in solar_radiation_curve
    plot = solar_radiation_curve(data, self.analysis_fields + ["T_ext_C"], title, output_path)
  File "C:\Users\iA\Documents\GitHub\CityEnergyAnalyst\cea\plots\solar_potential\solar_radiation_curve.py", line 26, in solar_radiation_curve
    plot(fig, auto_open=False, filename=output_path)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\offline\offline.py", line 476, in plot
    '100%', '100%', global_requirejs=False)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\offline\offline.py", line 154, in _plot_html
    figure = tools.return_figure_from_figure_or_data(figure_or_data, validate)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\tools.py", line 1474, in return_figure_from_figure_or_data
    figure = Figure(**figure).to_dict()
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\graph_objs\_figure.py", line 351, in __init__
    super(Figure, self).__init__(data, layout, frames, skip_invalid)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 174, in __init__
    layout, skip_invalid=skip_invalid)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\_plotly_utils\basevalidators.py", line 1898, in validate_coerce
    v = self.data_class(skip_invalid=skip_invalid, **v)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\graph_objs\_layout.py", line 3895, in __init__
    self['xaxis'] = xaxis if xaxis is not None else _v
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 3667, in __setitem__
    super(BaseLayoutHierarchyType, self).__setitem__(prop, value)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 2739, in __setitem__
    self._set_compound_prop(prop, value)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 3043, in _set_compound_prop
    val = validator.validate_coerce(val, skip_invalid=self._skip_invalid)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\_plotly_utils\basevalidators.py", line 1898, in validate_coerce
    v = self.data_class(skip_invalid=skip_invalid, **v)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\graph_objs\layout\_xaxis.py", line 2864, in __init__
    ] = rangeselector if rangeselector is not None else _v
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 2739, in __setitem__
    self._set_compound_prop(prop, value)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 3043, in _set_compound_prop
    val = validator.validate_coerce(val, skip_invalid=self._skip_invalid)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\_plotly_utils\basevalidators.py", line 1898, in validate_coerce
    v = self.data_class(skip_invalid=skip_invalid, **v)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\graph_objs\layout\xaxis\_rangeselector.py", line 601, in __init__
    self['buttons'] = buttons if buttons is not None else _v
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 2744, in __setitem__
    self._set_array_prop(prop, value)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 3117, in _set_array_prop
    val = validator.validate_coerce(val, skip_invalid=self._skip_invalid)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\_plotly_utils\basevalidators.py", line 1967, in validate_coerce
    **v_el))
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\graph_objs\layout\xaxis\rangeselector\_button.py", line 346, in __init__
    self['step'] = step if step is not None else _v
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 2748, in __setitem__
    self._set_prop(prop, value)
  File "C:\Users\iA\Anaconda2\envs\cea\lib\site-packages\plotly\basedatatypes.py", line 2984, in _set_prop
    raise err
ValueError: 
    Invalid value of type '__builtin__.str' received for the 'step' property of layout.xaxis.rangeselector.button
        Received value: 'week'

    The 'step' property is an enumeration that may be specified as:
      - One of the following enumeration values:
            ['month', 'year', 'day', 'hour', 'minute', 'second', 'all']
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas yep, as discussed some months ago, this will mean refactoring all plots. This is a won't have for this year at least.
