### ISSUE TITLE
KeyError when running data-helper from the cli

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1744]
When running cea data-helper from the cli the following KeyError is called:

```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst\docs>cea extract-reference-case
City Energy Analyst version 2.9.0
Running `cea extract-reference-case` with the following parameters:
- extract-reference-case:destination = C:\
Running extract-reference-case with destination =  C:\
Execution time: 7.76s

(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst\docs>cea data-helper
City Energy Analyst version 2.9.0
Running `cea data-helper` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
- general:region = CH
- data-helper:archetypes = ['comfort', 'architecture', 'HVAC', 'internal-loads', 'supply', 'restrictions']
C:\Users\Jack\Miniconda2\envs\cea\lib\site-packages\pysal\__init__.py:65: VisibleDeprecationWarning: PySAL's API will be changed on 2018-12-31. The last release made with this API is version 1.14.4. A preview of the next API version is provided in the `pysal` 2.0 prelease candidate. The API changes and a guide on how to change imports is provided at https://pysal.org/about
  ), VisibleDeprecationWarning)
Running data-helper with scenario = C:\reference-case-open\baseline
Running data-helper with archetypes = ['comfort', 'architecture', 'HVAC', 'internal-loads', 'supply', 'restrictions']
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py", line 397, in main
    prop_restrictions_flag=prop_restrictions_flag)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py", line 92, in data_helper
    prop_architecture_df = get_prop_architecture(categories_df, architecture_DB, list_uses)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py", line 322, in get_prop_architecture
    prop_architecture_df, architecture_DB, list_uses)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py", line 279, in correct_archetype_areas
    Ns = calc_average(Ns, indexed_DB['Ns'][current_use_code], prop_architecture_df[use][building])
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Ns'
```
It seems 'Ns' first appears in the correct_archetype_areas method of data-helper if that is any help.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro I guess you can help us in here. I remember you introduced the Ns variable right?

**Comment by martin-mosteiro** [comment]
I can't replicate the issue:
```
(cea) C:\Users\User>cea extract-reference-case
City Energy Analyst version 2.9.0
Running `cea extract-reference-case` with the following parameters:
- extract-reference-case:destination = C:\
Copied file: C:\reference-case-open\baseline\databases\CH\archetypes\construction_properties.xlsx
Copied file: C:\reference-case-open\baseline\databases\CH\archetypes\occupancy_schedules.xlsx
Copied file: C:\reference-case-open\baseline\databases\CH\archetypes\system_controls.xlsx
Copied file: C:\reference-case-open\baseline\databases\CH\systems\supply_systems.xls
Copied file: C:\reference-case-open\baseline\databases\CH\lifecycle\LCA_infrastructure.xlsx
Copied file: C:\reference-case-open\baseline\databases\CH\lifecycle\LCA_buildings.xlsx
Copied file: C:\reference-case-open\baseline\databases\CH\systems\emission_systems.xls
Copied file: C:\reference-case-open\baseline\databases\CH\systems\envelope_systems.xls
Copied file: C:\reference-case-open\baseline\databases\CH\systems\thermal_networks.xls
Copied file: C:\reference-case-open\baseline\databases\CH\benchmarks\benchmark_2000W.xls
Copied file: C:\reference-case-open\baseline\databases\CH\uncertainty\uncertainty_distributions.xls
Running extract-reference-case with destination =  C:\
Execution time: 4.20s

(cea) C:\Users\User>cea data-helper
City Energy Analyst version 2.9.0
Running `cea data-helper` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
- general:region = CH
- data-helper:archetypes = ['architecture', 'internal-loads', 'comfort', 'HVAC', 'restrictions', 'supply']
C:\Users\User\Miniconda2\envs\cea\lib\site-packages\pysal\__init__.py:65: VisibleDeprecationWarning: PySAL's API will be changed on 2018-12-31. The last release made with this API is version 1.14.4. A preview of the next API version is provided in the `pysal` 2.0 prelease candidate. The API changes and a guide on how to change imports is provided at https://migrating.pysal.org
  ), VisibleDeprecationWarning)
Running data-helper with scenario = C:\reference-case-open\baseline
Running data-helper with archetypes = ['architecture', 'internal-loads', 'comfort', 'HVAC', 'restrictions', 'supply']
c:\users\user\documents\github\cityenergyanalyst\cea\datamanagement\data_helper.py:164: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  names_df[field] = 0
Execution time: 17.41s
```

**Comment by martin-mosteiro** [comment]
@Jack-Hawthorne are you sure you are running the latest version of the master branch?

**Comment by Jack-Hawthorne** [comment]
okay so the problem was due to:

old database files which were not overwritten during the ```extract-reference-case``` execution

this should be an easy fix

**Comment by daren-thomas** [comment]
I think running `cea copy-default-databases` would have done the trick. This just for future reference. Thank you @Jack-Hawthorne & @martin-mosteiro for diagnosing this. Closing.
