### ISSUE TITLE
As a researcher, i would like to run thermal network optimization with different load types

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1757]
The current network optimization does not support load type variable, hence `optimize-network-load=True` in the **network optimization tool** is not functioning yet.
this functionality was implemented in the code in PR #1599 but it requires more bug fixes to work..

```
Individual:  [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
With  1  plant(s) at building(s): 
B004
With  0  disconnected building(s): 
Network does not have loops.
We have at least one connected building.
Running thermal_network for scenario C:\Users\zshi\Documents\WTP_MIX_m_1359
Running thermal_network for network type DC
Running thermal_network for file type shp
Running thermal_network for networks []
Running thermal_network with representative week per month.
Running thermal_network with cooling loads: ['ahu', 'aru', 'scu']
Initialize network
1.70244762244 seconds process time for Network Summary

Running substation design
B002
B003
B001
B006
B007
B004
B005
B008
B009
B010
0.177142619311 seconds process time for the Substation Routine 

Calculating edge mass flows
start calculating mass flows in edges...

 Diameter iteration number  0
Using 27 CPU's

...

test thermal_network_main() succeeded
total time:  441.822000027
Annual plant heat production: 133500802.0 [kWh]
Calculating cost of heat production at plant number:  1
population performance {5970972.4789468953: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -68978374.243107155: [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -16354916.4056: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]}
Lowest cost individual:  (-68978374.243107155, [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]) 

Traceback (most recent call last):
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 867, in <module>
    main(cea.config.Configuration())
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 862, in main
    thermal_network_optimization(config, gv, locator)
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 99, in thermal_network_optimization
    selectedPop = selectFromPrevPop(sortedPop, network_info)
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 351, in selectFromPrevPop
    next_Generation.append(sortedPrevPop[i][1])
IndexError: list index out of range

Process finished with exit code 1

```

**Comment by daren-thomas** [comment]
@shanshanhsieh do you have an estimate on how long this will take?
