### ISSUE TITLE
Thermal networks don't work on the HIL E65 computers

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1764]
This seems to be because the default ArcGIS Geodatabase is not where the CEA expects it to be (see `path_default_arcgis_db` in `cea.technologies.thermal_network_network_layout.main`) but is on a network path instead - roaming profiles.

This is urgent as @martin-mosteiro 's student needs this to work for her thesis.

Steps to reproduce:

- extract reference case
- run thermal network layout in ArcGIS with the default settings
- boom!

Current error message:

```
Traceback (most recent call last):
  File "C:\ProgramData\CityEnergyAnalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\CityEnergyAnalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\ProgramData\CityEnergyAnalyst\lib\site-packages\cea\interfaces\cli\cli.py", line 110, in <module>
    main(cea.config.Configuration())
  File "C:\ProgramData\CityEnergyAnalyst\lib\site-packages\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "C:\ProgramData\CityEnergyAnalyst\lib\site-packages\cea\technologies\thermal_network\network_layout\main.py", line 54, in main
    network_layout(config, locator)
  File "C:\ProgramData\CityEnergyAnalyst\lib\site-packages\cea\technologies\thermal_network\network_layout\main.py", line 39, in network_layout
    path_potential_network)
  File "C:\ProgramData\CityEnergyAnalyst\lib\site-packages\cea\technologies\thermal_network\network_layout\connectivity_potential.py", line 42, in calc_connectivity_network
    arcpy.CopyFeatures_management(path_connection_point_buildings_shp, memorybuildings)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.6\arcpy\arcpy\management.py", line 2563, in CopyFeatures
    raise e
arcgisscripting.ExecuteError: ERROR 000210: Cannot create output C:\Users\mmotie\Documents\ArcGIS\Default.gdb\points
Failed to execute (CopyFeatures).



Traceback (most recent call last):
  File "C:\Users\mmotie\AppData\Roaming\ESRI\Desktop10.6\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 127, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\mmotie\AppData\Roaming\ESRI\Desktop10.6\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 230, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (NetworkLayoutTool).
Failed at Thu Jan 24 10:19:59 2019 (Elapsed Time: 15.05 seconds)
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas we can close this right?
