### ISSUE TITLE
Radiation script not working on a CEA clean install

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1766]
After a clean install of CEA, I ran the radiation script and got the following error message:
```
Traceback (most recent call last):
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 10, in <module>
    from cea.resources.radiation_daysim import daysim_main, geometry_generator
  File "C:\Users\Assistenz\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\daysim_main.py", line 4, in <module>
    import py4design.py3dmodel.calculate as calculate
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py3dmodel\__init__.py", line 41, in <module>
    import fetch
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py3dmodel\fetch.py", line 21, in <module>
    import calculate
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py3dmodel\calculate.py", line 24, in <module>
    import construct
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py3dmodel\construct.py", line 25, in <module>
    import modify
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py3dmodel\modify.py", line 26, in <module>
    from OCCUtils import Construct, Common
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py3dmodel\OCCUtils\__init__.py", line 1, in <module>
    from Common import get_boundingbox
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py3dmodel\OCCUtils\Common.py", line 22, in <module>
    from OCC.Bnd import Bnd_Box
ImportError: No module named OCC.Bnd

Process finished with exit code 1
```

**Comment by martin-mosteiro** [comment]
Running on branch #1764 (which should also solve the above issue) I now ran into the following error:
```
'epw2wea' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 218, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 213, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.weather, settings)
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 166, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, building_dict, locator, weather_path, settings)
  File "C:\Users\Assistenz\Documents\GitHub\CityEnergyAnalyst\cea\resources\radiation_daysim\daysim_main.py", line 149, in isolation_daysim
    rad.execute_epw2wea(weather_path, ground_reflectance = settings.albedo)
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\py4design\py2radiance\__init__.py", line 890, in execute_epw2wea
    results = open(weaweatherfile, "r")
IOError: [Errno 2] No such file or directory: 'c:\\users\\assist~1\\appdata\\local\\temp\\temp0\\wea\\Zurich_60min.wea'
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas do you have the same error?
@martin-mosteiro would you mind writing the steps to replicate? thanks!

**Comment by martin-mosteiro** [comment]
For what it's worth, this computer is showing some other strange behavior, however. Namely, I tried to troubleshoot on a python console and I cannot seem to import config correctly, as the config file gets overwritten every time I do `import cea.config`

**Comment by Jack-Hawthorne** [comment]
I did a fresh install today of the CityEnergyAnalyst repos and cea conda environment (didn't re-install python or anaconda) and cannot run anything via the config:
```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst>cea data-helper
City Energy Analyst version 2.9.1
Running `cea data-helper` with the following parameters:
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 53, in main
    cea_script.print_script_configuration(config)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\scripts.py", line 33, in print_script_configuration
    parameter_value = parameter.get()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 330, in get
    encoded_value = self.replace_references(encoded_value)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 346, in replace_references
    encoded_value = re.sub('{([a-z0-9-]+):([a-z0-9-]+)}', lookup_config, encoded_value)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 344, in lookup_config
    return self.config.sections[matchobj.group(1)].parameters[matchobj.group(2)].get()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 332, in get
    return self.decode(encoded_value)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 627, in decode
    return self._choices[0]
IndexError: list index out of range
```

**Comment by daren-thomas** [comment]
@martin-mosteiro are you sure you installed Daysim?

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro , I am facing the same problem today, May I ask how you solved it?

**Comment by JIMENOFONSECA** [comment]
well to solve it, just check that the options of the radiation tool are pointing to a valid installation of Daysim.

![image](https://user-images.githubusercontent.com/8973186/63161406-9f102f00-c052-11e9-9f8f-34d3b0aa3681.png)
