### ISSUE TITLE
cea env needs to include mock

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1771]
Minor issue but the new conda environment (cea 2.9.1) doesn't include the mock package, leading to the following error when trying to run sphinx builds:
```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst\docs>sphinx-build -M html . _build
Running Sphinx v1.8.3

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "c:\users\jack\miniconda2\envs\cea\lib\site-packages\sphinx\config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "c:\users\jack\miniconda2\envs\cea\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "c:\users\jack\miniconda2\envs\cea\lib\site-packages\six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst\docs\conf.py", line 21, in <module>
    from mock import Mock as MagicMock
ImportError: No module named mock
```

**Comment by Jack-Hawthorne** [comment]
also noticed deap is missing:
```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst>cea trace-inputlocator --scripts multi-criteria-analysis
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 47, in main
    config.apply_command_line_args(args, cea_script.parameters)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 120, in apply_command_line_args
    section.name, parameter.name, command_line_args[parameter.name]))
ValueError: ERROR setting trace-inputlocator:scripts to multi-criteria-analysis

(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst>cea trace-inputlocator --scripts optimization
City Energy Analyst version 2.9.1
Running `cea trace-inputlocator` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
  (default: C:\reference-case-open\baseline)
- trace-inputlocator:scripts = ['optimization']
  (default: ['data-helper', 'demand', 'emissions'])
- trace-inputlocator:graphviz-output-file = C:\reference-case-open\baseline/outputs/trace_inputlocator.output.gv
  (default: C:\reference-case-open\baseline/outputs/trace_inputlocator.output.gv)
- trace-inputlocator:yaml-output-file = C:\reference-case-open\baseline/outputs/trace_inputlocator.output.yml
  (default: C:\reference-case-open\baseline/outputs/trace_inputlocator.output.yml)
City Energy Analyst version 2.9.1
Running `cea optimization` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
  (default: C:\reference-case-open\baseline)
- general:region = CH
  (default: CH)
- general:weather = c:\users\jack\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw
  (default: c:\users\jack\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw)
- general:district-heating-network = False
  (default: False)
- general:district-cooling-network = False
  (default: False)
- thermal-network:network-type = DH
  (default: DH)
- thermal-network:network-names = []
  (default: [])
- optimization:initialind = 3
  (default: 3)
- optimization:halloffame = 20
  (default: 20)
- optimization:ngen = 3
  (default: 3)
- optimization:fcheckpoint = 1
  (default: 1)
- optimization:maxtime = 604800
  (default: 604800)
- optimization:recoverycheckpoint = 0
  (default: 0)
- optimization:random-seed = None
  (default: None)
- decentralized:ahuflag = False
  (default: False)
- decentralized:aruflag = False
  (default: False)
- decentralized:scuflag = False
  (default: False)
- decentralized:ahuaruflag = False
  (default: False)
- decentralized:ahuscuflag = False
  (default: False)
- decentralized:aruscuflag = False
  (default: False)
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\tests\trace_inputlocator.py", line 50, in main
    script_func(config)  # <------------------------------ this is where we run the script!
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\api.py", line 20, in script_runner
    script_module = importlib.import_module(module_path)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\optimization\optimization_main.py", line 13, in <module>
    from cea.optimization.master import master_main
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\optimization\master\master_main.py", line 5, in <module>
    from cea.optimization.master import crossover
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\optimization\master\crossover.py", line 7, in <module>
    from deap import base
ImportError: No module named deap
```
