### ISSUE TITLE
KeyError: 'NFA_m2' when running cea operation-costs

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1782]
When running the tool `cea operation-costs`, a `KeyError: 'NFA_m2'` is produced.

Steps to reproduce:

- `cea extract-reference-case`
- `cea data-helper`
- `cea demand`
- `cea operation-costs`

Error message:

```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (master)
(cea) λ cea operation-costs
City Energy Analyst version 2.9.2
Running `cea operation-costs` with the following parameters:
- general:scenario = C:\reference-case-open\baseline
  (default: C:\reference-case-open\baseline)
- general:region = CH
  (default: CH)
Running operation-costs with scenario = C:\reference-case-open\baseline
C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\io\excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)
Traceback (most recent call last):
  File "c:\Users\darthoma\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 65, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\costs\operation_costs.py", line 104, in main
    operation_costs(locator=locator, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\costs\operation_costs.py", line 59, in operation_costs
    heating[service+'_cost_m2yr'] =  heating[service+'_cost_yr']/heating['NFA_m2']
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\darthoma\Miniconda2\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'NFA_m2'
```

**Comment by martin-mosteiro** [comment]
One of the `demand_writer`s contains a typo whereas 'NFA_m2' and 'people' get exported as 'NFA_m2people'. Missing comma. On it.
