### ISSUE TITLE
Databases are no longer copied by default?

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1888]
Running a demand simulation on a case study with no databases. I do not want to run the data helper since I am working with parameters provided by the user. I get the following error:
```
read input files
Traceback (most recent call last):
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 216, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 200, in main
    demand_calculation(locator=locator, config=config)
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 91, in demand_calculation
    override_variables)
  File "C:/Users/Assistenz/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 133, in properties_and_schedule
    building_properties = BuildingProperties(locator, use_daysim_radiation, override_variables)
  File "C:\Users\Assistenz\Documents\GitHub\CityEnergyAnalyst\cea\demand\building_properties.py", line 70, in __init__
    prop_supply_systems = get_properties_supply_sytems(locator, prop_supply_systems_building).set_index(
  File "C:\Users\Assistenz\Documents\GitHub\CityEnergyAnalyst\cea\demand\building_properties.py", line 699, in get_properties_supply_sytems
    supply_heating = pd.read_excel(locator.get_life_cycle_inventory_supply_systems(), "HEATING")
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\pandas\util\_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\pandas\io\excel.py", line 307, in read_excel
    io = ExcelFile(io, engine=engine)
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\pandas\io\excel.py", line 394, in __init__
    self.book = xlrd.open_workbook(self._io)
  File "C:\Users\Assistenz\Miniconda2\envs\cea\lib\site-packages\xlrd\__init__.py", line 111, in open_workbook
    with open(filename, "rb") as f:
IOError: [Errno 2] No such file or directory: 'C:\\reference-case-open\\baseline\\inputs\\technology\\lifecycle\\LCA_infrastructure.xlsx'
```
Shouldn't the databases be copied to the case study when they are not available in the given folder? 

As a workaround, I copied the databases from the CEA repository to the case study, but the folder structure is different... perhaps it would make sense for consistency for these to be the same?

**Comment by JIMENOFONSECA** [comment]
Nop. They are generated now with the data helper.

@channel IMPORTANT UPDATE. We erased the region parameter from general settings in CEA. This led to erasing the automatic copying of default databases (which was a hack). Now, you need to run the data helper with the category “technology”. This will copy the databases to your scenario. CEA will use the location inputs/technology to look for default databases
On 16 Apr 2019, 01:41 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

Assigned #1888<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1888> to @JIMENOFONSECA<https://github.com/JIMENOFONSECA>.

**Comment by martin-mosteiro** [comment]
Thanks for the clarification!
