### ISSUE TITLE
Fresh Install Issues

### ISSUE THREAD

**Issue by justinfmccarty** [architecture-building-systems/CityEnergyAnalyst#1909]
Hello there,

I am attempting to install CEA following steps 1-10 with fresh Pycharm, cloned repository, fresh Daysim 4.0, but have been hung up on this error: 
```
(base) C:\Users\justi>cd documents\github\cityenergyanalyst

(base) C:\Users\justi\Documents\GitHub\CityEnergyAnalyst>conda env create
Collecting package metadata: done
Solving environment: done

Downloading and Extracting Packages
msys2-conda-epoch-20 | 2 KB      | ############################################################################ | 100%
six-1.12.0           | 21 KB     | ############################################################################ | 100%
theano-1.0.3         | 3.7 MB    | ############################################################################ | 100%
libgdal-2.2.2        | 8.0 MB    | ############################################################################ | 100%
kiwisolver-1.0.1     | 66 KB     | ############################################################################ | 100%
zlib-1.2.11          | 116 KB    | ############################################################################ | 100%
vs2015_runtime-14.15 | 2.2 MB    | ############################################################################ | 100%
tornado-5.1.1        | 639 KB    | ############################################################################ | 100%
m2w64-winpthreads-gi | 45 KB     | ############################################################################ | 100%
openssl-1.0.2p       | 4.7 MB    | ############################################################################ | 100%
libpng-1.6.36        | 512 KB    | ############################################################################ | 100%
singledispatch-3.4.0 | 15 KB     | ############################################################################ | 100%
xz-5.2.4             | 297 KB    | ############################################################################ | 100%
click-plugins-1.0.4  | 10 KB     | ############################################################################ | 100%
m2w64-mpc-1.0.3      | 70 KB     | ############################################################################ | 100%
blas-1.0             | 1 KB      | ############################################################################ | 100%
icu-58.2             | 21.9 MB   | ############################################################################ | 100%
sqlite-3.26.0        | 874 KB    | ############################################################################ | 100%
tqdm-4.28.1          | 78 KB     | ############################################################################ | 100%
pytz-2018.7          | 250 KB    | ############################################################################ | 100%
m2w64-mpfr-3.1.4     | 293 KB    | ############################################################################ | 100%
geos-3.6.2           | 922 KB    | ############################################################################ | 100%
libtiff-4.0.9        | 818 KB    | ############################################################################ | 100%
gdal-2.2.2           | 773 KB    | ############################################################################ | 100%
matplotlib-2.2.3     | 6.5 MB    | ############################################################################ | 100%
intel-openmp-2019.1  | 1.7 MB    | ############################################################################ | 100%
cligj-0.5.0          | 12 KB     | ############################################################################ | 100%
chardet-3.0.4        | 191 KB    | ############################################################################ | 100%
m2w64-isl-0.16.1     | 655 KB    | ############################################################################ | 100%
m2w64-gcc-objc-5.3.0 | 15.1 MB   | ############################################################################ | 100%
numba-0.42.0         | 2.5 MB    | ############################################################################ | 100%
pythonocc-core-0.17  | 40.8 MB   | ############################################################################ | 100%
toolz-0.9.0          | 42 KB     | ############################################################################ | 100%
libnetcdf-4.4.1.1    | 457 KB    | ############################################################################ | 100%
m2w64-tools-git-5.0. | 314 KB    | ############################################################################ | 100%
m2w64-windows-defaul | 3 KB      | ############################################################################ | 100%
geopandas-0.3.0      | 918 KB    | ############################################################################ | 100%
m2w64-gcc-ada-5.3.0  | 33.5 MB   | ############################################################################ | 100%
python-dateutil-2.7. | 275 KB    | ############################################################################ | 100%
wincertstore-0.2     | 13 KB     | ############################################################################ | 100%
certifi-2018.11.29   | 146 KB    | ############################################################################ | 100%
shapely-1.6.4        | 380 KB    | ############################################################################ | 100%
backports_abc-0.5    | 12 KB     | ############################################################################ | 100%
urllib3-1.24.2       | 147 KB    | ############################################################################ | 100%
mkl-service-1.1.2    | 131 KB    | ############################################################################ | 100%
qt-5.6.2             | 55.9 MB   | ############################################################################ | 100%
markupsafe-1.1.0     | 26 KB     | ############################################################################ | 100%
m2w64-libwinpthread- | 30 KB     | ############################################################################ | 100%
m2w64-gcc-libs-5.3.0 | 518 KB    | ############################################################################ | 100%
m2w64-make-4.1.2351. | 116 KB    | ############################################################################ | 100%
freeimageplus-3.17.0 | 2.0 MB    | ############################################################################ | 100%
pygpu-0.7.6          | 585 KB    | ############################################################################ | 100%
m2w64-gmp-6.1.0      | 689 KB    | ############################################################################ | 100%
pyproj-1.9.5.1       | 3.0 MB    | ############################################################################ | 100%
libspatialite-4.3.0a | 4.0 MB    | ############################################################################ | 100%
pymc3-3.6            | 1.0 MB    | ############################################################################ | 100%
m2w64-gcc-5.3.0      | 41.1 MB   | ############################################################################ | 100%
typing-3.6.6         | 41 KB     | ############################################################################ | 100%
ca-certificates-2018 | 155 KB    | ############################################################################ | 100%
xerces-c-3.2.2       | 4.1 MB    | ############################################################################ | 100%
expat-2.2.5          | 144 KB    | ############################################################################ | 100%
pysal-1.14.4.post1   | 14.9 MB   | ############################################################################ | 100%
geopy-1.19.0         | 53 KB     | ############################################################################ | 100%
oce-0.17.2           | 25.7 MB   | ############################################################################ | 100%
cryptography-2.5     | 547 KB    | ############################################################################ | 100%
gurobi-8.1.0         | 25.4 MB   | ############################################################################ | 100%
jsonschema-3.0.1     | 101 KB    | ############################################################################ | 100%
gl2ps-1.3.8          | 96 KB     | ############################################################################ | 100%
wheel-0.32.3         | 51 KB     | ############################################################################ | 100%
hdf4-4.2.13          | 982 KB    | ############################################################################ | 100%
python-2.7.15        | 19.6 MB   | ############################################################################ | 100%
libssh2-1.8.0        | 181 KB    | ############################################################################ | 100%
networkx-2.2         | 1.1 MB    | ############################################################################ | 100%
h5py-2.7.1           | 767 KB    | ############################################################################ | 100%
m2w64-libiconv-1.14  | 1.5 MB    | ############################################################################ | 100%
idna-2.8             | 132 KB    | ############################################################################ | 100%
mkl-2019.1           | 158.3 MB  | ############################################################################ | 100%
mkl_fft-1.0.10       | 131 KB    | ############################################################################ | 100%
branca-0.3.1         | 25 KB     | ############################################################################ | 100%
pycparser-2.19       | 172 KB    | ############################################################################ | 100%
numpy-base-1.15.4    | 3.8 MB    | ############################################################################ | 100%
pyqt-5.6.0           | 4.3 MB    | ############################################################################ | 100%
m2w64-crt-git-5.0.0. | 3.4 MB    | ############################################################################ | 100%
numpy-1.15.4         | 47 KB     | ############################################################################ | 100%
proj4-4.9.3          | 3.2 MB    | ############################################################################ | 100%
enum34-1.1.6         | 54 KB     | ############################################################################ | 100%
requests-2.21.0      | 83 KB     | ############################################################################ | 100%
m2w64-headers-git-5. | 5.6 MB    | ############################################################################ | 100%
geographiclib-1.49   | 32 KB     | ############################################################################ | 100%
cffi-1.12.3          | 212 KB    | ############################################################################ | 100%
hdf5-1.10.1          | 17.7 MB   | ############################################################################ | 100%
freexl-1.0.5         | 55 KB     | ############################################################################ | 100%
click-7.0            | 116 KB    | ############################################################################ | 100%
vs2008_runtime-9.00. | 1017 KB   | ############################################################################ | 100%
funcsigs-1.0.2       | 20 KB     | ############################################################################ | 100%
llvmlite-0.27.0      | 10.1 MB   | ############################################################################ | 100%
krb5-1.16.1          | 812 KB    | ############################################################################ | 100%
win_inet_pton-1.1.0  | 7 KB      | ############################################################################ | 100%
psycopg2-2.7.5       | 286 KB    | ############################################################################ | 100%
folium-0.8.3         | 54 KB     | ############################################################################ | 100%
m2w64-gcc-fortran-5. | 10.3 MB   | ############################################################################ | 100%
setuptools-40.6.3    | 610 KB    | ############################################################################ | 100%
m2w64-gcc-libs-core- | 213 KB    | ############################################################################ | 100%
pysocks-1.6.8        | 21 KB     | ############################################################################ | 100%
pip-18.1             | 1.8 MB    | ############################################################################ | 100%
sqlalchemy-1.2.15    | 1.6 MB    | ############################################################################ | 100%
pyopenssl-19.0.0     | 79 KB     | ############################################################################ | 100%
osmnx-0.9            | 56 KB     | ############################################################################ | 100%
libkml-1.3.0         | 6.1 MB    | ############################################################################ | 100%
vincent-0.4.4        | 28 KB     | ############################################################################ | 100%
icc_rt-2019.0.0      | 9.4 MB    | ############################################################################ | 100%
asn1crypto-0.24.0    | 153 KB    | ############################################################################ | 100%
libspatialindex-1.8. | 314 KB    | ############################################################################ | 100%
pyparsing-2.3.0      | 99 KB     | ############################################################################ | 100%
m2w64-toolchain-5.3. | 2 KB      | ############################################################################ | 100%
libpq-10.5           | 3.4 MB    | ############################################################################ | 100%
decorator-4.4.0      | 11 KB     | ############################################################################ | 100%
m2w64-zlib-1.2.8     | 197 KB    | ############################################################################ | 100%
cycler-0.10.0        | 13 KB     | ############################################################################ | 100%
vc-9                 | 3 KB      | ############################################################################ | 100%
backports-1.0        | 5 KB      | ############################################################################ | 100%
fiona-1.7.10         | 622 KB    | ############################################################################ | 100%
curl-7.63.0          | 123 KB    | ############################################################################ | 100%
m2w64-binutils-2.25. | 44.3 MB   | ############################################################################ | 100%
sip-4.18.1           | 264 KB    | ############################################################################ | 100%
munch-2.3.2          | 13 KB     | ############################################################################ | 100%
configparser-3.7.3   | 36 KB     | ############################################################################ | 100%
m2w64-pkg-config-0.2 | 469 KB    | ############################################################################ | 100%
libgpuarray-0.7.6    | 313 KB    | ############################################################################ | 100%
libpython-2.1        | 39.2 MB   | ############################################################################ | 100%
tbb-4.3.6            | 737 KB    | ############################################################################ | 100%
futures-3.2.0        | 25 KB     | ############################################################################ | 100%
functools32-3.2.3.2  | 16 KB     | ############################################################################ | 100%
jinja2-2.10.1        | 91 KB     | ############################################################################ | 100%
attrs-19.1.0         | 32 KB     | ############################################################################ | 100%
jpeg-9b              | 306 KB    | ############################################################################ | 100%
joblib-0.12.5        | 336 KB    | ############################################################################ | 100%
libboost-1.67.0      | 31.7 MB   | ############################################################################ | 100%
pandas-0.23.4        | 8.8 MB    | ############################################################################ | 100%
rtree-0.8.3          | 45 KB     | ############################################################################ | 100%
mako-1.0.7           | 131 KB    | ############################################################################ | 100%
openjpeg-2.3.0       | 221 KB    | ############################################################################ | 100%
patsy-0.5.1          | 377 KB    | ############################################################################ | 100%
freetype-2.9.1       | 465 KB    | ############################################################################ | 100%
libcurl-7.63.0       | 268 KB    | ############################################################################ | 100%
descartes-1.1.0      | 8 KB      | ############################################################################ | 100%
ipaddress-1.0.22     | 18 KB     | ############################################################################ | 100%
tk-8.6.8             | 3.6 MB    | ############################################################################ | 100%
m2w64-libmangle-git- | 21 KB     | ############################################################################ | 100%
m2w64-gcc-libgfortra | 340 KB    | ############################################################################ | 100%
kealib-1.4.7         | 207 KB    | ############################################################################ | 100%
libxml2-2.9.8        | 3.2 MB    | ############################################################################ | 100%
m2w64-bzip2-1.0.6    | 100 KB    | ############################################################################ | 100%
backports.functools_ | 9 KB      | ############################################################################ | 100%
entrypoints-0.3      | 13 KB     | ############################################################################ | 100%
libiconv-1.15        | 659 KB    | ############################################################################ | 100%
altair-2.4.1         | 499 KB    | ############################################################################ | 100%
scipy-1.1.0          | 13.2 MB   | ############################################################################ | 100%
pyrsistent-0.14.11   | 71 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main::qt-5.6.2-vc9hc26998b_12'.
LinkError: post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main::qt-5.6.2-vc9hc26998b_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\justi\Miniconda2\envs\cea\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main::qt-5.6.2-vc9hc26998b_12'.
LinkError: post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main::qt-5.6.2-vc9hc26998b_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\justi\Miniconda2\envs\cea\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

CondaMultiError: LinkError: post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main::qt-5.6.2-vc9hc26998b_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\justi\Miniconda2\envs\cea\Scripts\.qt-post-link.bat
==> script messages <==
<None>
```
Following this I have tried to continue in the process:
```
(base) C:\Users\justi\Documents\GitHub\CityEnergyAnalyst>activate cea

(cea) C:\Users\justi\Documents\GitHub\CityEnergyAnalyst>pip install -e .[dev]
Unable to create process using 'C:\Users\justi\Miniconda2\envs\cea\python.exe C:\Users\justi\Miniconda2\envs\cea\Scripts\pip-script.py install -e .[dev]'
```

Any advice would be greatly appreciated.

**Comment by JIMENOFONSECA** [comment]
Hi @justinfmccarty would you mind trying our new all-in-one-step installer? #1908 

Let us know if this works for you!

**Comment by justinfmccarty** [comment]
@JIMENOFONSECA, the installer seems to have worked. About 20 minutes with the developer option checked. I was able to launch the dashboard (looking great) and migrate to the project we have created for one of our Vancouver test zones. The geometry appeared and everything looked right. There was an error when I launched the dashboard though:
```

City Energy Analyst version 2.12.0a1
Running `cea dashboard` with the following parameters:
 * Serving Flask app "cea.interfaces.dashboard.dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
City Energy Analyst version 2.12.0a1
Running `cea dashboard` with the following parameters:
 * Debugger is active!
 * Debugger PIN: 150-575-982
 * Running on http://localhost:5050/ (Press CTRL+C to quit)
```

I had to manually open http://localhost:5050 as well. But, nothing seems to be out of place. I will dig more into it tomorrow.

Thank you for passing that along!

**Comment by justinfmccarty** [comment]
I have been able to work from the new installer on the reference case. I tried to use our own project but was thwarted when running `radiation_main.py`. Error below, but I think you all already know about it:
```
C:\CityEnergyAnalyst\Dependencies\Python\python.exe C:/CityEnergyAnalyst/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py
DEBUG:shapely.geos:Trying `CDLL(C:\CityEnergyAnalyst\Dependencies\Python\Library\bin\geos_c.dll)`
DEBUG:shapely.geos:Library path: 'C:\\CityEnergyAnalyst\\Dependencies\\Python\\Library\\bin\\geos_c.dll'
DEBUG:shapely.geos:DLL: <CDLL 'C:\CityEnergyAnalyst\Dependencies\Python\Library\bin\geos_c.dll', handle 9d2d0000 at c930588>
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
verifying geometry files
C:\CityEnergyAnalyst\CityEnergyAnalyst\reference-case-open\baseline\inputs\building-geometry\zone.shp
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Projection not found (cogr_crs was NULL)
DEBUG:Fiona:Projection not found (cogr_crs was NULL)
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Projection not found (cogr_crs was NULL)
DEBUG:Fiona:Projection not found (cogr_crs was NULL)
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
Generating geometry for building B10
burning building  B10
Generating geometry for building B11
burning building  B11
Generating geometry for building B12
burning building  B12
Generating geometry for building B13
burning building  B13
Generating geometry for building B14
burning building  B14
Generating geometry for building B15
burning building  B15
Generating geometry for building B16
burning building  B16
Generating geometry for building B01
burning building  B01
Generating geometry for building B02
burning building  B02
Generating geometry for building B03
burning building  B03
Generating geometry for building B04
burning building  B04
Generating geometry for building B05
burning building  B05
Generating geometry for building B06
burning building  B06
Generating geometry for building B07
burning building  B07
Generating geometry for building B08
burning building  B08
Generating geometry for building B09
burning building  B09
Sending the scene: geometry and materials to daysim
	radiation_main: rad.base_file_path: c:\users\justi\appdata\local\temp\default_materials.rad
	radiation_main: rad.data_folder_path: c:\users\justi\appdata\local\temp
	radiation_main: rad.command_file: c:\users\justi\appdata\local\temp\command.txt
	radiation_main: rad.rad_file_path: c:\users\justi\appdata\local\temp\geometry.rad
isolation_daysim: daysim_dir=c:\users\justi\appdata\local\temp\temp0
	isolation_daysim: rad.hea_file: c:\users\justi\appdata\local\temp\temp0\temp0.hea
	isolation_daysim: rad.hea_filename: None
	isolation_daysim: rad.daysimdir_ies: c:\users\justi\appdata\local\temp\temp0\ies
	isolation_daysim: rad.daysimdir_pts: c:\users\justi\appdata\local\temp\temp0\pts
	isolation_daysim: rad.daysimdir_rad: c:\users\justi\appdata\local\temp\temp0\rad
	isolation_daysim: rad.daysimdir_res: c:\users\justi\appdata\local\temp\temp0\res
	isolation_daysim: rad.daysimdir_tmp: c:\users\justi\appdata\local\temp\temp0\tmp
	isolation_daysim: rad.daysimdir_wea: c:\users\justi\appdata\local\temp\temp0\wea
Calculating and sending sensor points
	isolation_daysim: rad.sensor_file_path: c:\users\justi\appdata\local\temp\points_0.pts
Starting Daysim simulation starts for buildings [u'B01', u'B02', u'B03', u'B04', u'B05', u'B06', u'B07', u'B08', u'B09']
Total number of sensors:  2349
Executing epw2wea
Executing radfiles2daysim
Writing radiance parameters
Executing gen_dc
'C:\CityEnergyAnalyst\Dependencies\Daysim\oconv' is not recognized as an internal or external command,
operable program or batch file.
=======================================================
rtrace_dc: fatal - (c:\users\justi\appdata\local\temp\temp0\tmp\/static_system.dir.oct): not an octree
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
'C:\CityEnergyAnalyst\Dependencies\Daysim\oconv' is not recognized as an internal or external command,
operable program or batch file.
rtrace_dc: fatal - (c:\users\justi\appdata\local\temp\temp0\tmp\/static_system.dif.oct): not an octree
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
Executing ds_illum
ds_illum: fatal error: File c:\users\justi\appdata\local\temp\temp0\res\temp0.dc does not contain any uncommented lines.

IN CASE YOU ARE USING DAYSIM UNDER WINDOWS, THE "RAPYPATH" VARIALBE MIGHT NOT HAVE BEEN SET CORRECTLY. TO TEST THIS, OPEN A DOS PROMPT AND TYPE 'set'. AMONG THE VARIALBLES DISPLAYED SHOULD BE 'Raypath c:\Daysim\lib'.
PLEASE REFER TO THE DAYSIM TUTORIAL FOR MORE INFORMATION...Evaluating illumination per sensor
Traceback (most recent call last):
  File "C:/CityEnergyAnalyst/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 219, in <module>
    main(cea.config.Configuration())
  File "C:/CityEnergyAnalyst/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 214, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.weather, settings)
  File "C:/CityEnergyAnalyst/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 165, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, building_dict, locator, weather_path, settings)
  File "C:\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation_daysim\daysim_main.py", line 173, in isolation_daysim
    solar_res = rad.eval_ill_per_sensor()
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\py4design\py2radiance\__init__.py", line 1158, in eval_ill_per_sensor
    res_dict_list = self.eval_ill()
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\py4design\py2radiance\__init__.py", line 1130, in eval_ill
    ill_file = open(ill_path, "r")
IOError: [Errno 2] No such file or directory: 'c:\\users\\justi\\appdata\\local\\temp\\temp0\\res\\temp0.ill'

Process finished with exit code 1

```

I made it through the intial demand and network layout calulcations with the reference case, but was faced with another error  during `decentralized_building_main`. #1825 - Same `ValueError: cannot convert float NaN to integer` Is there a fix for this that I missed in 1825?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas any clue about this?

**Comment by justinfmccarty** [comment]
I seem to have worked past it. I removed the CEA install and my C:\Daysim installation two days ago and then installed the CEA using the installer. When running `radiation_main` I ended with the error `IOError: [Errno 2] No such file or directory: 'c:\\users\\justi\\appdata\\local\\temp\\temp0\\wea\\Zug_60min.wea'`. I read in some issue in the log that this was a result of no RAYPATH or PATH variables. I checked my variables and there was nothing from Daysim or Radiance. So I added C:\Users\justi\CityEnergyAnalyst\Dependencies\ to PATH and RAYPATH.

This got me past the no .wea error but brought on `IOError: [Errno 2] No such file or directory: 'c:\\users\\justi\\appdata\\local\\temp\\temp0\\res\\temp0.ill'`. In my Daysim Dependencies there were only four .exe's were `.ds_illum`, `.epw2wea`, `.radfiles2daysim`, `.rtrace_dc`. I added `.oconv`, and `.gen_dc`. This led to an error about some missing .cal's so I dropped those all in as well. **Works now**. I have not reinstalled Daysim to C:\ yet.

**Comment by daren-thomas** [comment]
Newer versions of the installer (still under development) solve this. Try this one: https://www.dropbox.com/s/iavdblwizr9x9v0/Setup_CityEnergyAnalyst_2.13.exe?dl=0

The CEA console provided there has the RAYPATH variable set and I added some missing Daysim binaries. Does this help?

**Comment by justinfmccarty** [comment]
@daren-thomas Installed and works great inside of the console.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I just installed it, but using the link in the github repository, The last release 2.13. It does not work on my computer. Is by any chance this file in the dropboxlink different than that one in github?

![image](https://user-images.githubusercontent.com/8973186/57344660-a5049300-717a-11e9-9307-a20a56072a6b.png)

Following the comments of justin, it seems the installer did not get all the daysim binaries:

![image](https://user-images.githubusercontent.com/8973186/57344708-daa97c00-717a-11e9-999a-bcab286fd25d.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA yes, the dropbox link is newer. Here's the newest version I'm working with. It runs radiation-daysim from the cea console: https://www.dropbox.com/s/upxsegqkcf1c716/Setup_CityEnergyAnalyst_2.13.3.exe?dl=0

I'm still working on getting the Dashboard to run through (some setting of environment variables required).

Not all Daysim binaries are included. Only the ones we actually use. But a few more than shown in your screenshot above.

**Comment by JIMENOFONSECA** [comment]
Got, it. Is it possible to reemplaze this installer cersion with the one in github releases? Just because people download the tool almost every day..and it would be good to give them the most updated version...

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 8 May 2019, 15:52 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> yes, the dropbox link is newer. Here's the newest version I'm working with. It runs radiation-daysim from the cea console: https://www.dropbox.com/s/upxsegqkcf1c716/Setup_CityEnergyAnalyst_2.13.3.exe?dl=0

I'm still working on getting the Dashboard to run through (some setting of environment variables required).

Not all Daysim binaries are included. Only the ones we actually use. But a few more than shown in your screenshot above.
