### ISSUE TITLE
Cooling-Case-Workflow fails with IOError

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1958]
I just ran the `cea cooling-case-workflow` on the master branch over night and got the following error message:

```
IOError: File [...]\outputs\data\optimization\network\layout\DC__P_DeltaP_kW.csv does not exist
```

I was wondering, @shanshanhsieh, if the name of that file got changed somewhere? Here is more context of the error:

```
calculating thermal hydraulic properties of DC network  ...  time step 2011
calculating thermal hydraulic properties of DC network  ...  time step 2012
calculating thermal hydraulic properties of DC network  ...  time step 2013
calculating thermal hydraulic properties of DC network  ...  time step 2014
calculating thermal hydraulic properties of DC network  ...  time step 2015
Completed thermal-hydraulic calculation.

test thermal_network_main() succeeded
total time:  522.707000017
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 56, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\cooling_case_workflow.py", line 86, in main
    run(script, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\cooling_case_workflow.py", line 54, in run
    f(config=config, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 27, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network_optimization.py", line 859, in main
    thermal_network_optimization(config, gv, locator)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network_optimization.py", line 94, in thermal_network_optimization
    sortedPop = network_cost_calculation(newMutadedGen, network_info, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network_optimization.py", line 158, in network_cost_calculation
    capex_total, opex_total, total_cost, cost_storage_df = objective_function(network_info)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network_optimization.py", line 331, in objective_function
    Capex_total, Opex_total, Costs_total, cost_storage = network_costs.calc_Ctot_cs_district(network_info)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network_costs.py", line 461, in calc_Ctot_cs_district
    Capex_a_pump, Opex_fixed_pump, Opex_var_pump = calc_Ctot_network_pump(network_info)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network_costs.py", line 97, in calc_Ctot_network_pump
    deltaP_kW = pd.read_csv(network_info.locator.get_ploss('', network_type))
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File c:\users\darthoma\appdata\local\temp\2019-13-05-16-59-53-cooling-case-workflow\reference-case-cooling\baseline\outputs\data\optimization\network\layout\DC__P_DeltaP_kW.csv does not exist
```

**Comment by daren-thomas** [comment]
@shanshanhsieh I'm a bit stuck, as i'd need this to work to have optimization results to continue with the plots. do you have an idea what the problem could be?

**Comment by shanshanhsieh** [comment]
hey @daren-thomas, i found the problem, will send a PR today!

**Comment by shanshanhsieh** [comment]
hi @daren-thomas , i've solved the problems created by the name changes in the input locators.
the workflow now run through optimization. (see branch `i1958`)

and here comes an error that i cannot crack:
(also tried to run the multicriteria script locally, it works fine, only get this error when running via `cooling-case-workflow`)


```
Running multicriteria with scenario = C:\Users\Zhongming\AppData\Local\Temp\2019-22-05-08-14-06-cooling-case-workflow\reference-case-cooling\baseline
Running multicriteria for generation = 2
Traceback (most recent call last):
  File "C:/Users/Zhongming/Documents/Github/CityEnergyAnalyst/cea/tests/cooling_case_workflow.py", line 96, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Zhongming/Documents/Github/CityEnergyAnalyst/cea/tests/cooling_case_workflow.py", line 86, in main
    run(script, **kwargs)
  File "C:/Users/Zhongming/Documents/Github/CityEnergyAnalyst/cea/tests/cooling_case_workflow.py", line 54, in run
    f(config=config, **kwargs)
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\api.py", line 27, in script_runner
    script_module.main(config)
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\analysis\multicriteria\main.py", line 427, in main
    multi_criteria_main(locator, config)
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\analysis\multicriteria\main.py", line 52, in multi_criteria_main
    data_processed = preprocessing_cost_data(locator, data_generation['final_generation'], individual_list[0], generation, data_address, config)
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\analysis\multicriteria\main.py", line 323, in preprocessing_cost_data
    network_features = network_opt.network_opt_main(config, locator)
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\optimization\distribution\network_opt_main.py", line 33, in __init__
    network_names = config.thermal_network.network_names
  File "C:\Users\Zhongming\Documents\Github\CityEnergyAnalyst\cea\config.py", line 236, in __getattr__
    "Parameter not configured to work with this script: {%s}" % self.parameters[cid].fqname)
AttributeError: Parameter not configured to work with this script: {thermal-network:network-names}
```

**Comment by shanshanhsieh** [comment]
hey @daren-thomas , can you help me understand this error? thanks!
![image](https://user-images.githubusercontent.com/16998305/58234969-683bbd00-7d72-11e9-8d1a-ae9e98f1f670.png)

**Comment by daren-thomas** [comment]
Yes, this is fixed in PR #1997 - basically, the installer didn't set up qt properly in your environment. Either re-run the installer (from the releases page) OR (much quicker):

- open the file `C:\Users\YOUR_USER_NAME\Documents\CityEnergyAnalyst\Dependencies\Python\qt.conf`
  - of course, replace with your user name
- edit each path in that file to be similar to this: 

```
[Paths] 
Prefix =C:/Users/YOUR_USER_NAME/Documents/CityEnergyAnalyst/Dependencies/Python/Library 
Binaries =C:/Users/YOUR_USER_NAME/Documents/CityEnergyAnalyst/Dependencies/Python/Library/bin 
Libraries =C:/Users/YOUR_USER_NAME/Documents/CityEnergyAnalyst/Dependencies/Python/Library/lib 
Headers =C:/Users/YOUR_USER_NAME/Documents/CityEnergyAnalyst/Dependencies/Python/Library/include/qt
```

(please note that the slashes need to be _forward_ slashes. not backward slashes)

**Comment by shanshanhsieh** [comment]
first i had an error with the `osmnx` model
and now i have this
![image](https://user-images.githubusercontent.com/16998305/58241668-06824f80-7d80-11e9-8c86-605078c3edb4.png)

**Comment by daren-thomas** [comment]
what's the value of `cooling-case-workflow:last` in your config file?

**Comment by shanshanhsieh** [comment]
oops, that's the problem! it was left blank... my bad
running the entire workflow again, at optimization now... will update you in 1-2 hours!

**Comment by shanshanhsieh** [comment]
```
Running plots with args {'network_type': 'DC', 'generations': 2}
City Energy Analyst version 2.14
Running `cea plots` with the following parameters:
- general:scenario = c:\users\envimet\appdata\local\temp\2019-05-24-11-27-23-cooling-case-workflow\reference-case-cooling\baseline
  (default: C:\reference-case-open\baseline)
- general:weather = c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\databases\weather\Singapore.epw
  (default: c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\databases\weather\Zug.epw)
- plots:buildings = []
  (default: [])
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
- plots:building = B001
Traceback (most recent call last):
  File "C:\Users\envimet\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 56, in main
    script_module.main(config)
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\cooling_case_workflow.py", line 88, in main
    run(script, **kwargs)
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\cooling_case_workflow.py", line 55, in run
    f(config=config, **kwargs)
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 27, in script_runner
    cea_script.print_script_configuration(config)
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\scripts.py", line 36, in print_script_configuration
    print("  (default: %s)" % default_config.get(parameter.fqname))
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\config.py", line 178, in get
    return self.get_parameter(fqname).get()
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\config.py", line 328, in get
    return self.decode(encoded_value)
  File "c:\users\envimet\documents\cityenergyanalyst\cityenergyanalyst\cea\config.py", line 623, in decode
    return self._choices[0]
IndexError: list index out of range
```

**Comment by daren-thomas** [comment]
```
thermal network plots successfully saved in plots folder of scenario:  c:\users\darthoma\appdata\local\temp\2019-05-22-17-00-04-cooling-case-workflow\reference-case-cooling\baseline
done - time elapsed: 73.2f seconds
--------------------------------------------------------------------------------
Execution time: 73.44s
Running plots-optimization with args {'generation': 2, 'network_type': 'DC'}
City Energy Analyst version 2.14
Running `cea plots-optimization` with the following parameters:
- general:scenario = c:\users\darthoma\appdata\local\temp\2019-05-22-17-00-04-cooling-case-workflow\reference-case-cooling\baseline
  (default: C:\reference-case-open\baseline)
- plots-optimization:generation = 2
  (default: 3)
- plots-optimization:network-type = DC
  (default: DC)
- plots-optimization:multicriteria = True
  (default: True)
- plots-optimization:categories = ['pareto_curve', 'system_sizes', 'costs_analysis']
  (default: ['pareto_curve', 'system_sizes', 'costs_analysis'])
- general:detailed-electricity-pricing = False
  (default: False)
Running dashboard with scenario = c:\users\darthoma\appdata\local\temp\2019-05-22-17-00-04-cooling-case-workflow\reference-case-cooling\baseline
Running dashboard with the next generation = 2
--------------------------------------------------------------------------------
Execution time: 7.23s
done.
Execution time: 88.92s
```

runs through on my machine. hm...
