### ISSUE TITLE
Error when running Data helper:  BUG: "INDUSTRY" vs "INDUSTRIAL" in zone-helper

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2012]
For this case study I am not being able to run the Data Helper and there is no clear message about what could be the error when running the code in PyCharm.

Case study file can be found here (expires in one week): https://we.tl/t-nsYDnHEBPt

**Comment by gabriel-happle** [comment]
@lguilhermers I took a look at this.
It seems your occupancy.dbf has the type "INDUSTRY" and "INDUSTRIAL".
The bug is caused by the zone-helper script in the function `calculate_occupancy_file`.
I'm therefore renaming this issue and assign labels.

**Comment by reyery** [comment]
@JIMENOFONSECA based on `COLUMNS_ZONE_OCCUPANCY` only the column `INDUSTRIAL` exists not `INDUSTRY` found in `zone_helper`. So I am going to assume that `INDUSTRIAL` is the correct/intended column name and proceed with the fix.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/edf54922c74a0803c03de7dcd3068915257dea61/cea/datamanagement/databases_verification.py#L12-L13

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/edf54922c74a0803c03de7dcd3068915257dea61/cea/datamanagement/zone_helper.py#L173-L178

**Comment by daren-thomas** [comment]
this seems to work with your PR!

**Comment by lguilhermers** [comment]
> this seems to work with your PR!

I managed to run the data helper with the fix, but the running the demand still shows an error:
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\xlrd\book.py", line 476, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
xlrd.biffh.XLRDError: No sheet named <u'INDUSTRY'>

Process finished with exit code 1

**Comment by reyery** [comment]
@lguilhermers hmmm.. `INDUSTRY` should not be appearing anymore. Does your new `occupancy.dbf` file still have the `INDUSTRY` column at the end?

Could you provide the full stack trace of the error or the `solar-radiation` files? Because I cannot run and recreate the problem without running daysim which is going to take a very long time to run on my laptop.

**Comment by lguilhermers** [comment]
I think I know what happened. The Industry was still in the dbf for one of the buildings, even though I couldn't see it anymore in the CEA. I think for new models it should be fine
![image](https://user-images.githubusercontent.com/50981039/58542744-b2201980-8230-11e9-938b-f99c4ae1a406.png)
Now I am getting a new error when I run the demand:
C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe C:/Users/luis.santos/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/demand/demand_main.py
Running demand calculation for scenario C:\CEA\LCZ_preliminary\LCZ4
Running demand calculation with weather file c:\users\luis.santos\documents\github\cityenergyanalyst\cea\databases\weather\Singapore.epw
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation with stochastic occupancy=False
read input files
Traceback (most recent call last):
  File "C:/Users/luis.santos/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/demand/demand_main.py", line 213, in <module>
    main(cea.config.Configuration())
  File "C:/Users/luis.santos/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/demand/demand_main.py", line 200, in main
    demand_calculation(locator=locator, config=config)
  File "C:/Users/luis.santos/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/demand/demand_main.py", line 92, in demand_calculation
    override_variables)
  File "C:/Users/luis.santos/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/demand/demand_main.py", line 134, in properties_and_schedule
    building_properties = BuildingProperties(locator, override_variables)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\building_properties.py", line 57, in __init__
    prop_occupancy_df = dbf_to_dataframe(locator.get_building_occupancy()).set_index('Name')
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 3909, in set_index
    level = frame[col]._values
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Name'

Process finished with exit code 1

**Comment by lguilhermers** [comment]
Model file is here: https://we.tl/t-GboICJ9FUj

**Comment by reyery** [comment]
@lguilhermers Seems like your `occupancy.dbf` has been altered and the `Name` column is missing. You could try running `zone_helper.py` again to recreate the file or manually add the `Name` column back again (but I suggest the former). Should not have any problems after that as I was able to run it on my side.

**Comment by reyery** [comment]
@lguilhermers just want to check with you if this issue has been resolved?

**Comment by lguilhermers** [comment]
@reyery currently I am unable to check on that due to another error that Darren is checking (https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2039#issuecomment-498607456). 
I no longer have the old files to test, so I can do once I am able to test new projects again.
Thanks!
