### ISSUE TITLE
Demand tool not working when occupancy fraction is modified

### ISSUE THREAD

**Issue by Khayatian** [architecture-building-systems/CityEnergyAnalyst#2046]
When the fraction of occupancy type is modified, the demand tool will not run.

To replicate:
(1) run the open reference case scenario
(2) in project management, create a copy of the scenario
(3) in the new scenario go to inputs/occupancy
(4) modify building 3 in the following way:
    a) change the fraction of occupancy for industrial from 0.5 to 0.0
    b) change the fraction of occupancy for library from 0.0 to 0.5
(5) save and exit
(6) run demand

**Comment by gabriel-happle** [comment]
@Khayatian this might be related to PR #2034. I suggest to try this again after #2034 is merged.

**Comment by martin-mosteiro** [comment]
@Khayatian #2034 has been merged, you can try this again now.

**Comment by Khayatian** [comment]
@gabriel-happle @martin-mosteiro 
The issue is not entirely solved. There is a new error pointing to the Temperature range. Please see the following:

Running demand calculation for all buildings in the zone
Using 7 CPU's
Building No. 1 completed out of 9
Building No. 2 completed out of 9
Building No. 3 completed out of 9
Process Process-6:
Traceback (most recent call last):
  File "D:\Users\Fazel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "D:\Users\Fazel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 200, in main
    demand_calculation(locator=locator, config=config)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 106, in demand_calculation
    format_output, config, write_detailed_output, debug)
  File "d:\users\fazel\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 177, in calc_demand_multiprocessing
    job.get(240)
  File "D:\Users\Fazel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
Exception: Temperature in RC-Model of building B06 out of bounds! First occured at timestep = 7386. The results were Tint = 50.208401122, theta_c = 49.857625685, theta_m = 49.7244460162, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 0.9 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0.

**Comment by Khayatian** [comment]
@gabriel-happle @martin-mosteiro 
**correction**: I believe this (new) error is not related to the occupancy ratio. Once I re-run the solar radiation module, (daysim finishes successfully), yet when running the demand module afterwards, it returns an error pointing to the temperature range (Building #3).
to replicate:
(1) create a copy of baseline scenario,
(2) run solar potential (daysim) module
(3) run demand module

**Comment by Khayatian** [comment]
The issue is resolved.
