### ISSUE TITLE
Supply System plots don't work (KeyError: population_fitness)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2081]
Steps to reproduce and result: (based on output of cooling-case-workflow)

```
C:\Users\darthoma\Documents\CityEnergyAnalyst
λ cea plots-supply-system --categories system_sizes
City Energy Analyst version 2.16
Running `cea plots-supply-system` with the following parameters:
- general:scenario = C:\reference-case-cooling\baseline
  (default: C:\reference-case-open\baseline)
- plots-supply-system:generation = 2
  (default: 3)
- plots-supply-system:individual = ind1
  (default: ind1)
- plots-supply-system:network-type = DC
  (default: DC)
- plots-supply-system:categories = ['system_sizes']
  (default: ['system_sizes', 'costs_analysis', 'supply_mix', 'imports_exports', 'thermal_dispatch_curves', 'electrical_dispatch_curves'])
Running dashboard with scenario = C:\reference-case-cooling\baseline
Running dashboard with the next generation = 2
Running dashboard with the next individual = ind1
optimization-detailed
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 61, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\main.py", line 944, in main
    plots_main(locator, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\main.py", line 56, in plots_main
    plots = Plots(locator, individual, generation, individual_pointer, generation_pointer, config, type_of_network, category)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\main.py", line 224, in __init__
    self.data_processed = preprocessing_generations_data(self.locator, self.generation)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\main.py", line 616, in preprocessing_generations_data
    data['population_fitness']]  # convert to millions
KeyError: 'population_fitness'
```

I have done some digging and it seems the checkpoint file is a json dictionary and some of the keys were renamed:

- `population_fitness` -> `tested_population_fitness`
- `population` -> `tested_population`

BUT: I did try to rename these in the plots function (`cea.plots.supply_system.main.preprocessing_generations_data`) - and then I ran into the dict not having a `capacities` column.

So. I think the supply system plots are just broken for the time being.

**Comment by daren-thomas** [comment]
@shanshanhsieh would you mind looking into this for me?

**Comment by JIMENOFONSECA** [comment]
These plots were updated during #2120
