### ISSUE TITLE
KeyError: 'E_ACH_W' when running plots-scenario-comparisons

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2092]
I'm about to start working on #1986 (add plots-scenario-comparisons to dashboard) and tried to run the existing plotting functions first. I expected them to run through. They used to work, after all!

Instead, I got this:

```
cea plots-scenario-comparisons --categories demand
City Energy Analyst version 2.17a0
Running `cea plots-scenario-comparisons` with the following parameters:
- plots-scenario-comparisons:project = C:\reference-case-cooling
  (default: C:\reference-case-open)
- plots-scenario-comparisons:base-scenario = baseline
  (default: C:\reference-case-open\baseline)
- plots-scenario-comparisons:scenarios = ['baseline/1/ind1', 'baseline/1/ind2']
  (default: ['C:\\reference-case-open\\baseline/1/ind2'])
- plots-scenario-comparisons:categories = ['demand']
  (default: ['demand', 'supply_mix', 'costs_analysis', 'life_cycle_analysis', 'land_use'])
- plots-scenario-comparisons:network-type = DC
  (default: DC)
['baseline/1/ind1', 'baseline/1/ind2']
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 61, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\comparisons\main.py", line 484, in main
    plots_main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\comparisons\main.py", line 76, in plots_main
    generation_pointers, individual_pointers, network_type, config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\comparisons\main.py", line 197, in __init__
    self.data_processed_supply = self.preprocessing_supply_scenarios()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\comparisons\main.py", line 242, in preprocessing_supply_scenarios
    locator, self.network_type)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\energy_mix_based_on_technologies_script.py", line 48, in energy_mix_based_on_technologies_script
    E_ACH_total_W = data_electricity['E_ACH_W'].sum()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'E_ACH_W'
```

**Comment by reyery** [comment]
this plots are not used anymore @JIMENOFONSECA is creating new ones
