### ISSUE TITLE
Error when trying to change number of floors and height above ground using data helper

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2107]
Hi,

With data helper I am able to change the zone occupancy, but the number of floors/ height above ground give me an error:

City Energy Analyst version 2.17a0
Running `cea zone-helper` with the following parameters:
- general:scenario = C:\CEA\LCZ8_JooKoon
  (default: C:\reference-case-open\baseline)
- zone-helper:height-ag = 9.0
  (default: None)
- zone-helper:floors-ag = 3
  (default: None)
- zone-helper:year-construction = None
  (default: None)
- zone-helper:height-bg = 3.0
  (default: 3.0)
- zone-helper:floors-bg = 1
  (default: 1)
- zone-helper:occupancy-type = INDUSTRIAL
  (default: Get it from open street maps)
Process Process-5:
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 248, in main
    zone_helper(locator, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 126, in zone_helper
    poly, zone_output_path)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 233, in polygon_to_zone
    buildings_floors_below_ground, key="B")
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 97, in clean_attributes
    "REFERENCE"]]
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 455, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['REFERENCE'] not in index"

**Comment by reyery** [comment]
@daren-thomas this issue seems to be the same as #2091. It seems to be happening when editing floors/height above ground parameter. I'm looking into it now

**Comment by reyery** [comment]
Ahhh the `REFERENCE` column is only added if `height-ag` and `floors-ag` parameters is not set... How could I have missed that.

**Comment by daren-thomas** [comment]
@reyery this is fixed now, right? With #2108?

**Comment by reyery** [comment]
@daren-thomas yeah. Gonna close this issue now.
