### ISSUE TITLE
cooling-case-workflow crashes during multi-criteria-analysis

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2135]
The `cooling-case-workflow` has stopped working. The issue seems to be in the `multi-criteria-analysis`. It looks like a variable (`df_current_individual`) was renamed or something.

```
Running multicriteria with scenario = c:\users\assist~1\appdata\local\temp\2019-07-01-16-32-46-cooling-case-workflow\reference-case-cooling\baseline
Running multicriteria for generation = 2
compiled data of all individuals in this generation:  2
Traceback (most recent call last):
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 61, in main
    script_module.main(config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\cooling_case_workflow.py", line 88, in main
    run(script, **kwargs)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\cooling_case_workflow.py", line 55, in run
    f(config=config, **kwargs)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\analysis\multicriteria\main.py", line 587, in main
    multi_criteria_main(locator, config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\analysis\multicriteria\main.py", line 61, in multi_criteria_main
    config), ignore_index=True)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\analysis\multicriteria\main.py", line 366, in preprocessing_cost_data_DC
    if df_current_individual['Data Centre'][0] == 1:
NameError: global name 'df_current_individual' is not defined
```

**Comment by daren-thomas** [comment]
@JIMENOFONSECA is this something you could handle?

**Comment by JIMENOFONSECA** [comment]
yesp I am on it, expect something by the end of the week (ps, I have been working for 3 days straight on this) :S

**Comment by daren-thomas** [comment]
Just tried this again. The simulation stops with lake-potential. I'm creating a PR to update the workflow.

```
Traceback (most recent call last):
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 64, in main
    script_module.main(config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\workflow.py", line 45, in main
    do_script_step(config, step)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\workflow.py", line 105, in do_script_step
    script = cea.scripts.by_name(step["script"])
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\scripts.py", line 111, in by_name
    raise cea.ScriptNotFoundException('Invalid script name: %s' % script_name)
cea.ScriptNotFoundException: Invalid script name: lake-potential
```

**Comment by daren-thomas** [comment]
This issue is currently blocked because of #2256 - I can't get passed `decentralized`. Also, blocked by the `thermal-network-optimization` needing some refactoring.

I guess the cooling-case workflow is working in the sense that it _is_ showing us where the problems are.

I am creating a PR that fixes some stuff. This PR should be merged, even though it doesn't fix this issue per se - It fixes other stuff.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'm getting the following error after the `optimization-cooling` branches was merged to master:

```
Workflow step: script=optimization
Running optimization with args {'random_seed': 100, 'scenario': 'c:\\Users\\darthoma\\Documents\\CityEnergyAnalyst\\projects\\reference-case-cooling\\baseline', 'mutation_prob': 0.1, 'district_cooling_network': True, 'crossover_prob': 0.9, 'population_size': 5, 'detailed_electricity_pricing': False, 'number_of_generations': 2, 'multiprocessing': True, 'district_heating_network': False}
City Energy Analyst version 2.23
Running `cea optimization` with the following parameters:
- general:scenario = c:\Users\darthoma\Documents\CityEnergyAnalyst\projects\reference-case-cooling\baseline
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- optimization:district-heating-network = False
  (default: True)
- optimization:district-cooling-network = True
  (default: False)
- optimization:detailed-electricity-pricing = False
  (default: False)
- optimization:population-size = 5
  (default: None)
- optimization:number-of-generations = 2
  (default: 100)
- optimization:random-seed = 100
  (default: 100)
- optimization:crossover-prob = 0.9
  (default: 0.9)
- optimization:mutation-prob = 0.1
  (default: 0.1)
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
PRE-PROCESSING
PRE-PROCESSING 1/2: weather properties
PRE-PROCESSING 2/2: thermal networks
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 64, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 45, in main
    do_script_step(config, step)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 109, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 29, in run
    f(config=config, **kwargs)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, config=config)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 83, in moo_optimization
    weather_file, district_heating_network, district_cooling_network)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\preprocessing\preprocessing_main.py", line 72, in preproccessing
    substation.substation_main_cooling(locator, total_demand, buildings_cooling_demand, DCN_barcode=DCN_barcode)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\technologies\substation.py", line 139, in substation_main_cooling
    locator, DCN_barcode)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\technologies\substation.py", line 306, in substation_model_cooling
    calc_substation_cooling(Qcre_sys_W, thi, tho, tci, ch, ch_0, Qnom_W, thi_0, tci_0, tho_0)
  File "c:\users\darthoma\documents\cityenergyanalyst\cityenergyanalyst\cea\technologies\substation.py", line 591, in calc_substation_cooling
    tco, cc = np.vectorize(calc_HEX_cooling)(Q, UA_cooling, thi, tho, tci, ch)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2042, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2002, in _get_ufunc_and_otypes
    outputs = func(*inputs)
ZeroDivisionError: division by zero
```

So... we still can't get as far as multi-criteria-analysis. Any ideas?

**Comment by daren-thomas** [comment]
Current status: Breaks on demand

```
Exception: Temperature in RC-Model of building B007 out of bounds! First occured at timestep = 3220. The results were Tint = -67.1300539189, theta_c = -7.98175527126, theta_m = 23.3852261124, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 0.45 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0.
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas as discussed this now works. the error was in the inputs used to run this
