### ISSUE TITLE
ImportError with CEA Dashboard

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2240]
I'm getting the following error with master (as of 2019-08-12) when running `cea dashboard`

```
C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst (master -> origin)
λ python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 10 2018, 21:57:18) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cea.api
cea.api: loading cea_script: <cea compile>
[...]
cea.api: loading cea_script: <cea data-helper>
>>> cea.api.dashboard()
>>> cea.api.dashboard()
City Energy Analyst version 2.19
Running `cea dashboard` with the following parameters:
- general:debug = False
  (default: False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "cea\interfaces\dashboard\dashboard.py", line 116, in main
    import plots.routes
  File "cea\interfaces\dashboard\plots\routes.py", line 20, in <module>
    for c in cea.plots.categories.list_categories()}
  File "cea\interfaces\dashboard\plots\routes.py", line 20, in <dictcomp>
    for c in cea.plots.categories.list_categories()}
  File "cea\plots\categories.py", line 97, in plots
    module = importlib.import_module(modname)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\comparisons\main.py", line 22, in <module>
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\old\main.py", line 23, in <module>
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\multicriteria\optimization_post_processing\locating_individuals_in_generation_script.py", line 22, in <module>
ImportError: cannot import name initialize_column_names_of_individual
```

**Comment by daren-thomas** [comment]
nevermind... i still had old .pyc files lying around.
