### ISSUE TITLE
run_thermal_network - RuntimeError: no arguments in initialization list

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2242]
The `cea test` script fails with the error below in master:

```
The gelman-rubin statistic is larger than 1.05 for some parameters. This indicates slight problems during sampling.
The number of effective samples is smaller than 10% for some parameters.
.  run_emissions_operation:open
.  run_thermal_network
########################################
TaskError - taskid:run_thermal_network
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\dodo.py", line 368, in run_thermal_network
    tnm.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network.py", line 3562, in main
    thermal_network_main(locator, network_type, network_name, file_type, set_diameter, config, substation_systems, temperature_control)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network.py", line 476, in thermal_network_main
    use_multiprocessing=config.multiprocessing)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network.py", line 1735, in calc_max_edge_flowrate
    pipe_properties_df = assign_pipes_to_edges(thermal_network, set_diameter)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\thermal_network\thermal_network.py", line 1174, in assign_pipes_to_edges
    lat, lon = get_lat_lon_projected_shapefile(network_edges)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\utilities\standardize_coordinates.py", line 61, in get_lat_lon_projected_shapefile
    data = data.to_crs(get_geographic_coordinate_system())
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 443, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geoseries.py", line 304, in to_crs
    proj_in = pyproj.Proj(self.crs, preserve_units=True)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pyproj\__init__.py", line 358, in __new__
    return _proj.Proj.__new__(self, projstring)
  File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1170)
RuntimeError: no arguments in initialization list
```

**Comment by daren-thomas** [comment]
(working on this in the `release-2.20` thread)

**Comment by daren-thomas** [comment]
works in master (2.20.3)
