### ISSUE TITLE
KeyError: network_type when running thermal-network

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2243]
The configuration for the script `thermal-network` might be broken. Check the following output:

```
λ cea thermal-network
City Energy Analyst version 2.20
Running `cea thermal-network` with the following parameters:
- general:scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\CASE-EXECUTIVE-COURSE\baseline
  (default: {general:project}\{general:scenario-name})
- general:weather = c:\users\darthoma\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw
  (default: c:\users\darthoma\documents\github\cityenergyanalyst\cea\databases\weather\Zug.epw)
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- thermal-network:network-type = DH
  (default: DH)
- thermal-network:network-names = []
  (default: [])
- thermal-network:file-type = shp
  (default: shp)
- thermal-network:set-diameter = True
  (default: True)
- thermal-network:load-max-edge-flowrate-from-previous-run = False
  (default: False)
- thermal-network:start-t = 0
  (default: 0)
- thermal-network:stop-t = 8760
  (default: 8760)
- thermal-network:use-representative-week-per-month = False
  (default: False)
- thermal-network:minimum-mass-flow-iteration-limit = 30
  (default: 30)
- thermal-network:minimum-edge-mass-flow = 0.1
  (default: 0.1)
- thermal-network:diameter-iteration-limit = 10
  (default: 10)
- thermal-network:substation-cooling-systems = ['ahu', 'aru', 'scu']
  (default: ['ahu', 'aru', 'scu'])
- thermal-network:substation-heating-systems = ['ahu', 'aru', 'shu', 'ww']
  (default: ['ahu', 'aru', 'shu', 'ww'])
- thermal-network:temperature-control = VT
  (default: VT)
- thermal-network:plant-supply-temperature = 80.0
  (default: 80.0)
- thermal-network-optimization:use-representative-week-per-month = True
  (default: False)
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 58, in main
    if list(cea_script.missing_input_files(config)):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\scripts.py", line 69, in missing_input_files
    path = method(*self._lookup_args(config, locator, args))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\scripts.py", line 81, in _lookup_args
    result.append(config.get(arg))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\config.py", line 178, in get
    return self.get_parameter(fqname).get()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\config.py", line 183, in get_parameter
    return self.sections[section].parameters[parameter]
KeyError: 'network_type'
```

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is that the case?

**Comment by shanshanhsieh** [comment]
the sript is working well in CEA v2.24
