### ISSUE TITLE
Thermal Network Optimization doesn't run through (TypeError: __init__() takes exactly 4 arguments (3 given))

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2274]
Steps to reproduce:

- reference-case-cooling (doesn't work for heating case yet)
- run from PyCharm (doesn't work for cli/dashboard yet)
- start... wait... it calculates for quite a while. then:

```
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 866, in <module>
    main(cea.config.Configuration())
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 861, in main
    thermal_network_optimization(config, gv, locator)
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 96, in thermal_network_optimization
    sortedPop = network_cost_calculation(newMutadedGen, network_info, config)
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 160, in network_cost_calculation
    capex_total, opex_total, total_cost, cost_storage_df = objective_function(network_info)
  File "C:/Users/darthoma/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 333, in objective_function
    Capex_total, Opex_total, Costs_total, cost_storage = network_costs.calc_Ctot_cs_district(network_info)
  File "C:\Users\darthoma\Documents\GitHub\CityEnergyAnalyst\cea\technologies\thermal_network\thermal_network_costs.py", line 451, in calc_Ctot_cs_district
    network_info.network_features = NetworkOptimizationFeatures(network_info.config, network_info.locator)
TypeError: __init__() takes exactly 4 arguments (3 given)
```

**Comment by daren-thomas** [comment]
@shanshanhsieh is this fixed? I think it is, right?
