### ISSUE TITLE
District heating system workflow fails at decentralized tool

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2291]
Steps to reproduce:

-  `cea workflow --workflow district-heating-system` 

Expected the workflow to run through, but only gets as far as  `decentralized`:

>  AttributeError: 'DataFrame' object has no attribute 'Tcref_sup_C'

Full stack trace:

```
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 64, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 45, in main
    do_script_step(config, step)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 112, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 29, in run
    f(config=config, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\decentralized_building_main.py", line 57, in main
    config=config, prices=prices, lca=lca)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\decentralized_building_main.py", line 44, in disconnected_building_main
    config, prices, lca)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\decentralized_buildings_cooling.py", line 65, in disconnected_buildings_cooling_main
    cooling_configuration=['scu'])
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\decentralized_buildings_cooling.py", line 585, in calc_combined_cooling_loads
    substation.substation_main_cooling(locator, total_demand, buildings_name_with_cooling, cooling_configuration)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\substation.py", line 157, in substation_main_cooling
    locator, DCN_barcode)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\substation.py", line 297, in substation_model_cooling
    tho = building.Tcref_sup_C + 273  # in K
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'Tcref_sup_C'
```

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what is the status here? I think it's fixed, right?

**Comment by JIMENOFONSECA** [comment]
Yep
On 18 Sep 2019, 22:23 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what is the status here? I think it's fixed, right?
