### ISSUE TITLE
Error running emissions script

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2296]
Steps to reproduce:

- open scenario in dashboard
- choose "Tools / Analysis / Life Cycle Analysis (zone)"
- click "Run"

Expected script to complete successfully, instead got this error:

```
City Energy Analyst version 2.21
Running `cea emissions` with the following parameters:
- general:scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\CASE-EXECUTIVE-COURSE\baseline
  (default: {general:project}\{general:scenario-name})
- emissions:year-to-calculate = 2020
  (default: 2020)
Running emissions with scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\CASE-EXECUTIVE-COURSE\baseline
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\lca\main.py", line 45, in main
    emissions_main(locator=locator, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\lca\main.py", line 34, in emissions_main
    lca_operation(locator, config)
TypeError: lca_operation() takes exactly 1 argument (2 given)
done!
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I believe this is fixed?
