### ISSUE TITLE
Unable to handle column names with different case due to case sensitivity of pandas column names

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2330]
Hi all,
I was trying to change the parameter "Es" in architecture.dbf and this caused an error in the simulation and now when trying to opening this file. Not sure what caused, but changing it back also didn't help.

I am attaching a link to the edited file here (I can't attach this format here): https://we.tl/t-UPxDy7Mq8B

I am also copying the log error below:
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\inputs\routes.py", line 108, in route_get_building_properties
    store['tables'][db] = json.loads(table_df.set_index('Name').to_json(orient='index'))
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 3909, in set_index
    level = frame[col]._values
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Name'

**Comment by reyery** [comment]
hey @lguilhermers, because pandas column names are case-sensitive and the file that you have given me has all the column names in uppercase, it was not able to find the column `Name` even though it exists in your file as `NAME`. Easiest way to solve it would be to just rename your columns to the original case. We will look into how we can handle this type of errors.

**Comment by lguilhermers** [comment]
Got it! But not sure what caused the cases to change, as I didn't to this change manually...
