### ISSUE TITLE
Geometry extraction from open streetmap fails in San Francisco and Los Angeles

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2345]
Trying to extract geometry in Los Angeles and San Francisco fails with below error message.
Funny enough, extracting geometry in other places in California (e.g. Alturas, California) seems to work.

```
Traceback (most recent call last): File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request rv = self.handle_user_exception(e) File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router return original_handler(e) File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router return original_handler(e) File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception reraise(exc_type, exc_value, tb) File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\landing\routes.py", line 201, in route_create_scenario_save cea.api.district_helper(cea_config) File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__ self._runner.__call__(*args, **kwargs) File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner script_module.main(config) File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\district_geometry_helper.py", line 247, in main geometry_extractor_osm(locator, config) File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\district_geometry_helper.py", line 210, in geometry_extractor_osm zone = zone.to_crs(get_projected_coordinate_system(float(lat), float(lon))) File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\standardize_coordinates.py", line 55, in get_projected_coordinate_system utm_data = utm.from_latlon(lat, lon) File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\utm\conversion.py", line 155, in from_latlon raise OutOfRangeError('latitude out of range (must be between 80 deg S and 84 deg N)') OutOfRangeError: latitude out of range (must be between 80 deg S and 84 deg N) 
```

e.g. Alturas, California
![image](https://user-images.githubusercontent.com/17002288/65702354-235ac680-e083-11e9-9107-9b2ea3591466.png)

**Comment by JIMENOFONSECA** [comment]
So this is a problem of an external library. It seems the lat and lon of the site are outside of the bounds (the bounds are in this picture).

Maybe we could check if the file in OSM comes with another latitute and longitude readings in SanFrancisco?

<img width="771" alt="Screen Shot 2019-09-27 at 11 25 15 AM" src="https://user-images.githubusercontent.com/8973186/65739893-826b1a80-e119-11e9-9448-491f1a8db01f.png">

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle fixed in master, it should work now
