### ISSUE TITLE
Solar radiation: Standard construction error

### ISSUE THREAD

**Issue by RicardoGomesIST** [architecture-building-systems/CityEnergyAnalyst#2367]
Hi,

When I ran the Solar Radiation tab, it does not run and present "RuntimeError: Standard_ConstructionError

 "
The construction look ok and are the same as used in reference examples.  Is the coordinate system again? I have zone, district and terrain files with the sampe projection 
CRS EPSG:32229 - WGS 72 / UTM zone 29N - Projected

(...)
Generating geometry for building B41090
burning building  B41090
Generating geometry for building B41144
burning building  B41144
Generating geometry for building B41193
burning building  B41193
Generating geometry for building B41312
burning building  B41312
Process Process-1:
Traceback (most recent call last):
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\radiation_main.py", line 195, in main
    config)
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 402, in geometry_main
    height_col='height_ag', nfloor_col="floors_ag")
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 187, in building2d23d
    building_solid = calc_solid(face_footprint, range_floors, flr2flr_height, config)
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\geometry_generator.py", line 321, in calc_solid
    vertical_shell = construct.make_loft(moved_face_list)
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\py4design\py3dmodel\construct.py", line 1175, in make_loft
    loft = Construct.make_loft(wire_list, ruled = rule_face, tolerance = tolerance )
  File "D:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\py4design\py3dmodel\OCCUtils\Construct.py", line 422, in make_loft
    sections.Build()
RuntimeError: Standard_ConstructionError
[WGS 84 - v4.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3697036/WGS.84.-.v4.zip)

**Comment by JIMENOFONSECA** [comment]
Hi!, I could not open your case study. I see there are problems regarding the inputs. For example the filed NAME should be Name. This happens in the input database of indoor-comfort. 

![image](https://user-images.githubusercontent.com/8973186/66793442-eff7b300-ef2f-11e9-9002-73a3f3e1f5e6.png)

**Comment by RicardoGomesIST** [comment]
Thank you Jimeno!

 



IST, Taguspark, N14.16
