### ISSUE TITLE
OutofRange error

### ISSUE THREAD

**Issue by OmarAdnan** [architecture-building-systems/CityEnergyAnalyst#2394]
I have tried to generate input data for zone in the city of Lisbon and i get this OutOfRangeError.

Traceback (most recent call last):
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\inputs\routes.py", line 94, in route_get_building_properties
    store['crs'][db] = get_projected_coordinate_system(lat, lon)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\utilities\standardize_coordinates.py", line 55, in get_projected_coordinate_system
    utm_data = utm.from_latlon(lat, lon)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\utm\conversion.py", line 155, in from_latlon
    raise OutOfRangeError('latitude out of range (must be between 80 deg S and 84 deg N)')
OutOfRangeError: latitude out of range (must be between 80 deg S and 84 deg N)

**Comment by JIMENOFONSECA** [comment]
Try the new version Omar. we fixed that in the latest release, let us know if this worked.

**Comment by OmarAdnan** [comment]
ok thanks will try it and inform you
