### ISSUE TITLE
Energy Demand calculation failing with KeyError: 'rhum_max_pc'

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2399]
When running `cea test`, the pydoit task `run_demand:open` fails with the following output:

```
TaskError - taskid:run_demand:open
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\tests\dodo.py", line 200, in run_demand
    cea.demand.demand_main.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 158, in main
    demand_calculation(locator=locator, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 129, in demand_calculation
    repeat(debug, n))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\utilities\parallel.py", line 95, in wrapper
    result = map_result.get()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
KeyError: 'rhum_max_pc'
```

I'm guessing there is some step that needs to be added to the tests.

**Comment by daren-thomas** [comment]
Nope. Just checked: Running the data-helper and the schedule-maker does not solve the problem.

**Comment by daren-thomas** [comment]
Running with `multiprocessing=False` yields a more accurate description:

```
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 158, in main
    demand_calculation(locator=locator, config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 129, in demand_calculation
    repeat(debug, n))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\utilities\parallel.py", line 139, in wrapper
    result = func(*instance_args)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\thermal_loads.py", line 112, in calc_thermal_loads
    use_dynamic_infiltration_calculation)  # end-use demand latent and sensible + ventilation
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\thermal_loads.py", line 356, in calc_Qhs_Qcs
    ventilation_air_flows_simple.calc_air_mass_flow_mechanical_ventilation(bpr, tsd, t)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\ventilation_air_flows_simple.py", line 47, in calc_air_mass_flow_mechanical_ventilation
    if control_ventilation_systems.is_mechanical_ventilation_active(bpr, tsd, t) \
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\control_ventilation_systems.py", line 31, in is_mechanical_ventilation_active
    and is_night_flushing_active(bpr, tsd, t):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\control_ventilation_systems.py", line 110, in is_night_flushing_active
    and tsd['rh_ext'][t] < bpr.comfort['rhum_max_pc']:
KeyError: 'rhum_max_pc'
```

**Comment by martin-mosteiro** [comment]
No, someone renamed a variable without changing the name anywhere else (e.g., in the databases).

I'm not sure this was intentional, so I'm creating a PR that solves this issue by reverting to the old naming convention.

**Comment by martin-mosteiro** [comment]
@daren-thomas I just noticed you had already created a PR about this, so I closed mine. In any case, it's probably a good idea to test stuff before merging in the future... 😂
