### ISSUE TITLE
optimization not running in SG

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#2406]
Optimization of Supply system centralized and Supply system decentralized both don't run.
Both scripts try to find 'WOOD' in the LCA database, which doesn't exist in the SG case.

```City Energy Analyst version 2.24
Running `cea optimization` with the following parameters:
- general:scenario = C:\GABRIEL\modified-case-study\new-baseline
  (default: {general:project}\{general:scenario-name})
Traceback (most recent call last):
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 117, in main
    moo_optimization(locator=locator, weather_file=weather_file, config=config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\optimization_main.py", line 66, in moo_optimization
    lca = LcaCalculations(locator)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\lca_calculations.py", line 34, in __init__
    self.DRYBIOMASS_TO_CO2_EQ = resources_lca.loc['WOOD']['CO2']
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1911, in _getitem_axis
    self._validate_key(key, axis)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1798, in _validate_key
    error()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: u'the label [WOOD] is not in the [index]'
```

**Comment by shizhongming** [comment]
Same error for the decentralized case:

```
City Energy Analyst version 2.24
Running `cea decentralized` with the following parameters:
- general:scenario = C:\GABRIEL\modified-case-study\new-baseline
  (default: {general:project}\{general:scenario-name})
- decentralized:detailed-electricity-pricing = False
  (default: False)
Traceback (most recent call last):
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\preprocessing\decentralized_building_main.py", line 52, in main
    lca = LcaCalculations(locator)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\optimization\lca_calculations.py", line 34, in __init__
    self.DRYBIOMASS_TO_CO2_EQ = resources_lca.loc['WOOD']['CO2']
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1911, in _getitem_axis
    self._validate_key(key, axis)
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1798, in _validate_key
    error()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1785, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: u'the label [WOOD] is not in the [index]'

Running decentralized model for buildings with scenario = C:\GABRIEL\modified-case-study\new-baseline
```

**Comment by JIMENOFONSECA** [comment]
@shizhongming you can solve it by adding the 'WOOD' parameter to the Singapore LCA. a PR is much appreciated it.
