### ISSUE TITLE
Unable to run dashboard.py in PyCharm

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2424]
For some reason PyCharm does not like this kind of imports and will not run `dashboard.py`. 

Running it from console seems to work though

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/12a5dec08fcf449eada930a23109730ed9cd184c/cea/interfaces/dashboard/server/__init__.py#L12
```
C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe C:/Users/Admin/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/interfaces/dashboard/dashboard.py
Traceback (most recent call last):
  File "C:/Users/Admin/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/interfaces/dashboard/dashboard.py", line 150, in <module>
    main(cea.config.Configuration())
  File "C:/Users/Admin/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/interfaces/dashboard/dashboard.py", line 125, in main
    from server import blueprint as server_blueprint
  File "C:\Users\Admin\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\interfaces\dashboard\server\__init__.py", line 12, in <module>
    from ..tools.routes import shutdown_worker_processes
ValueError: Attempted relative import beyond toplevel package

Process finished with exit code 1
```

**Comment by daren-thomas** [comment]
I found this while googling the error message: https://stackoverflow.com/questions/30669474/beyond-top-level-package-error-in-relative-import

I think we should just use the full package name (`from cea.interfaces.dashboard.tools.routes import shutdown_worker_processes`)
