### ISSUE TITLE
Solar radiation curve plot not working in GUI

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2453]
this happened today with the newest CEA version.
Same error for monthly solar radiation plot.
Solar radiation per building works fine.

```
Traceback (most recent call last):
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\plots\routes.py", line 255, in route_div
    plot_div = plot.plot_div()
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\base.py", line 160, in plot_div
    return self.cache.lookup_plot_div(self, self._plot_div_producer)
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\cache.py", line 50, in lookup_plot_div
    plot_div = producer()
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\base.py", line 163, in _plot_div_producer
    fig = plotly.graph_objs.Figure(data=self.calc_graph(), layout=self.layout)
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\solar_potential\solar_radiation_curve.py", line 29, in calc_graph
    data_frame = self.input_data_aggregated_kW
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\solar_potential\__init__.py", line 57, in input_data_aggregated_kW
    plot=self, producer=self._calculate_input_data_aggregated_kW)
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\cache.py", line 42, in lookup
    return self.store_cached_value(data_path, plot.parameters, producer)
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\cache.py", line 99, in store_cached_value
    data = producer()
  File "c:\users\gabriel\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\solar_potential\__init__.py", line 98, in _calculate_input_data_aggregated_kW
    input_data_aggregated_kW["T_ext_C"] = weather_data["drybulb_C"].values
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 3119, in __setitem__
    self._set_item(key, value)
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 3194, in _set_item
    value = self._sanitize_column(key, value)
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 3391, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "C:\Users\Gabriel\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\series.py", line 4001, in _sanitize_index
    raise ValueError('Length of values does not match length of ' 'index')
ValueError: Length of values does not match length of index
```

**Comment by martin-mosteiro** [comment]
Strange. Just ran it on my computer and it worked fine.

**Comment by gabriel-happle** [comment]
well... I created a random project in Switzerland and ran until after solar radiation.
Let me know if anyone needs the files.

**Comment by daren-thomas** [comment]
@gabriel-happle can you please try to replicate with newest version? If you can replicate it, please assign to me :)
