### ISSUE TITLE
Fails to run Building Solar radiation tool

### ISSUE THREAD

**Issue by DespaxJulien** [architecture-building-systems/CityEnergyAnalyst#2502]
Hi,

I get an error when running the Building solar radiation tool (see stacktrace below).

I'm on V2.27.

Steps I followed:

- Create a new project + new scenario using `Generate new input files using tools`. I created the Zone + Surroundings + Terrain + Weather in the `Create new scenario` window.
- Run the `Data helper` to create the databases (all 6 of them)
- Run the `Building Solar radiation tool` -> error

I got the same error when trying different weather files.

Thanks for your help!
Best,
Julien

Stacktrace:
```
City Energy Analyst version 2.27.0
Running `cea radiation` with the following parameters:
- general:scenario = I:\Logiciels\City Energy Analyst\ZACOL\ZACOL\block
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = True
  (default: False)
- radiation:buildings = []
  (default: [])
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Daysim\bin)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
verifying geometry files
I:\Logiciels\City Energy Analyst\ZACOL\ZACOL\block\inputs\building-geometry\zone.shp
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
getting geometry materials
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 7 CPU's
Sending the scene: geometry and materials to daysim
Traceback (most recent call last):
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\radiation_main.py", line 238, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, settings)
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\radiation_main.py", line 183, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, building_dict, locator, settings, max_global)
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\resources\radiation_daysim\daysim_main.py", line 194, in isolation_daysim
    rad.execute_epw2wea(locator.get_weather_file(), ground_reflectance=settings.albedo)
  File "C:\Users\jdespax\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\py4design\py2radiance\__init__.py", line 890, in execute_epw2wea
    results = open(weaweatherfile, "r")
IOError: [Errno 2] No such file or directory: 'c:\\users\\jdespax\\appdata\\local\\temp\\temp0\\wea\\weather_60min.wea'

	radiation_main: rad.base_file_path: c:\users\jdespax\appdata\local\temp\default_materials.rad
	radiation_main: rad.data_folder_path: c:\users\jdespax\appdata\local\temp
	radiation_main: rad.command_file: c:\users\jdespax\appdata\local\temp\command.txt
	radiation_main: rad.rad_file_path: c:\users\jdespax\appdata\local\temp\geometry.rad
isolation_daysim: daysim_dir=c:\users\jdespax\appdata\local\temp\temp0
	isolation_daysim: rad.hea_file: c:\users\jdespax\appdata\local\temp\temp0\temp0.hea
	isolation_daysim: rad.hea_filename: None
	isolation_daysim: rad.daysimdir_ies: c:\users\jdespax\appdata\local\temp\temp0\ies
	isolation_daysim: rad.daysimdir_pts: c:\users\jdespax\appdata\local\temp\temp0\pts
	isolation_daysim: rad.daysimdir_rad: c:\users\jdespax\appdata\local\temp\temp0\rad
	isolation_daysim: rad.daysimdir_res: c:\users\jdespax\appdata\local\temp\temp0\res
	isolation_daysim: rad.daysimdir_tmp: c:\users\jdespax\appdata\local\temp\temp0\tmp
	isolation_daysim: rad.daysimdir_wea: c:\users\jdespax\appdata\local\temp\temp0\wea
Calculating and sending sensor points
	isolation_daysim: rad.sensor_file_path: c:\users\jdespax\appdata\local\temp\points_0.pts
Starting Daysim simulation starts for buildings [u'B1000', u'B1001', u'B1002', u'B1003', u'B1004']
Total number of sensors:  594
Transforming weather files to daysim format
```

**Comment by daren-thomas** [comment]
@DespaxJulien it looks like it should all work, except that the Radiance / Daysim tools didn't run.

Would you mind trying the following: Rename the folder `I:\Logiciels\City Energy Analyst` to `I:\Logiciels\CityEnergyAnalyst` (remove the spaces) and try again - it could be a problem with how the py2radiance module calls those binaries...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this might be again the same problem as in #2447

**Comment by JIMENOFONSECA** [comment]
@DespaxJulien we just merged the work. either you need to update from master or reinstall CEA development version. let us know if this did not work.

**Comment by DespaxJulien** [comment]
@daren-thomas @JIMENOFONSECA, I deleted the spaces in the folder path and it solved the problem: I'm able to run the radiation tool.

Thank you very much for your help
