### ISSUE TITLE
cea-toolbox

### ISSUE THREAD

**Issue by Lh0r** [architecture-building-systems/CityEnergyAnalyst#2518]
hi i really don't know where is the problem. can you help me?

Traceback (most recent call last):
  File "E:\CITY\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 10, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
NameError: name 'load_entry_point' is not defined

**Comment by daren-thomas** [comment]
Hi @Lh0r, I'm really not sure I have all the information necessesary to help you. Would you mind answering the following questions please:

- how did you install? what version? what choices did you make during the installation? (you seem to have a non-standard installation path)
- what exactly are you trying to do? how did you get to this error? (did you click on "CEA GUI"?)
- is that the _whole_ message?

**Comment by Lh0r** [comment]
Hi thanks for your help!!
I try to install cea on grasshopper and this is the whole message of error:

λ cea install-grasshopper
City Energy Analyst version 2.27.0
Running `cea install-grasshopper` with the following parameters:
- general:debug = False
  (default: False)
Traceback (most recent call last):
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea.exe\__main__.py", line 7, in <module>
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\grasshopper\install_grasshopper.py", line 43, in main
    copy_cea_ghuser(r'%APPDATA%\Grasshopper\UserObjects')
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\grasshopper\install_grasshopper.py", line 96, in copy_cea_ghuser
    shutil.copy(src_file, dst_folder)
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\shutil.py", line 133, in copy
    copyfile(src, dst)
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\gglho\\Documents\\CityEnergyAnalyst\\Dependencies\\Python\\lib\\site-packages\\cea\\interfaces\\grasshopper\\CEA.ghuser'

**Comment by Lh0r** [comment]
And this for toolbox: 

λ cea toolbox
Traceback (most recent call last):
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea.exe\__main__.py", line 7, in <module>
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\cli\cli.py", line 51, in main
    cea_script = cea.scripts.by_name(script_name)
  File "C:\Users\gglho\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\scripts.py", line 112, in by_name
    raise cea.ScriptNotFoundException('Invalid script name: %s' % script_name)
cea.ScriptNotFoundException: Invalid script name: toolbox

**Comment by daren-thomas** [comment]
@Lh0r, ok, so it seems you installed the CEA in the normal mode. This is good, but the errors you show are expected:

- `cea install-grasshopper`, there is an issue with the standard installation, in that it doesn't include the `CEA.ghuser` file for running the CEA in Rhino/Grasshopper - you'll need to install the "Developer" version to get that functionality. Please note that this interface (GH) is very experimental and not actively maintained - it will also only run on Rhino 5
- `cea toolbox` - I'm not quite sure what you're trying to achieve here... maybe you meant `cea install-toolbox`, which is an obsolete script used to install the CEA into ArcGIS. Instead, just use the "CEA GUI" (check your start-menu in Windows). This should get you up-and-running.
