### ISSUE TITLE
cea workflow checking resume-workflow.yml before creating it

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2561]
when running `cea workflow` from the console, i got the following error:
```
λ cea workflow
City Energy Analyst version 2.29.0
Running `cea workflow` with the following parameters:
- workflow:workflow = c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\district_heating_system.yml
  (default: c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\district_heating_system.yml)
- workflow:resume = False
  (default: False)
- workflow:resume-file = C:\reference-case-open/../resume-workflow.yml
  (default: {general:project}/../resume-workflow.yml)
Setting general:project=${CEA_general_project}/../reference-case-open
Setting general:multiprocessing=True
Setting radiation:daysim-bin-directory=${CEA_radiation_daysim-bin-directory}
Traceback (most recent call last):
  File "C:\Users\Shanshan\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 63, in main
    with open(resume_yml, 'w') as resume_fp:
IOError: [Errno 13] Permission denied: 'C:\\reference-case-open/../resume-workflow.yml'
```

and after i changed the config to `resume-file = {general:project}/resume-workflow.yml`
another error occured:
```
IOError: [Errno 2] No such file or directory: 'C:\\reference-case-open/resume-workflow.yml'
```

**Comment by daren-thomas** [comment]
@shanshanhsieh try setting `{general:project}` or `{general:scenario}` to an existing folder that you have write-access to. The error message above seems to be indicating that you don't have a `C:\reference-case-open` folder. Is that correct?

**Comment by reyery** [comment]
I guess the whole idea is for it to work with default values even if `reference-case-open` folder does not exist since `workflow` script is supposed to create/extract it as part of its step.

We could set the default file location to somewhere CEA would have write-access to because the assumption now is that the project folder must exist. Or we could just explicitly show an error message for the user to create/change the path of resume folder.

**Comment by daren-thomas** [comment]
@shanshanhsieh did you get around to testing the PR?
