### ISSUE TITLE
As a user I would like to run CEA on my MacOS

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2577]

**Comment by daren-thomas** [comment]
this is a question of dependencies and packaging.

**Comment by JIMENOFONSECA** [comment]
Should we give it priority in the upcoming sprints or rather move it after the migration to py3

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I think we should do this after migration to py3 - else we'd have to do the same work twice.

**Comment by JIMENOFONSECA** [comment]
Great. Let’s do that. So do we see cea 3 with py 3? :-)
On 10 Mar 2020, 20:33 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I think we should do this after migration to py3 - else we'd have to do the same work twice.

**Comment by daren-thomas** [comment]
@jimenofonseca you _could_ try using the docker image - and write a blog post on how to get it up and running?

The docker image is hosted on dockerhub as "darenthomas/cityenergyanalyst". it's compiled for x64.

**Comment by jimenofonseca** [comment]
Steps
1. Download docker desktop for mac.
    -> LInk: https://www.docker.com/products/docker-desktop
    -> 10 mins to download and install in SG
2. Download and install CEA docker image
   -> Open terminal
   -> Paste “docker pull darenthomas/cityenergyanalyst:latest”
   -> 5 mins to download and install in SG
3. Open docker desktop
   -> go to images.
   -> select the image and click RUN
   -> configure the container
	-> set a containername e.g., “CEA”
         -> set the Host Path of the Volume (information for CEA). It can be any folder e.g., /documents/volumes/cea/
   -> click run again

Problems:
-> While Cli shows that the container is running and the Cli fo the container says that CEA is running. It is not clear where.
-> I checked “docker container port CONTAINER. There is no port associated to cea. so where is the interface running?

<img width="459" alt="Screenshot 2020-12-07 at 1 30 20 PM" src="https://user-images.githubusercontent.com/8973186/101313137-78ea5000-3890-11eb-9e7c-85d74375fcca.png">
<img width="1107" alt="Screenshot 2020-12-07 at 1 30 12 PM" src="https://user-images.githubusercontent.com/8973186/101313142-7b4caa00-3890-11eb-9c7d-c424fb076906.png">

**Comment by reyery** [comment]
@jimenofonseca the default port for CEA is `5050`, maybe you can try mapping the host port `5050` to the same port in the container. Then you could try go to `http://localhost:5050/api` on your browser to see if it is able to connect to it.

**Comment by jimenofonseca** [comment]
Bravo! API runs after mapping.

Here are the steps: 
Here are the steps I took to reproduce this in a Mac OS.

1. Download docker desktop for mac.
-> LInk: https://www.docker.com/products/docker-desktop
-> 10 mins to download and install in SG

2. Download and install CEA docker image
-> Open terminal
-> Paste “docker pull darenthomas/cityenergyanalyst:latest”
-> 5 mins to download and install in SG

3. Run CEA image
-> open terminal
-> Paste “docker run -p 5050:5050 darenthomas/cityenergyanalyst:latest”
-> open your browser
-> Paste "http://localhost:5050/api/"

![Screenshot 2020-12-07 at 3 54 40 PM](https://user-images.githubusercontent.com/8973186/101324039-88739400-38a4-11eb-9bd5-81648db1055b.png)

**Comment by jimenofonseca** [comment]
Where is the GUI btw? I Imagine the old one will be usable but not the one in REACT or...?

**Comment by reyery** [comment]
The GUI would have to be installed separately to talk to the Docker container. Currently we only have the Windows version of the electron app but it **_should_** be quite straight forward to compile it to work for Mac.

**Comment by jimenofonseca** [comment]
Cool @reyery about the GUI, mind giving me a container for that so I can test it?

Another question, where can I find the command line of CEA? is there access to it from the image? I can start testing daysim there and other commands.

btw, @daren-thomas mind putting the image in a repo of Docker allusive to CEA? It may be good to avoid everyone checking your name in the build :).

**Comment by daren-thomas** [comment]
Status update: @martin-mosteiro and I were able to install the cea backend with conda and also get the GUI up and running on mac os. There are some things that are still not quite there yet:

- installation steps still need to be documented
- we'll need to build a mac os version of the Daysim binaries (separate hackathon planned)
- the dashboard still needs to be started manually first, before opening the GUI (run `cea dashboard` in terminal) as the GUI doesn't know how to start the dashboard on mac. This will probably only be fixable when creating a proper mac installation for users...
- socket.io doesn't seem to be working. also, it seems to be a problem from the gui side (@reyery maybe you're interested in investigating this? do you have access to a mac?)
- the icon for the GUI needs to be 512x512 px, and the one in the repo is 256x256. I'm not sure exactly how to handle that
- we're still a long way from shipping CEA for users
- @martin-mosteiro is busy documenting the steps...

**Comment by martin-mosteiro** [comment]
Status update: I have documented the installation steps as far as we got to today. The result is a full installation of CEA with non-functional Daysim and a partly-functional dashboard. I'll continue to update it after our next hackathon!

**Comment by martin-mosteiro** [comment]
Status update: last weekend we did a second hackathon on this. We created the Daysim binaries for Mac using CMake and Xcode and pushed it to the branch for this issue. However, this did *_not_* solve the issue on my computer. Daysim still does _not_ work on my Mac:
```
(cea) ita-schlueter-m:build martinmo$ cea radiation --daysim-bin-directory /Users/martinmo/Documents/GitHub/CityEnergyAnalyst/setup/Dependencies/Daysim/bin
City Energy Analyst version 3.15.0
Running `cea radiation` with the following parameters:
[...]
Generating geometry for building 1 completed out of 1: B1000
Sending the scene: geometry and materials to daysim
	radiation_main: rad.base_file_path: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/default_materials.rad
	radiation_main: rad.data_folder_path: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T
	radiation_main: rad.command_file: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/command.txt
	radiation_main: rad.rad_file_path: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/geometry.rad
isolation_daysim: daysim_dir=/var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0
	isolation_daysim: rad.hea_file: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/temp0.hea
	isolation_daysim: rad.hea_filename: None
	isolation_daysim: rad.daysimdir_ies: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/ies
	isolation_daysim: rad.daysimdir_pts: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/pts
	isolation_daysim: rad.daysimdir_rad: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/rad
	isolation_daysim: rad.daysimdir_res: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/res
	isolation_daysim: rad.daysimdir_tmp: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/tmp
	isolation_daysim: rad.daysimdir_wea: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/wea
Calculating and sending sensor points
	isolation_daysim: rad.sensor_file_path: /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/points_0.pts
Starting Daysim simulation starts for buildings ['B1000']
Total number of sensors:  754
Transforming weather files to daysim format
Transforming radiance files to daysim format
Running command `['radfiles2daysim', '/var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/temp0.hea', '-g', '-m', '-d']`
Writing radiance parameters
Executing hourly solar isolation calculation
Running command `['gen_dc', '/var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/tmp/temp0temp.hea', '-dir']`
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
Running command `['gen_dc', '/var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/tmp/temp0temp.hea', '-dif']`
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
Running command `['gen_dc', '/var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/tmp/temp0temp.hea', '-paste']`
Running command `['ds_illum', '/var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/temp0.hea']`
IN CASE YOU ARE USING DAYSIM UNDER WINDOWS, THE "RAPYPATH" VARIALBE MIGHT NOT HAVE BEEN SET CORRECTLY. TO TEST THIS, OPEN A DOS PROMPT AND TYPE 'set'. AMONG THE VARIALBLES DISPLAYED SHOULD BE 'Raypath c:\Daysim\lib'.
PLEASE REFER TO THE DAYSIM TUTORIAL FOR MORE INFORMATION...fatal - file /var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/res/temp0.dc does not contain any uncommented lines
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cea/bin/cea", line 33, in <module>
    sys.exit(load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')())
  File "/Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/interfaces/cli/cli.py", line 72, in main
    script_module.main(config)
  File "/Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 585, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.radiation)
  File "/Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 181, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, building_dict, locator, settings, max_global, weatherfile)
  File "/Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/daysim_main.py", line 211, in isolation_daysim
    rad.execute_ds_illum()
  File "/Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 516, in execute_ds_illum
    self.run_cmd(command1)
  File "/Users/martinmo/Documents/GitHub/CityEnergyAnalyst/cea/resources/radiation_daysim/radiation_main.py", line 272, in run_cmd
    subprocess.check_call(cmd, cwd=cwd, stderr=subprocess.STDOUT, env=os.environ)
  File "/opt/anaconda3/envs/cea/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ds_illum', '/var/folders/44/tzftk86n0h92yqw_4k__x_8r0000gn/T/temp0/temp0.hea']' returned non-zero exit status 1.
```
Since @daren-thomas is on vacation this is likely on pause until... some time in the future.

**Comment by shanshanhsieh** [comment]
the next debugging steps:

1. `commands.txt` in the Temp directory, check that and execute the command inside 
2. check the contents of the input files, especially for file references in `C:\\` windows format (this could be fine since it also works on ubuntu)

**Comment by brauliobarahona** [comment]
hello everyone, I just learned about CEA today and have this issue with running in Mac OS, one clarification does this applies only to the GUI? Since there are issues with part of the calculation engine (i.e. [DaySim](https://github.com/MITSustainableDesignLab/Daysim/issues/9) ) I guess this means I should not yet try to run scripts on a Mac? thanks!

**Comment by martin-mosteiro** [comment]
@brauliobarahona Indeed, the issue with running CEA on Mac is not the GUI, but rather the Daysim engine. Your best bet to use CEA on Mac OS is to [use a Docker image](https://city-energy-analyst.readthedocs.io/en/latest/developer/run-cea-in-docker.html#running-the-image-in-a-new-container).

**Comment by martin-mosteiro** [comment]
I have decided to give Docker another go on my Mac. I'm following [the corresponding tutorial](https://city-energy-analyst.readthedocs.io/en/latest/developer/run-cea-in-docker.html#running-the-image-in-a-new-container). It's slightly outdated (_To build the docker image, navigate to the folder docker/ in the CityEnergyAnalyst repository_) but workable. However, the first command already has issues in my case:
```
(cea) martin@x86_64-apple-darwin13 CityEnergyAnalyst % docker build -t dockeruser/cea:latest .
[+] Building 117.6s (16/26)                                                                                                             
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 37B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 35B                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                   3.3s
 => [internal] load metadata for docker.io/continuumio/miniconda3:latest                                                           3.3s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                      0.0s
 => [auth] continuumio/miniconda3:pull token for registry-1.docker.io                                                              0.0s
 => [cea-build 1/8] FROM docker.io/continuumio/miniconda3@sha256:592a60b95b547f31c11dc6593832e962952e3178f1fa11db37f43a2afe8df8d7  0.0s
 => [daysim-build 1/5] FROM docker.io/library/ubuntu:latest@sha256:9d6a8699fb5c9c39cf08a0871bd6219f0400981c570894cd8cbea30d3424a3  0.0s
 => [internal] load build context                                                                                                  0.1s
 => => transferring context: 48.16kB                                                                                               0.1s
 => CACHED [cea-runtime 2/7] RUN apt-get update && apt-get install -y libgl1                                                       0.0s
 => CACHED [daysim-build 2/5] RUN apt update && DEBIAN_FRONTEND="noninteractive" apt install -y git cmake build-essential libgl1-  0.0s
 => CACHED [daysim-build 3/5] RUN git clone https://github.com/MITSustainableDesignLab/Daysim.git                                  0.0s
 => [daysim-build 4/5] RUN mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_HEADLESS=ON -DOpenGL_GL_PREFERENC  19.4s
 => CACHED [cea-build 2/8] COPY environment.yml /tmp/environment.yml                                                               0.0s
 => ERROR [cea-build 3/8] RUN conda env create -f /tmp/environment.yml -n cea && conda clean -afy                                113.9s
 => [daysim-build 5/5] RUN sed -i 's/#add_definitions(-DDAYSIM)/add_definitions(-DDAYSIM)/' /Daysim/src/rt/CMakeLists.txt && cd   11.8s
------                                                                                                                                  
 > [cea-build 3/8] RUN conda env create -f /tmp/environment.yml -n cea && conda clean -afy:                                             
#12 1.152 Collecting package metadata (repodata.json): ...working... done                                                               
#12 38.66 Solving environment: ...working... Killed                                                                                     
------                                                                                                                                  
executor failed running [/bin/sh -c conda env create -f /tmp/environment.yml -n cea && conda clean -afy]: exit code: 137                
(cea) martin@x86_64-apple-darwin13 CityEnergyAnalyst % 
```

I am not sure who to ask for help on Docker... @reyery? @shanshanhsieh? @someoneelse? Any hints or an idea whom to ask/where to get help?

**Comment by daren-thomas** [comment]
@martin-mosteiro that's not necessarily a _docker_ issue. It looks like the conda environment isn't being created. Maybe it's a really old environment?

**Comment by reyery** [comment]
@martin-mosteiro I think that is something to do with how much resources (RAM and storage) you have assigned to docker. The conda build uses quite a bit of storage. You can try increasing the storage assigned to docker in the docker dashboard and run it again.

**Comment by martin-mosteiro** [comment]
Oh hi @daren-thomas 🤗
Thanks for the comments Daren and @reyery. I'll adjust the resources and give it another go.

**Comment by martin-mosteiro** [comment]
For future reference: I assigned to Docker 4GB of ram and 96 GB of storage. Worked well!

**Comment by martin-mosteiro** [comment]
Update: running CEA from the command line on Docker worked for me. Success!
Running the dashboard, however, did _not_. That's still good enough for my purposes, but I guess it doesn't fully solve issue #2577 for users who wanna use the dashboard.

**Comment by martin-mosteiro** [comment]
Is this issue officially solved? It requires some workarounds and having your hand held through setting everything up (thanks @reyery) but there is now _a_ working version of CEA for Mac, both from the command line and on the dashboard.

If we deem the current status to be good enough to close the issue, I can create a little guide for working with CEA on Mac if that's desirable. It'd essentially be "Step 1: [run CEA in Docker](https://city-energy-analyst.readthedocs.io/en/latest/developer/run-cea-in-docker.html). Step 2: do a few small Mac-specific additional steps to get the dashboard going."

**Comment by daren-thomas** [comment]
I'd say the little guide would be what solves the issue, no?

**Comment by martin-mosteiro** [comment]
@daren-thomas I agree!

**Comment by martin-mosteiro** [comment]
I assigned PR #3028 to @reyery since he can probably judge whether the commands I listed make sense, but if @daren-thomas wants to give feedback on the guide itself, you are more than welcome too! :)

**Comment by shanshanhsieh** [comment]
@reyery will make a PR with the updated Daysim binary for MAC!!!!!

**Comment by reyery** [comment]
PR created for Daysim https://github.com/MITSustainableDesignLab/Daysim/pull/10
