### ISSUE TITLE
system-costs: KeyError: 'Opex_var_buy_USD2015perkWh'

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2600]
Steps to reproduce:

- create a new project/scenario
  - db: CH
  - location: kleinalbis (choose a couple of buildings around nr. 80)
  - weather zurich
- run archetypes-mapper, radiation, schedule-maker, demand
- run `system-costs`

Expected this to run through. Instead, I get the following message in CityEnergyAnalyst v2.31.0:

```
City Energy Analyst version 2.31.1
Running `cea system-costs` with the following parameters:
Traceback (most recent call last):
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\costs\system_costs.py", line 201, in main
    costs_main(locator=locator,config=config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\costs\system_costs.py", line 37, in costs_main
    factors_resources_simple = [(name, values['Opex_var_buy_USD2015perkWh'].mean()) for name, values in factors_resources.items()]
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Opex_var_buy_USD2015perkWh'

- general:scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\2020.02.24\kleinalbis
  (default: {general:project}\{general:scenario-name})
- costs:capital = True
  (default: True)
- costs:operational = True
  (default: True)
Running system-costs with scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\2020.02.24\kleinalbis
```

**Comment by daren-thomas** [comment]
@reyery @JIMENOFONSECA this is blocking my efforts to update schemas.yml and the glossary shown in the documentation.
