### ISSUE TITLE
ConfigParser.ParsingError

### ISSUE THREAD

**Issue by nasty-bos** [architecture-building-systems/CityEnergyAnalyst#2606]
Occasionally getting _ConfigParser.ParsingError: File contains parsing errors: C:\Users\HHM/cea.config_ while using multiprocessing within workflow. Deleting config file and using a default one didn't help.
```
Using 7 CPU's
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\forking.py", line 510, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\workflows\workflow.py", line 16, in <module>
    import cea.api
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\api.py", line 71, in <module>
    register_scripts()
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\api.py", line 14, in register_scripts
    config = cea.config.Configuration()
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\config.py", line 35, in __init__
    self.user_config.read([DEFAULT_CONFIG, config_file])
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: C:\Users\HHM/cea.config
	[line 182]: 'm'
```
Using V2.31 on two computers with Windows - both run into the same issue.

**Comment by daren-thomas** [comment]
@nasty-bos could you attach the offending file please (`C:\Users\HHM/cea.config`) - I'm especially interested in the lines around 182.

**Comment by nasty-bos** [comment]
@daren-thomas here we go: 

[ceaconfigfile.txt](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4254855/ceaconfigfile.txt)

couple of times the error was encountered in the line 179 too.

**Comment by daren-thomas** [comment]
@nasty-bos hm.... that seems to be ok. I think @reyery is working on a solution here - we found some race conditions pertaining to config files that might show up with multiprocessing.
