### ISSUE TITLE
ValueError: invalid literal for int() with base 2: '' when running the Decentralized script

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2608]
Steps to reproduce:

- project/scenario = reference-case-open/baseline
- run standard workflow up to "Supply System Part I (decentralized)" (see `district-heating-system.yml`)

Expected: Script runs through. Instead, I get this error:

```
City Energy Analyst version 2.31.0
Running `cea decentralized` with the following parameters:
- general:scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\reference-case-open\baseline
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
Running decentralized model for buildings with scenario = C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\reference-case-open\baseline
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 56, in main
    do_script_step(config, step)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 141, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\workflows\workflow.py", line 29, in run
    f(config=config, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\decentralized_building_main.py", line 54, in main
    config=config, prices=prices, lca=lca)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\decentralized_building_main.py", line 36, in disconnected_building_main
    config, prices, lca)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\optimization\preprocessing\decentralized_buildings_heating.py", line 54, in disconnected_buildings_heating_main
    substation.substation_main_heating(locator, total_demand, building_names)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\substation.py", line 74, in substation_main_heating
    DHN_barcode)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\technologies\substation.py", line 550, in substation_model_heating
    substation_activation.to_csv(locator.get_optimization_substations_results_file(name, "DH" , DHN_barcode), sep=',',
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\inputlocator.py", line 495, in get_optimization_substations_results_file
    district_network_barcode_hex = hex(int(str(district_network_barcode), 2))
ValueError: invalid literal for int() with base 2: ''
```

**Comment by daren-thomas** [comment]
@JIMENOFONSECA do you maybe know what is happening here? (I'm guessing the change in how the optimization script refers to individuals might be the culprit?)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas mind telling me what is the value of district_network_barcode? before the crash?

**Comment by JIMENOFONSECA** [comment]
btw, maybe we can include the decentralized script now in the unitests? I mean now that the scripts are super fast

**Comment by daren-thomas** [comment]
@JIMENOFONSECA testing your branch right now. The testing works like this:

- `cea test --workflow quick` (default workflow for testing) will run a bunch of scripts excluding the slower ones - this is run for every PR
- `cea test --workflow unittests` runs all unittests in `cea/tests`
- `cea test --workflow slow` runs all the scripts when merging to master - currently, it's failing due to this issue.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA where do I find `district_network_barcode`?
