### ISSUE TITLE
Unable to edit code column in Database Editor for Assemblies/Envelope/Construction

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2612]
Steps to reproduce: 

- open Database Editor
- navigate to Assemblies / Envelope / Construction
- click "Add Row"
- enter Description, Cm_Af
- enter code

Expected: Entering code succeeds

Buggy behavior: The column seems to be read-only - I can't enter any text at all. Saving the new entry results in the Input Editor complaining: "ERROR: index 0 is out of bounds for axis 0 with size 0"

```
Traceback (most recent call last):
  File "C:\Users\daren-thomas\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\daren-thomas\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\daren-thomas\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\daren-thomas\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\daren-thomas\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\users\daren-thomas\documents\github\cityenergyanalyst\cea\interfaces\dashboard\api\inputs.py", line 115, in get
    store = get_building_properties()
  File "c:\users\daren-thomas\documents\github\cityenergyanalyst\cea\interfaces\dashboard\api\inputs.py", line 235, in get_building_properties
    columns[column]['choices'] = get_choices(field['choice_properties'], path)
  File "c:\users\daren-thomas\documents\github\cityenergyanalyst\cea\interfaces\dashboard\api\inputs.py", line 440, in get_choices
    label = df.loc[df[lookup['column']] == choice, 'Description'].values[0] if 'Description' in df.columns else ''
IndexError: index 0 is out of bounds for axis 0 with size 0
```

@reyery this might be an easy bug to fix. Would you mind taking a look please? I need it for my blog article.

**Comment by reyery** [comment]
@daren-thomas could you try the GUI in https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/17

**Comment by daren-thomas** [comment]
@reyery assigning this to you as I believe you fixed it.
