### ISSUE TITLE
Archetypes Mapper - IndexError : single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2616]
**Describe the bug**
There is an error when trying to run the Archetypes Mapper in CEA 2.31 . I have been working with **conda environments** (due to dependency clashes with other programs), and I have a conda environment called CEA for the use of the City Energy Analyst. The environment was active when the error occured. I don't know if it may be the reason.

**To Reproduce**
1. Launch a scenario in CEA
2. Input the zone.shp and the district.shp files
3. Run **Data Management > Archetypes Mapper**

**Screenshots**
I get the following error : 

```
City Energy Analyst version 2.31.0    
Running cea archetypes-mapper with the following parameters:
- general:scenario = C:\Users\AlexandreJewell\Desktop\PUVSA\CEA\VSA\Default_CH
  (default: {general:project}\{general:scenario-name})
Traceback (most recent call last):
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\archetypes_mapper.py", line 452, in main
    buildings=buildings)
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\archetypes_mapper.py", line 94, in archetypes_mapper
    architecture_mapper(locator, building_typology_df)
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\archetypes_mapper.py", line 213, in architecture_mapper
    dataframe_to_dbf(prop_architecture_df[fields], locator.get_building_architecture())
  File "c:\users\alexandrejewell\anaconda3\envs\cea\cityenergyanalyst\cityenergyanalyst\cea\utilities\dbf.py", line 50, in dataframe_to_dbf
    types = [type(df[i].iloc[0]) for i in df.columns]
  File "C:\Users\AlexandreJewell\Anaconda3\envs\CEA\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\AlexandreJewell\Anaconda3\envs\CEA\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 2102, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Users\AlexandreJewell\Anaconda3\envs\CEA\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 2009, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds 
```

Here are the parameters I was using : 
```
- archetypes-mapper:input-databases = ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules']
  (default: ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules'])
- archetypes-mapper:buildings = []
  (default: [])
Running archetypes-mapper with scenario = C:\Users\AlexandreJewell\Desktop\PUVSA\CEA\VSA\Default_CH
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version : CEA 2.31

**Comment by daren-thomas** [comment]
@AlexJew can you try re-running `cea archetypes-mapper`, but instead use the CEA Console? It has it's own environment and that way we can ensure we're all working with the same packages.

**Comment by JIMENOFONSECA** [comment]
@AlexJew can you check if the values inside "typology" (on the CEA interface) are valid for your buildings? do they map to your database of "Archetypes/use_types"? Let us know. @reyery we may keep track of this and create a warning message if this is the case. OR what about validation so the users cannot run anything unless typology and zone are ok?

**Comment by AlexJew** [comment]
@daren-thomas I ran the `cea archetypes-mapper` via the CEA console and got the same error.

@JIMENOFONSECA I am not sure I understood what you meant, but I compared the typology.dbf file of my scenario (I am still using the default CH one) and the typology from the CEA interface, and they were the same.

![imagem](https://user-images.githubusercontent.com/32110882/75548286-d52c6380-5a24-11ea-9d98-a312dd2092f6.png)

**Comment by reyery** [comment]
@AlexJew it seems to me that the values for `STANDARD` are wrong. They are supposed to be in the format `STANDARD1` not `T1`. May I know how did you create the scenario? I'm assuming you created it by importing your own `zone` and `surrounding` files and the `typology` file was created for you by CEA. In that case, there might be something wrong with how CEA is creating the typology file.

**Comment by JIMENOFONSECA** [comment]
Hi alex, i think this has to do with our latest update, where we standarized the names of the ‘standard’ filed in typology. Try to ise the latest version. Asign a new database to the scenario (button on the right of the database editor), check the typology file from the cea interface and run archetypes mapper.

Let us know if this works.
On 28 Feb 2020, 20:42 +0800, Reynold Mok <notifications@github.com>, wrote:

@AlexJew<https://github.com/AlexJew> it seems to me that the values for STANDARD are wrong. They are supposed to be in the format STANDARD1 not T1. May I know how did you create the scenario? I'm assuming you created it by importing your own zone and surrounding files and the typology file was created for you by CEA. In that case, there might be something wrong with how CEA is creating the typology file.

**Comment by AlexJew** [comment]
Hello @JIMENOFONSECA @reyery , sorry for the late answer. Indeed, the problem had to do with backward compatibility. I did as you said @JIMENOFONSECA and it worked. Thanks :)
