### ISSUE TITLE
cooling case workflow not running

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2644]
**Describe the bug**
`cea workflow` does not run when `workflow = district-cooling-system`
more specifically, there is a problem when running the radiation script

**To Reproduce**
1. run `cea workflow` with `workflow = district-cooling-system`
2. See error
```
Traceback (most recent call last):
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 83, in main
    do_script_step(config, step, trace_input)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 172, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 30, in run
    f(config=config, **kwargs)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 464, in main
    config)
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 538, in geometry_main
    height_col='height_ag', nfloor_col="floors_ag")
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 267, in building_2d_to_3d
    [data_preprocessed for x in range(n)])
  File "c:\users\zhongming\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 97, in wrapper
    result = map_result.get()
  File "C:\Users\Zhongming\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
KeyError: u'the label [B1001] is not in the [index]'
```
**Expected behaviour**
successful execution of the workflow for a cooling case

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version : 2.32.0

**Comment by shanshanhsieh** [comment]
the radiation script is running for other cases, something is wrong with the specific combination of this case and the weather file

**Comment by daren-thomas** [comment]
This is connected to #2640 and seems to be a problem not with the radiation script itself, but with the `archetypes-mapper` using a CH typology input file but using SG archetypes - after running the Archetypes Mapper, some of the input tables do not have all the buildings.

Yes. This needs to be fixed. I think having a separate SG case would be best.

**Comment by JIMENOFONSECA** [comment]
may I suggest the same project but different scenario? just for the sake of keeping things tidy.

**Comment by daren-thomas** [comment]
you mean `reference-case-open/sg-baseline` or something? sure. that would keep things tidier. but the scenario should be in Singapore. And... it's ok if it's a really small case (3 buildings should do, no?) as we just want to be able to run all the different codepaths...

**Comment by JIMENOFONSECA** [comment]
well that would not work though...but hey what is the problem? is it that the workflow does not work for SG as a database? if it is that I guess that can be fixed. I remember thinking about that.


Maybe shanshan can describe what is the issue? and at what point does it happen?


I think we can solve it without the need of another case. remember that we have measured data for this one. It is also realistic. The best scenario we have so far for testing. It would be a pity to come back to more simple things.

________________________________

**Comment by daren-thomas** [comment]
@JIMENOFONSECA the archetypes don't map - try opening the scenario and then running it as an SG case - some of the input tables lose half of their buildings. I'm guessing it's to do with how the tables are joined (an inner join will remove all rows that don't join).

the thing is, if we don't have a SG case, we're not testing that stuff.

so yes - you have a scenario with measured data and that serves a purpose, but another thing we're trying to do is test all _code paths_. that's a different kind of testing. we currently don't really go through all the `if` branches (and similar things) in our testing and that can mean some stuff stops working and we never find out about it.

i don't think it would be a pity at all. but i _do_ think it's a good idea to mention somehow that the data is not realistic. i was thinking instead of the 4x4 buildings we used to have, we use the tool to create a scenario from OSM? that _should_ be realistic too, no?
