### ISSUE TITLE
Installed Capacities plot fails for system = _sys_today

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2648]
Steps to reproduce:

- run `cea workflow --workflow district-heating-system`
- open GUI at scenario (`reference-case-open/baseline`, as created in previous step)
- navigate to Dashboard
- add plot, choose Category="Supply System", Plot="Installed Capacities"
- for parameters, choose scenario-name="baseline", system="_sys_today" (the default)
- expected a plot, but instead get the following message:

```
This plot can't be displayed because some input files are missing:

C:\Users\darthoma\Documents\CityEnergyAnalyst\projects\reference-case-open\baseline\outputs\data\optimization\slave\gen_sys\ind_today_Electricity_Requirements_Pattern.csv
Try running these scripts first:

Supply System Part II (centralized)
```

Tried re-running the optimization script, but the file is never generated.

**Comment by reyery** [comment]
I have tried it and can confirm that I have the same issue. 

It seems that `Supply System Part II (centralized)` does not run any tool/analysis for `_sys_today_` but only for those created during optimization as part of the script, therefore the file would not be created.

One way to solve it is to maybe try to run `_sys_today_` with `cea/optimization/master/evaluation.py` which helps create the data needed.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/d695eac0f151a8f8570981f60829b93663d74e59/cea/optimization/master/evaluation.py#L94-L129

**Comment by shanshanhsieh** [comment]
we will not create the plots for `_sys_today_` for the moment, but it is an upcoming feature.
this feature will require a *supply system simulator* tool

**Comment by daren-thomas** [comment]
@shanshanhsieh I can't get this plot to run for any system:

- Installed Capacities for sys_89_0 - baseline:

```
Traceback (most recent call last):
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\darthoma\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\interfaces\dashboard\plots\routes.py", line 46, in route_div
    plot_div = plot.plot_div()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\base.py", line 161, in plot_div
    return self.cache.lookup_plot_div(self, self._plot_div_producer)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\cache.py", line 51, in lookup_plot_div
    plot_div = producer()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\base.py", line 164, in _plot_div_producer
    fig = plotly.graph_objs.Figure(data=self.calc_graph(), layout=self.layout)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\b_installed_capacities.py", line 97, in calc_graph
    data_disconnected = self.process_disconnected_capacities_kW()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\cache.py", line 156, in wrapper
    plot=self, producer=lambda: producer(self))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\cache.py", line 43, in lookup
    return self.store_cached_value(data_path, plot.parameters, producer)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\cache.py", line 128, in store_cached_value
    data = super(MemoryPlotCache, self).store_cached_value(data_path, parameters, producer)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\cache.py", line 100, in store_cached_value
    data = producer()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\cache.py", line 156, in <lambda>
    plot=self, producer=lambda: producer(self))
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\plots\supply_system\__init__.py", line 177, in process_disconnected_capacities_kW
    dataframe = cool.set_index('Name')
AttributeError: 'NoneType' object has no attribute 'set_index'
```

**Comment by reyery** [comment]
Hmmm.. That might possibly mean that both heating and cooling capacity files are empty since both are `None`. But its hard to tell since it is using a catch all exception and could be caused by something else. Would change this to catch `pandas.errors.EmptyDataError` instead since I think it was the intended logic.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/1c2d4c9b24342f74be1a43e9d10ec76fb690712e/cea/plots/supply_system/__init__.py#L163-L183
