### ISSUE TITLE
unittest failing on master

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2679]
**Describe the bug**
The unittest is not passing in the master branch. @daren-thomas could you please take a look at this? Thanks!

**To Reproduce**
1. Go to cea consold
2. Do `cea test`

**Expected behaviour**
Succesful completion of unittest.

```
======================================================================
ERROR: test_category_names_in_plots (test_plots.TestCategories)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\test_plots.py", line 28, in test_category_names_in_plots
    for plot in category.plots:
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\categories.py", line 97, in plots
    module = importlib.import_module(modname)
  File "C:\Users\Shanshan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\plots\supply_system\supply_system_map.py", line 14, in <module>
ImportError: cannot import name network_layout

----------------------------------------------------------------------
Ran 19 tests in 156.532s

FAILED (errors=1)
Traceback (most recent call last):
  File "C:\Users\Shanshan\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 66, in main
    script_module.main(config)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\__init__.py", line 38, in main
    cea.workflows.workflow.main(default_config)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 83, in main
    do_script_step(config, step, trace_input)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 172, in do_script_step
    run(config, py_script, **py_parameters)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\workflows\workflow.py", line 30, in run
    f(config=config, **kwargs)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\shanshan\documents\cityenergyanalyst\cityenergyanalyst\cea\tests\run_unit_tests.py", line 28, in main
    raise AssertionError("Unittests failed.")
AssertionError: Unittests failed.
```

**Comment by shanshanhsieh** [comment]
the test works after cleaning the .pyc files
