### ISSUE TITLE
_ensure_folder method in InputLocator class may create race condition when used with multiprocessing

### ISSUE THREAD

**Issue by nasty-bos** [architecture-building-systems/CityEnergyAnalyst#2687]
**Describe the bug**
While running "cea photovaltaic" within workflow for the districts containing multiple buildings of exactly same kind, simulation would often crash at the beginning of writing the results (BuildingName_PV.csv) into _outputs\\data\\potentials\\solar_ folder. 

**To Reproduce**
Difficult to reproduce as conditions require that the calculation for 2 buildings is finished simultaneously (which was often the case in my scenarios since the districts contain same buildings).

**Expected behaviour**
I would expect a folder to have been created before multiprocess is allowed to write into it i.e. 

```
    if not os.path.exists(locator.solar_potential_folder()):
        os.mkdir(locator.get_solar_radiation_folder())
```
Alternatively, one could catch the error in the "_ensure_folder" method and proceed with remaining execution after a short pause (100ms) and one final check for existence of the folder i.e. 

```
    @staticmethod
    def _ensure_folder(*components):
        """Return the `*components` joined together as a path to a folder and ensure that that folder exists on disc.
        If it doesn't exist yet, attempt to make it with `os.makedirs`."""
        folder = os.path.join(*components)
        if not os.path.exists(folder):
            try:
                os.makedirs(folder)
            except WindowsError as e:
                if "[Error 183] Cannot create a file when that file already exists" in e.__str__():
                    print("Error in creating [%s] - folder was created before I could create it")
                    time.sleep(0.1)
                    assert os.path.exists(folder), \
                        "Folder [%s] still not created or was deleted - aborting"
                else:
                    raise e
        return folder

```

**Screenshots**

```
Using 7 CPU's
calculating solar properties done
gathering properties of PV panel
calculating solar properties done
gathering properties of PV panel
calculating solar properties done
gathering properties of PV panel
calculating solar properties done
gathering properties of PV panel
calculating solar properties done
gathering properties of PV panel
calculating solar properties done
gathering properties of PV panel
calculating solar properties done
gathering properties of PV panel
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
filtering low potential sensor points done
calculating optimal tile angle and separation done
generating groups of sensor points done
Traceback (most recent call last):
  File "C:/Users/HHM/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/workflows/workflow.py", line 216, in <module>
    main(config)
  File "C:/Users/HHM/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/workflows/workflow.py", line 60, in main
    do_script_step(config, step)
  File "C:/Users/HHM/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/workflows/workflow.py", line 145, in do_script_step
    run(config, py_script, **py_parameters)
  File "C:/Users/HHM/Documents/CityEnergyAnalyst/CityEnergyAnalyst/cea/workflows/workflow.py", line 33, in run
    f(config=config, **kwargs)
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\technologies\solar\photovoltaic.py", line 782, in main
    buildings_names)
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\utilities\parallel.py", line 97, in wrapper
    result = map_result.get()
  File "C:\Users\HHM\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
WindowsError: [Error 183] Cannot create a file when that file already exists: 'D:\\MVP_Lshape_3\\outputs\\lshape\\l_31_12_07\\outputs\\data\\potentials\\solar'

```

**Hardware**
 - Windows 10
 - Version of CEA 2.30.0

**Comment by daren-thomas** [comment]
@nasty-bos thank you! I think an adaptation of your 2nd solution could work - but instead of catching the `WindowsError` (non-portable, error message could change from version to version or maybe even be in a different language), we might be able to catch a more generic error or just sleep and check if it exists before re-trying...

**Comment by daren-thomas** [comment]
Wait. Actually, your first solution is much much cleaner!

**Comment by nasty-bos** [comment]
Agreed, first solution is simple and transparent, unfortunately it is not generic, working only for this specific case and not really addressing the underlying problem. 

The second solution could be better in my opinion but requires some further thought. Catching OSError would be too broad i.e. catch an exception of "disk full" or "file not found" instead of the one we're interested in. Catching WindowsError is too narrow. Perhaps we could catch OSError, sleep, then proceed to check that the folder was created and re-throw the error if it was not, propagating the actual error stored in "e"? 

```
    @staticmethod
    def _ensure_folder(*components):
        """Return the `*components` joined together as a path to a folder and ensure that that folder exists on disc.
        If it doesn't exist yet, attempt to make it with `os.makedirs`."""
        folder = os.path.join(*components)
        if not os.path.exists(folder):
            try:
                os.makedirs(folder)
            except OSError as e:
                time.sleep(0.1)
                if not os.path.exists(folder):
                    raise e
        return folder
```

One potential problem I see is that sleep may be too short. Perhaps 500-1000ms is a better trade-off?

**Comment by shanshanhsieh** [comment]
Hi @nasty-bos,
Would you be interested in becoming a developer of CEA?
We've added you as a contributor!
Please create a pull request with the proposed changes, and assign @daren-thomas as the reviewer.
thank you!
