### ISSUE TITLE
network-layout error, length mismatch

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2689]
When I run the network-layout script for one specific scenario, the following error is raised: 
```
`Traceback (most recent call last):
  File "C:/Users/emanuel/Documents/CityEnergyAnalyst_New/CityEnergyAnalyst/cea/technologies/network_layout/main.py", line 96, in <module>
    main(cea.config.Configuration())
  File "C:/Users/emanuel/Documents/CityEnergyAnalyst_New/CityEnergyAnalyst/cea/technologies/network_layout/main.py", line 92, in main
    layout_network(network_layout, locator)
  File "C:/Users/emanuel/Documents/CityEnergyAnalyst_New/CityEnergyAnalyst/cea/technologies/network_layout/main.py", line 65, in layout_network
    allow_looped_networks, optimization_flag, plant_building_names, disconnected_building_names)
  File "C:\Users\emanuel\Documents\CityEnergyAnalyst_New\CityEnergyAnalyst\cea\technologies\network_layout\steiner_spanning_tree.py", line 121, in calc_steiner_spanning_tree
    new_mst_nodes.loc[:, 'Name'] = names_temporary
  File "C:\Users\emanuel\Documents\CityEnergyAnalyst_New\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 189, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "C:\Users\emanuel\Documents\CityEnergyAnalyst_New\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 606, in _setitem_with_indexer
    raise ValueError('Must have equal len keys and value '
ValueError: Must have equal len keys and value when setting with an iterable`
```
The problem is, the whole file is too big to share through normal channels (14.7 GB),
Here the building geometry and building properties folders as well as the first outputs of the DC network before the script shoes an error: 
[scenario_network_error.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4469114/scenario_network_error.zip)

It seems that "nodes.shp" and the temp file "nodes_buildings.shp" have different length. 
this is the end output of the nodes.shp file: 
```
294  294.0   ...        NONE
295  295.0   ...        NONE
296  296.0   ...        NONE
297  297.0   ...        NONE
298    NaN   ...       B1089
```
and that of  "nodes_buildings.shp" :

`'NODE294', 'NODE295', 'NODE296', 'NODE297']`

The error is Scenario specific, i have tested with a newly setup scenario and it works fine. 

What could be the cause? Any hint on what causes the problem would be great? 
Also, where is the temp file "nodes_buildings.shp"  created?

- CEA Version 3.0.2 and current master ( '1c2d4c9')

**Comment by lguilhermers** [comment]
Jimeno, Emanuel and I will give a try on this bug tomorrow (14/04)
