### ISSUE TITLE
'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by MarelloAvanzini** [architecture-building-systems/CityEnergyAnalyst#2772]
**Describe the bug**
An error occurs when running a radiation simulation on a scenario I have created by modifying a shapefile of Lisbon I have been given for my thesis. I used QGIS to merge smaller buildings 5 by 5 into the 2-stories linear buildings you see on the right and to draw the single-storey buildings with various shapes at the center (some were overlapping in the original file); therefore I guess the problem lays somewhere there, but I am not sure about it.

**To Reproduce**
1. Click 'Open project', select the path of 'Padre Cruz' and click on 'Open'
2. Click on 'Padre Cruz_baracas_lineas_trial' > 'Open'
3.Go to 'Tools' > 'Demand forecasting' > 'Building Solar Radiation' 
4. Click on 'Run Script'
5. See the error

**Expected behaviour**
The radiation simulation should run smoothly
![Padre Cruz with error](https://user-images.githubusercontent.com/64660466/84567231-99b96900-ad77-11ea-8963-71a9294c2063.PNG)
![Padre Cruz - Multipolygonerror](https://user-images.githubusercontent.com/64660466/84567233-9b832c80-ad77-11ea-9a3c-8814dee92db0.PNG)

**Hardware (please complete the following information):**
    iOS 10.12 (CEA running on Windows 10 partition)
    CEA v. 3.2

I report the error text here:

City Energy Analyst version 3.2.0
Running `cea radiation` with the following parameters:
- general:scenario = C:\Users\Marello\Desktop\CEA projects\Padre Cruz\Padre Cruz_baracas_lineas_trial
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = []
  (default: [])
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:consider-intersections = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = C:\Users\Marello\Documents\CityEnergyAnalyst\Dependencies\Daysim
  (default: C:\Daysim\bin)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
verifying geometry files
C:\Users\Marello\Desktop\CEA projects\Padre Cruz\Padre Cruz_baracas_lineas_trial\inputs\building-geometry\zone.shp
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
getting geometry materials
creating 3D geometry and surfaces
Reading terrain geometry
Creating 3D building surfaces
Traceback (most recent call last):
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 483, in main
    config)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 533, in geometry_main
    height_col='height_ag', nfloor_col="floors_ag")
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 235, in building_2d_to_3d
    data_preprocessed = BuildingData(locator, settings, geometry_terrain, height_col, nfloor_col)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 146, in __init__
    self.surroundings_building_solid_list = np.vectorize(self.calc_surrounding_building_solids, otypes=[object])(self.surroundings_building_names)
  File "C:\Users\Marello\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\Marello\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2048, in _vectorize_call
    outputs = ufunc(*inputs)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 195, in calc_surrounding_building_solids
    face_footprint = burn_buildings(geometry, self.terrain_intersection_curves)
  File "c:\users\marello\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\geometry_generator.py", line 379, in burn_buildings
    point_list_2D = geometry.exterior.coords
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by daren-thomas** [comment]
@MarelloAvanzini - thank you for reporting this. We'll schedule this in an upcoming sprint.

For now, the CEA doesn't actually work with MultiPolygon shapefiles for the zone: instead, can you create the scenario with Polygon shapefiles?

**Comment by daren-thomas** [comment]
@MarelloAvanzini - we're closing this issue for now. Please feel free to file a new issue with follow up questions :)
