### ISSUE TITLE
Thermal Network Simulation - UnboundLocalError: local variable 'tavg' referenced before assignment

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2781]
**Describe the bug**
Hello CEA developers! I am using CEA to design a heating and cooling network for a future neighbourhood. The module **Thermal Network Part I (layout)** for designing the layout has worked for both DH and DC. However, I have tried using the simplified model for the simulation with **Therma Network Part II (Simulation)**, and it only ran for the DC. For the DH, I got the following error:
```
C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\folium\__init__.py:59: UserWarning:

This version of folium is the last to support Python 2. Transition to Python 3 to be able to receive updates and fixes. Check out https://python3statement.org/ for more info.

City Energy Analyst version 3.3.0
Running `cea thermal-network` with the following parameters:
- general:scenario = C:\Users\jewell\Desktop\CEA\VSA\Comfort_for_future
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- thermal-network:network-type = DH
  (default: DH)
- thermal-network:network-model = simplified
  (default: simplified)
- thermal-network:min-head-substation = 20.0
  (default: 20.0)
- thermal-network:hw-friction-coefficient = 100
  (default: 100)
- thermal-network:peak-load-velocity = 2.0
  (default: 2.0)
- thermal-network:equivalent-length-factor = 0.2
  (default: 0.2)
- thermal-network:peak-load-percentage = 100.0
  (default: 100.0)
- thermal-network:network-names = []
  (default: [])
- thermal-network:set-diameter = True
  (default: True)
- thermal-network:load-max-edge-flowrate-from-previous-run = False
  (default: False)
- thermal-network:start-t = 0
  (default: 0)
- thermal-network:stop-t = 8760
  (default: 8760)
- thermal-network:use-representative-week-per-month = False
  (default: False)
- thermal-network:minimum-mass-flow-iteration-limit = 30
  (default: 30)
- thermal-network:minimum-edge-mass-flow = 0.1
  (default: 0.1)
- thermal-network:diameter-iteration-limit = 10
  (default: 10)
- thermal-network:substation-cooling-systems = ['ahu', 'aru', 'scu']
  (default: ['ahu', 'aru', 'scu'])
- thermal-network:substation-heating-systems = ['ahu', 'aru', 'shu', 'ww']
  (default: ['ahu', 'aru', 'shu', 'ww'])
- thermal-network:temperature-control = VT
  (default: VT)
- thermal-network:plant-supply-temperature = 80.0
  (default: 80.0)
- thermal-network-optimization:use-representative-week-per-month = False
  (default: False)
Traceback (most recent call last):
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 53, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 33, in script_runner
    script_module.main(config)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\technologies\thermal_network\thermal_network.py", line 3591, in main
    thermal_network_simplified(locator, config, network_name)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\technologies\thermal_network\simplified_thermal_network.py", line 195, in thermal_network_simplified
    substation.substation_main_heating(locator, total_demand, building_names, DHN_barcode=DHN_barcode)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\technologies\substation.py", line 66, in substation_main_heating
    Ths_supply_C, Ths_return_C = calc_temp_hex_building_side_heating(substation_demand, heating_configuration)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\technologies\substation.py", line 87, in calc_temp_hex_building_side_heating
    Ths_return, Ths_supply = calc_compound_Ths(building_demand_df, heating_configuration)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\technologies\substation.py", line 433, in calc_compound_Ths
    Ths_ahu_return, Ths_aru_return, Ths_shu_return
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2048, in _vectorize_call
    outputs = ufunc(*inputs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\technologies\substation.py", line 762, in calc_HEX_mix_3_flows
    return np.float(tavg)
UnboundLocalError: local variable 'tavg' referenced before assignment
```

I do not know if running with another model than the simplified model would result

**To Reproduce**
1. Download the following inputs: https://we.tl/t-pIaXPAmi3i
2. Run prerequisite modules
3. Run **Thermal Network Part I (layout)** with DH
4. Run **Thermal Network Part II (simulation)** with DH 

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA: 3.3

**Comment by shanshanhsieh** [comment]
this problem is being resolved: https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/c91e0a4439c95f2a95125d0b679f883a07bfb563/cea/technologies/substation.py#L756-L761
