### ISSUE TITLE
AttributeError with streets.shp

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2782]
**Describe the bug**
Hello CEA developers, I am currently working with CEA to design a thermal network for a future neighbourhood in Lisbon. Since the streets remain to be built, I have drawn the future street layout that I export to CEA. I was using a _single multipart polygon_ for the street layout up until now, but when trying to build the thermal network, I realised that CEA required _single part polygons_ in order to build a proper coordinate sequence. I have split the _multipart feature_ to _single part features_, however when going in the **Input Editor**, the following error pops up: 
```
Traceback (most recent call last):
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\inputs.py", line 127, in get
    locator.get_street_network(), trigger_abort=False)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\inputs.py", line 305, in df_to_json
    lat, lon = get_lat_lon_projected_shapefile(table_df)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\utilities\standardize_coordinates.py", line 65, in get_lat_lon_projected_shapefile
    data = data.to_crs(get_geographic_coordinate_system())
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 386, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geoseries.py", line 288, in to_crs
    result = self.apply(lambda geom: transform(project, geom))
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\series.py", line 3194, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1472, in pandas._libs.lib.map_infer
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geoseries.py", line 288, in <lambda>
    result = self.apply(lambda geom: transform(project, geom))
  File "C:\Users\jewell\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\shapely\ops.py", line 221, in transform
    if geom.is_empty:
AttributeError: 'NoneType' object has no attribute 'is_empty'
```

What could be the explanation?

**To Reproduce**
1. Download the inputs (with default streets.shp)
[inputs.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4812778/inputs.zip)

2. Open in CEA and check if it works
3. Test replacing with _streets_singleparts.shp_ (do not forget to change the name!) : 
[streets_singleparts.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4812779/streets_singleparts.zip)

**Expected behaviour**
I expect the error not to occur

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA you are using: CEA 3.3

**Comment by AlexJew** [comment]
I have found the origin of the problem. It was due to an empty geometry in my _streets.shp_ file. Sorry ^^

**Comment by daren-thomas** [comment]
@AlexJew congratulations on fixing this!

**Comment by AlexJew** [comment]
Maybe it would be good to clarify the message printed, explaining that it probably comes from a feature with an empty geometry

**Comment by daren-thomas** [comment]
Good idea, I created issue #2785 with this suggestion.
