### ISSUE TITLE
CalledProcessError while running the radiation script

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2819]
**Describe the bug**
I am running the radiation script on the case study discussed in #2812. After solving the terrain issues, I managed to get the Daysim simulation running, but now I get the following error message:
```
Starting Daysim simulation starts for buildings [u'B444416']
Total number of sensors:  111
Transforming weather files to daysim format
Transforming radiance files to daysim format
Running command `radfiles2daysim "c:\users\assist~1\appdata\local\temp\temp667\temp667.hea" -g -m -d`
Writing radiance parameters
Executing hourly solar isolation calculation
Running command `gen_dc "c:\users\assist~1\appdata\local\temp\temp667\tmp\temp667temp.hea" -dir`
Running command `gen_dc "c:\users\assist~1\appdata\local\temp\temp667\tmp\temp667temp.hea" -dif`
Running command `gen_dc "c:\users\assist~1\appdata\local\temp\temp667\tmp\temp667temp.hea" -paste`
Traceback (most recent call last):
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 58, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 504, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, config.radiation)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 186, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, building_dict, locator, settings, max_global, weatherfile)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\daysim_main.py", line 209, in isolation_daysim
    rad.execute_ds_illum()
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 442, in execute_ds_illum
    self.run_cmd(command1)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 268, in run_cmd
    subprocess.check_call(cmd, cwd=cwd, stderr=subprocess.STDOUT, env=os.environ)
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ds_illum "c:\users\assist~1\appdata\local\temp\temp667\temp667.hea"' returned non-zero exit status 1

Running command `ds_illum "c:\users\assist~1\appdata\local\temp\temp667\temp667.hea"`
```

Since I am not familiar with Daysim, I am not sure what this error even means.

**To Reproduce**
1. [Download the case study](https://we.tl/t-hpeNyDI4jF)
2. Run the radiation script
3. See error

**Hardware:**
 - OS and version: Windows 10
 - CityEnergyAnalyst v3.7.0

Assigning @reyery since we have been discussing similar issues for the past few days, but feel free to reassign if you think there is a more appropriate candidate!

**Comment by shanshanhsieh** [comment]
we could find out more information by running command `ds_illum "c:\users\assist~1\appdata\local\temp\temp667\temp667.hea"`

**Comment by martin-mosteiro** [comment]
@shanshanhsieh thanks!

**Comment by martin-mosteiro** [comment]
This issue hasn't appeared again since, so I'm closing it
