### ISSUE TITLE
KeyError in Thermal network layout tool

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2855]
Attemped to run the thermal network layout tool on a case study created from scratch on CEA 3.13.0. The tool does not work at present due to a KeyError:
```
City Energy Analyst version 3.13.0
Running `cea network-layout` with the following parameters:
- general:scenario = C:\Users\Assistenz\Desktop\test\test_again
  (default: {general:project}\{general:scenario-name})
- network-layout:network-type = DH
  (default: DC)
- network-layout:connected-buildings = ['B1000', 'B1001', 'B1002', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011', 'B1012', 'B1013', 'B1014', 'B1015', 'B1016', 'B1017']
  (default: ['B1000', 'B1001', 'B1002', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011', 'B1012', 'B1013', 'B1014', 'B1015', 'B1016', 'B1017'])
- network-layout:pipe-diameter = 150
  (default: 150)
- network-layout:type-mat = T1
  (default: T1)
- network-layout:allow-looped-networks = False
  (default: False)
- network-layout:consider-only-buildings-with-demand = True
  (default: True)
Traceback (most recent call last):
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'FID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\technologies\network_layout\main.py", line 106, in main
    layout_network(network_layout, locator)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\technologies\network_layout\main.py", line 78, in layout_network
    disconnected_building_names)
  File "c:\users\assistenz\documents\cityenergyanalyst\cityenergyanalyst\cea\technologies\network_layout\steiner_spanning_tree.py", line 120, in calc_steiner_spanning_tree
    mst_nodes['Name'] = mst_nodes['FID'].apply(lambda x: "NODE" + str(x))
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 828, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Assistenz\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'FID'
```

**Comment by shanshanhsieh** [comment]
@martin-mosteiro  not sure if it is related, there is a known error with the precision and only a manual solution so far: see #2786

**Comment by daren-thomas** [comment]
@martin-mosteiro do you have a status update for the CEA planning session tomorrow?

**Comment by martin-mosteiro** [comment]
@daren-thomas As of right now, no – But I'm doing some testing right now and hopefully have an update by tomorrow!

**Comment by martin-mosteiro** [comment]
After repeating the steps I followed last time on the same area I analyzed back then (plus two others), I haven't been able to replicate the issue. So I'm closing it.

**Comment by Raummma97** [comment]
@martin-mosteiro  please can you tell me where is the steps you follow and solve this problem because I suffered from the same problem

**Comment by martin-mosteiro** [comment]
@Raummma97 To be honest, I don't really remember this issue. It's been so long, and it seems to have resolved itself. I suggest you create a new issue specifying the circumstances in which you got this error and any information necessary for us to try to replicate it.

**Comment by Raummma97** [comment]
@martin-mosteiro  I've already made an issue and I'm waiting for the solution ... thanks Martin
