### ISSUE TITLE
Having problem in 3.13.0 exe windows installation: No module named 'queue'

### ISSUE THREAD

**Issue by xiaoshir** [architecture-building-systems/CityEnergyAnalyst#2860]
Hi I'm trying to install 3.13.0 using the exe windows installer (Setup_CityEnergyAnalyst_3.13.0.exe) getting from [here](https://cityenergyanalyst.com/try-cea), but ran into an error in the end that says

```
(CEA) C:\Users\zhang_x\Documents\CityEnergyAnalyst>CALL "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe" -m pip install --force-reinstall --no-deps "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\cityenergyanalyst.tar.gz" 
Traceback (most recent call last):
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pip\__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 24, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 12, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pip\_internal\utils\logging.py", line 9, in <module>
    import logging.handlers
  File "C:\Users\zhang_x\Documents\CityEnergyAnalyst\Dependencies\Python\lib\logging\handlers.py", line 28, in <module>
    import queue
ModuleNotFoundError: No module named 'queue'
```

See also below for a screenshot. 
![image](https://user-images.githubusercontent.com/28433916/98545086-38011a80-2295-11eb-86b6-1fb28c4e5e3a.png)

Note that:
- I didn't check the box for installing the developer version 
- I have installed CEA before (but didn't use it much after opening it once, as it was not running for some reason)

I'm not sure if the above two points would play any role in successful installation of CEA, but I would like just to mention it in case they are relevant. 

My question is: what shall I do to be able to install CEA? 

Thanks.

**Comment by daren-thomas** [comment]
@xiaoshir you raise a good point: a previous installation of CEA actually might be the problem here. Mainly, because two different versions of Python are being installed in the same folder (`CityEnergyAnalyst/Dependencies/Python`).

I suggest you uninstall CEA. make sure the folder `C:\Users\{your-user-name}\Documents\CityEnergyAnalyst` is completely removed. Then try re-installing.

**Comment by daren-thomas** [comment]
@xiaoshir - did you get this to work? If not, please comment - we will otherwise close this issue (for now) tomorrow.
