### ISSUE TITLE
write the ReMaP_archetype_mapper

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2903]
continuing #2902, a script is needed to construct the input database according to the predefined data in #2902 and user inputs.

the users will only specify : 
1. district type (urban/sub-urban/rural), 
2. year (2040/2060), 
3. urban development scenario, and 
4. building property scenario

and the script will assign the corresponding building properties to buildings in the district.

**Comment by daren-thomas** [comment]
See comments in #2903 for implementation details...

@shanshanhsieh @nasty-bos: It's done! Check out: https://github.com/architecture-building-systems/cea-remap-ville-plugin

**Comment by nasty-bos** [comment]
@daren-thomas I get the following error message: 

```
Traceback (most recent call last):
  File "C:\Users\abosova\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-script.py", line 33, in <module>
    sys.exit(load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')())
  File "c:\users\abosova\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cli.py", line 72, in main
    script_module.main(config)
  File "c:\users\abosova\documents\cityenergyanalyst\cea-remap-ville-plugin\remap_ville_plugin\remap.py", line 18, in main
    cea.api.remap_copy_archetypes(config=config)
  File "c:\users\abosova\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\abosova\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    if list(cea_script.missing_input_files(config)):
  File "c:\users\abosova\documents\cityenergyanalyst\cityenergyanalyst\cea\scripts.py", line 77, in missing_input_files
    method_name, args = locator_spec[0], locator_spec[1:]
KeyError: 0

```

**Comment by daren-thomas** [comment]
@nasty-bos Oops, I'm very sorry. I made a mistake in the `scripts.yml` file. Please update your repository and try again :)

**Comment by nasty-bos** [comment]
@daren-thomas amazing, thanks, it works now! bravooo :)

**Comment by shanshanhsieh** [comment]
i also tried it out, super cool!!! thanks, @daren-thomas !
