### ISSUE TITLE
Validation checks in schemas from plugins

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2907]
**To Reproduce**
Open CEA and go to the Database editor

**Describe the bug**

Database Editor is not opening, error seems to be coming from glossary ("UNIT": cd["unit"])

![image](https://user-images.githubusercontent.com/50981039/103749234-373ff700-5040-11eb-9225-0f77fe5a322a.png)

error log:

[2021-01-06 16:45:49,114] ERROR in app: Exception on /api/glossary/ [GET]
Traceback (most recent call last):
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\glossary.py", line 63, in glossary_row
    "UNIT": cd["unit"],
KeyError: 'unit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router
    return original_handler(e)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\glossary.py", line 15, in get
    glossary = read_glossary_df(plugins=current_app.cea_config.plugins)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\glossary.py", line 45, in read_glossary_df
    rows.append(glossary_row(script, file_path, col, lm, cd, worksheet=""))
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\glossary.py", line 72, in glossary_row
    **locals()))
AttributeError: 'KeyError' object has no attribute 'message'

**Hardware (please complete the following information):**
 - Version of CEA you are using [v. 3.15]

**Comment by lguilhermers** [comment]
@reyery pointed to me that my schemas.yml had some fields missing the 'unit', and there is a validation that will check for those. After creating units for all fields on my plugin, the database editor worked again.
