### ISSUE TITLE
zone_helper not working outside Singapore

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2953]
**Describe the bug**
The zone_helper is working in Singapore but not in Zurich.

**To Reproduce**
1. open dashboard 
2. "create scenario" outside Singapore (e.g., Zurich)
3. See error

```
Traceback (most recent call last):
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\api\project.py", line 181, in post
    cea.api.zone_helper(config, scenario=new_scenario_path)
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 324, in main
    zone_helper(locator, config)
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 162, in zone_helper
    poly, zone_output_path)
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 274, in polygon_to_zone
    buildings_floors_below_ground, key="B")
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\zone_helper.py", line 122, in clean_attributes
    in_categories = shapefile['amenity'].isin(OSM_BUILDING_CATEGORIES.keys())
  File "C:\Users\shsieh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 828, in __getitem__
    result = super(GeoDataFrame, self).__getitem__(key)
  File "C:\Users\shsieh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\shsieh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'amenity'
```

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA you are using : 3.22 (master branch)

**Comment by martin-mosteiro** [comment]
@shanshanhsieh great catch, didn't notice that OSM shapefiles don't always have all the same column `list_of_columns` – there's actually a line in the `zone_helper` that checks for this (l. 109-116). Adding an `if` statement right before the line where the error happens should suffice ("if there's an amenity type and it's useful, use that as the category").

Unfortunately I can't test this at the moment – @shanshanhsieh could you maybe test whether the branch I created solves the issue?
