### ISSUE TITLE
xlrd does no longer support xlsx files

### ISSUE THREAD

**Issue by samfux84** [architecture-building-systems/CityEnergyAnalyst#2967]
**Describe the bug**

According to https://xlrd.readthedocs.io/en/latest/ the xlrd package does no longer support any other format than .xls and since the unittests of cea try to read an xlsx file with xlrd, it fails and throws an error:

```
ERROR: test_mixed_use_archetype_values (test_schedules.TestBuildingPreprocessing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/tests/test_schedules.py", line 31, in test_mixed_use_archetype_values
    calculated_results = calculate_mixed_use_archetype_values_results(locator).to_dict()
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/tests/test_schedules.py", line 88, in calculate_mixed_use_archetype_values_results
    occ_densities = pd.read_excel(locator.get_database_use_types_properties(), 'INTERNAL_LOADS').set_index('code')
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pandas/io/excel/_base.py", line 304, in read_excel
    io = ExcelFile(io, engine=engine)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
    super().__init__(filepath_or_buffer)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pandas/io/excel/_base.py", line 353, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pandas/io/excel/_xlrd.py", line 37, in load_workbook
    return open_workbook(filepath_or_buffer)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/xlrd/__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
```

Therefore I think you would need to use a different Python package to read xlsx files, for instance xlrd could be replaced with one of the following packages:

* openpyxl (https://openpyxl.readthedocs.io/en/stable/)
* xlwings (https://www.xlwings.org/)

**To Reproduce**

* Run "cea test" with a cea 3.11.0 installation using xlrd >=2

**Expected behaviour**
The xlsx file should be read without throwing an error message

**Screenshots**
no screenshot

**Hardware (please complete the following information):**
 - OS and version: CentOS 7.9
 - Version of CEA you are using: 3.11.0

**Comment by shanshanhsieh** [comment]
1. remove `xlrd` from the dependency
2. @lguilhermers will recommend one of the newer libraries to replace it
