### ISSUE TITLE
AttributeError: module 'pysal' has no attribute 'lib'

### ISSUE THREAD

**Issue by samfux84** [architecture-building-systems/CityEnergyAnalyst#2968]
**Describe the bug**
The pysal package has no attribute lib, therefore the unittest of cea fail

```
======================================================================
ERROR: setUpClass (test_calc_thermal_loads.TestCalcThermalLoads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/tests/test_calc_thermal_loads.py", line 44, in setUpClass
    cea.datamanagement.archetypes_mapper.archetypes_mapper(cls.locator, True, True, True, True, True, True,
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/datamanagement/archetypes_mapper.py", line 71, in archetypes_mapper
    building_typology_df = dbf_to_dataframe(locator.get_building_typology())
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/utilities/dbf.py", line 66, in dbf_to_dataframe
    dbf = pysal.lib.io.open(dbf_path)
AttributeError: module 'pysal' has no attribute 'lib'

======================================================================
ERROR: test_roundtrip (test_dbf.TestDbf)
Make sure the roundtrip df -> dbf -> df keeps the data intact.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/tests/test_dbf.py", line 20, in test_roundtrip
    dbf.dataframe_to_dbf(df, dbf_path)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/utilities/dbf.py", line 56, in dataframe_to_dbf
    dbf = pysal.lib.io.open(dbf_path, 'w', 'dbf')
AttributeError: module 'pysal' has no attribute 'lib'
```

**To Reproduce**
1. run "cea test" with version 3.11.0

**Expected behaviour**
No error should be thrown

**Screenshots**
no screenshot

**Hardware (please complete the following information):**
 - OS and version: CentOS 7.9
 - Version of CEA you are using: 3.11.0

**Comment by shanshanhsieh** [comment]
closing this issue as it cannot be reproduced in v3.24
