### ISSUE TITLE
MoudleNotFoundError: No module named 'osmnx.footprints'

### ISSUE THREAD

**Issue by samfux84** [architecture-building-systems/CityEnergyAnalyst#2969]
**Describe the bug**
The package osmnx has no module footprints, so you cannot import it

```
======================================================================
ERROR: test_inputs_setup_workflow (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_inputs_setup_workflow
Traceback (most recent call last):
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/tests/test_inputs_setup_workflow.py", line 6, in <module>
    from cea.datamanagement import zone_helper, surroundings_helper, terrain_helper, streets_helper, data_initializer, \
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/cea/datamanagement/zone_helper.py", line 10, in <module>
    import osmnx.footprints
ModuleNotFoundError: No module named 'osmnx.footprints'
```

**To Reproduce**
1. run "cea test" with version 3.11.0

**Expected behaviour**
No error should be thrown

**Screenshots**
no screenshot

**Hardware (please complete the following information):**
 - OS and version: CentOS 7.9
 - Version of CEA you are using: 3.11.0

**Comment by shanshanhsieh** [comment]
closing this issue as it cannot be reproduced in v3.24
