### ISSUE TITLE
Create release for V3.24

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#2975]

**Comment by shanshanhsieh** [comment]
the step at conda-pack is not passing, @daren-thomas any pointer?

```
CONDA-PACK to Dependencies folder: cea-3.24.0
RUN: c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\dev\conda.bat conda-pack --name cea-3.24.0 --output c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\setup\Dependencies\Python.tar --n-threads -1 --force 'conda-pack' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\shsieh\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts\cea-dev-script.py", line 33, in <module>
    sys.exit(load_entry_point('cityenergyanalyst', 'console_scripts', 'cea-dev')())
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\cli\cea_dev.py", line 77, in main
    script_module.main(config)
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\dev\build.py", line 43, in main
    conda_pack(config, env_name, repo_folder)
  File "c:\users\shsieh\documents\cityenergyanalyst\cityenergyanalyst\cea\dev\build.py", line 115, in conda_pack
    subprocess.run(command, capture_output=False, check=True, env=get_env(config, "base"), shell=True)
  File "C:\Users\shsieh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['c:\\users\\shsieh\\documents\\cityenergyanalyst\\cityenergyanalyst\\cea\\dev\\conda.bat', 'conda-pack', '--name', 'cea-3.24.0', '--output', 'c:\\users\\shsieh\\documents\\cityenergyanalyst\\cityenergyanalyst\\setup\\Dependencies\\Python.tar', '--n-threads', '-1', '--force']' returned non-zero exit status 1.
```

**Comment by shanshanhsieh** [comment]
thanks @daren-thomas , i must have lost the package after installing the new cea...
adding this to the documentation!
