### ISSUE TITLE
solar radiation error (subprocess error) in user defined geometry

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2983]
**Describe the bug**
I have created an user defined geometry (thanks @nasty-bos for the blog post \o/) but I am getting errors when running solar radiation. Possibly it is related with the user defined geometry (maybe I missed something), since it is running on other case studies (from open street maps).
I have attached my case study here (https://we.tl/t-KymZyoewOE).

**To Reproduce**
1. Download case study
2. Run Solar Radiation
3. See error

```
Generating geometry for surrounding buildings
Generating geometry for buildings in the zone of analysis
Using 3 CPU's
Generating geometry for building 1 completed out of 1
Creating radiance material file
Creating radiance geometry file
Converting files for DAYSIM
Transforming weather files to daysim format
Running command `epw2wea "C:\CEA\CS2_Sensitivity\sensitivity_baseline\inputs\weather\weather.epw" "C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\common_inputs\weather_60min.wea"`
Transforming radiance files to daysim format
Running command `radfiles2daysim "C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\common_inputs\rad2daysim.hea" -g -m -d`
Creating daysim project in: C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\projects\chunk_0\
Calculating and sending sensor points
Traceback (most recent call last):
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 255, in main
    num_processes=config.get_number_of_processes())
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiation_main.py", line 84, in radiation_singleprocessing
    max_global, weatherfile, geometry_pickle_dir)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\daysim_main.py", line 188, in isolation_daysim
    daysim_project.execute_ds_illum()
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiance.py", line 326, in execute_ds_illum
    CEADaySim.run_cmd(command1)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\radiance.py", line 82, in run_cmd
    subprocess.check_call(cmd, cwd=cwd, stderr=subprocess.STDOUT, env=os.environ)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ds_illum "C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea"' returned non-zero exit status 1.

Starting Daysim simulation for buildings: ['B1001']
Total number of sensors:  362
Writing radiance parameters
Executing hourly solar isolation calculation
Running command `gen_dc "C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea" -dir`
Running command `gen_dc "C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea" -dif`
Running command `gen_dc "C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea" -paste`
Running command `ds_illum "C:\Users\LUIS1.SAN\AppData\Local\Temp\cea_radiation\projects\chunk_0\chunk_0.hea"`
```

**Comment by shanshanhsieh** [comment]
@shanshanhsieh will check the case study and see if the error is reproducible

**Comment by shanshanhsieh** [comment]
yep @lguilhermers , i got exactly the same error message.

**Comment by lguilhermers** [comment]
Rookie mistake: forgot to remove the attributes that do not exist in the surroundings (height_bg and floors_bg).
After fixing the surroundings attributes (took one generated by CEA as a base to be sure they were matching), it worked.
