### ISSUE TITLE
Error when building energy demand

### ISSUE THREAD

**Issue by my-hub30** [architecture-building-systems/CityEnergyAnalyst#3005]
Hello, I'm trying to calculate the hourly energy demand but stuck with errors. I'd appreciate it if someone would help me.
I ran all scripts in Data Management and ran 'Building solar radiation' and 'Building Schedules' in Demand Forecasting. Everything goes well, but when I ran 'Energy Demand', I have this error:

FileNotFoundError: [Errno 2] File C:\Users\e0546183\AppData\Local\Temp\B1000T.csv does not exist: 'C:\\Users\\e0546183\\AppData\\Local\\Temp\\B1000T.csv'

However, my project addreass is located at ''C:\Users\e0546183\Desktop\CEA_proj''.

BTW, I find all files in my file, no 'B1000T.csv' file exists.

Thx!

The whole error is shown as follows:
City Energy Analyst version 3.24.0
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\e0546183\Desktop\CEA_proj\data
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = True
  (default: False)
- demand:buildings = ['B1000', 'B1001']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
Running demand calculation for scenario C:\Users\e0546183\Desktop\CEA_proj\data
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand in debug mode: Instant visualization of tsd activated.
Running demand calculation with write detailed output
Running demand calculation for the following buildings=['B1000', 'B1001']
read input files
done
Using 5 CPU's
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1001 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1000 to .xls file.
Building No. 1 completed out of 2: B1000
Building No. 2 completed out of 2: B1001
Traceback (most recent call last):
  File "c:\users\e0546183\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\e0546183\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\e0546183\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\e0546183\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "c:\users\e0546183\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 157, in main
    demand_calculation(locator=locator, config=config)
  File "c:\users\e0546183\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 134, in demand_calculation
    writer_totals.write_to_csv(building_names, locator)
  File "c:\users\e0546183\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_writers.py", line 168, in write_to_csv
    df = pd.read_csv(temporary_file)
  File "C:\Users\e0546183\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\e0546183\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\e0546183\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\e0546183\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\e0546183\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File C:\Users\e0546183\AppData\Local\Temp\B1000T.csv does not exist: 'C:\\Users\\e0546183\\AppData\\Local\\Temp\\B1000T.csv'

**Comment by shanshanhsieh** [comment]
@my-hub30, could you please upload the files so i can re-create the error. thanks!

**Comment by my-hub30** [comment]
Hello, Shanshan, I reinstall CEA and it can run now. 
Seems some errors in the eraly version.
Thx for your reply Shanshan!
