### ISSUE TITLE
Error in Building Energy demand when setting general:debug = True

### ISSUE THREAD

**Issue by electron1406** [architecture-building-systems/CityEnergyAnalyst#3101]
**Describe the bug**
After following every single steps when I Run Script at the **step 8 Demand forecasting
Building Energy demand - Calculate the Demand** I get an error.

**To Reproduce**
1. I open a previous project
2. Click on **data management** and then I prior run and after I received the message of confirmation (success) I **save to config** each one of the following 'Archetypes manager; Weather helper; Surroundings helper; Terrain helper; Streets helper.' It is worth mentioning that none of them has failed
3. I scrolled down to **Demand forecasting** then I clicked on running script **building solar irradiation** it took a long time but it was successfully created and also **saved to config**, later I ran the script for **Building Schedules** , I **saved to config**, finally I ran **Building energy demand** and hereafter a while sent me an error message.
```
City Energy Analyst version 3.26.0
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\tonycastillo\Zorrotzaurre\2020
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = True
  (default: False)
- demand:buildings = ['B1000', 'B1001', 'B1002', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011', 'B1012', 'B1013', 'B1014', 'B1015', 'B1016', 'B1017', 'B1018', 'B1019', 'B1020', 'B1021', 'B1022', 'B1023', 'B1024', 'B1025', 'B1026', 'B1027', 'B1028']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = True
  (default: True)
Running demand calculation for scenario C:\Users\tonycastillo\Zorrotzaurre\2020
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand in debug mode: Instant visualization of tsd activated.
Running demand calculation with write detailed output
Running demand calculation for the following buildings=['B1000', 'B1001', 'B1002', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011', 'B1012', 'B1013', 'B1014', 'B1015', 'B1016', 'B1017', 'B1018', 'B1019', 'B1020', 'B1021', 'B1022', 'B1023', 'B1024', 'B1025', 'B1026', 'B1027', 'B1028']
read input files
done
Using 3 CPU's
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1006 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1003 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1000 to .xls file.
Building No. 1 completed out of 29: B1006
Building No. 2 completed out of 29: B1000
Building No. 3 completed out of 29: B1003
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1001 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1007 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1004 to .xls file.
Building No. 4 completed out of 29: B1007
Building No. 5 completed out of 29: B1001
Building No. 6 completed out of 29: B1004
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1008 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1002 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1005 to .xls file.
Building No. 7 completed out of 29: B1008
Building No. 8 completed out of 29: B1002
Building No. 9 completed out of 29: B1005
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1009 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1012 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1015 to .xls file.
Building No. 10 completed out of 29: B1009
Building No. 11 completed out of 29: B1012
Building No. 12 completed out of 29: B1015
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1010 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1013 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1016 to .xls file.
Building No. 13 completed out of 29: B1010
Building No. 14 completed out of 29: B1013
Building No. 15 completed out of 29: B1016
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1011 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1014 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1017 to .xls file.
Building No. 16 completed out of 29: B1011
Building No. 17 completed out of 29: B1014
Building No. 18 completed out of 29: B1017
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1018 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1021 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1024 to .xls file.
Building No. 19 completed out of 29: B1018
Building No. 20 completed out of 29: B1021
Building No. 21 completed out of 29: B1024
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1019 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1022 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1025 to .xls file.
Building No. 22 completed out of 29: B1019
Building No. 23 completed out of 29: B1022
Building No. 24 completed out of 29: B1025
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1020 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1023 to .xls file.
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1026 to .xls file.
Building No. 25 completed out of 29: B1020
Building No. 26 completed out of 29: B1023
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1027 to .xls file.
Building No. 27 completed out of 29: B1026
Building No. 28 completed out of 29: B1027
Creating instant plotly visualizations of demand variable time series.
Behavior can be changed in cea.utilities.reporting code.
Writing detailed demand results of B1028 to .xls file.
Building No. 29 completed out of 29: B1028Traceback (most recent call last):
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 59, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 37, in script_runner
    script_module.main(config)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_main.py", line 157, in main
    demand_calculation(locator=locator, config=config)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_main.py", line 134, in demand_calculation
    writer_totals.write_to_csv(building_names, locator)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\demand\demand_writers.py", line 170, in write_to_csv
    df = df.append(pd.read_csv(temporary_file), ignore_index=True)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 51, i
![error CEA step 8](https://user-images.githubusercontent.com/70798389/157222310-9c1bb2bd-1da8-4c51-bf6e-7e5a693b9585.png)
n __init__
    self._open_handles(src, kwds)
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\parsers\base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "C:\Users\tonycastillo\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\TONYCA~1\\AppData\\Local\\Temp\\B1015T.csv'
```

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by shanshanhsieh** [comment]
@electron1406, could you try running the script again with `general:debug = False`? thanks!

**Comment by shanshanhsieh** [comment]
hi @electron1406,

When setting `general:debug = True`, it is currently not possible to get annual summary of the whole district.
We are working on fixing it now.
However, the outputs for individual buildings should be available in `C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\demand` folder.

**Comment by electron1406** [comment]
Dear @shanshanhsieh.

I saw the outputs for the buildings in C:\Users\tonycastillo\Zorrotzaurre\2020\outputs\data\demand folder (by the way, I have noticed that Solar Irradiation is NaN).  Nonetheless, I do not know how should I run the script with **general:debug = False?** since I use the CEA Dashboard, and maybe it is for CEA Console, is not it? do you mind giving me more hints to carry it out? please.
Best regards
