### ISSUE TITLE
Error running demand: calc_Eauxf_fw TypeError: can't convert complex to float

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3104]
**Describe the bug**
The error was found while running the stochastic scenario generator (#2998 ).  Previously mentioned in (#3067) and transfered to here.
A scenario where this error appear can be found here:
https://www.dropbox.com/s/ujlgjcgozxqyyj4/err_convert_complex_to_float.rar?dl=0

**To Reproduce**
1. Download scenario above (not sure how to reproduce the error in other scenarios)
2. Run demand simulation
3. See error

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 131, in __apply_func_with_worker_stream
    result = func(*args)
  File "C:\Users\luis.santos\Documents\GitHub\stochastic_scenario_generator\data_generation.py", line 164, in stochastic_scenario_generator
    demand_main.demand_calculation(locator, config)  # runs demand simulation
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 130, in demand_calculation
    repeat(debug, n))
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 149, in wrapper
    result = func(*instance_args)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\thermal_loads.py", line 140, in calc_thermal_loads
    tsd = electrical_loads.calc_Eaux_fw(tsd, bpr, schedules)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\electrical_loads.py", line 143, in calc_Eaux_fw
    tsd['Eaux_fw'] = np.vectorize(calc_Eauxf_fw)(tsd['vfw_m3perh'], deltaP_kPa, b)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2195, in _vectorize_call
    res = array(outputs, copy=False, subok=True, dtype=otypes[0])
TypeError: can't convert complex to float
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/luis.santos/Documents/GitHub/stochastic_scenario_generator/data_generation.py", line 323, in <module>
    main(cea.config.Configuration())
  File "C:/Users/luis.santos/Documents/GitHub/stochastic_scenario_generator/data_generation.py", line 243, in main
    list_of_dataframe_with_instances)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 96, in wrapper
    result = map_result.get()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
TypeError: can't convert complex to float

Process finished with exit code 1
```

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using  v. 3.26

**Comment by shanshanhsieh** [comment]
hey @lguilhermers ,
the floor height of this building is 2.2m, is that intended?
if yes, I will update the script to allow this floor height
