### ISSUE TITLE
OverflowError: math range error in thermal loads calculation

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3121]
**Describe the bug**
The error was previously mentioned in #3067, while devoling a stochastic scenario generator for CEA (#2998).

Some particlar numbers of `theta ` would be problematic while trying to solve
`p_sat_int = 611.2 * math.exp(17.62 * theta / (243.12 + theta))`.
This is probably due to a very large number of decimals and doesn't fit into a double (as found here: https://stackoverflow.com/questions/4050907/python-overflowerror-math-range-error).

**To Reproduce**
1. Download [here](https://www.dropbox.com/s/j8e7kjxf6motzxl/err_overflow_mathrange.rar?dl=0) the scenario where error appears.
2. Run demand simulation
3. See error

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 131, in __apply_func_with_worker_stream
    result = func(*args)
  File "C:\Users\luis.santos\Documents\GitHub\stochastic_scenario_generator\data_generation.py", line 170, in stochastic_scenario_generator
    demand_main.demand_calculation(locator, config)  # runs demand simulation
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 130, in demand_calculation
    repeat(debug, n))
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 149, in wrapper
    result = func(*instance_args)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\thermal_loads.py", line 122, in calc_thermal_loads
    use_dynamic_infiltration_calculation, config)  # end-use demand latent and sensible + ventilation
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\thermal_loads.py", line 340, in calc_Qhs_Qcs
    hourly_procedure_heating_cooling_system_load.calc_heating_cooling_loads(bpr, tsd, t, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\hourly_procedure_heating_cooling_system_load.py", line 99, in calc_heating_cooling_loads
    rc_model_temperatures = calc_cool_loads_central_ac(bpr, t, tsd, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\hourly_procedure_heating_cooling_system_load.py", line 472, in calc_cool_loads_central_ac
    g_dhu_demand_aru = latent_loads.calc_dehumidification_moisture_load(bpr, tsd, t)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\latent_loads.py", line 97, in calc_dehumidification_moisture_load
    x_set_max = calc_max_moisture_set_point(bpr, tsd, t)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\latent_loads.py", line 168, in calc_max_moisture_set_point
    p_sat_int = calc_saturation_pressure(t_int)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\latent_loads.py", line 188, in calc_saturation_pressure
    p_sat_int = 611.2 * math.exp(17.62 * theta / (243.12 + theta))
OverflowError: math range error
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/luis.santos/Documents/GitHub/stochastic_scenario_generator/data_generation.py", line 334, in <module>
    main(cea.config.Configuration())
  File "C:/Users/luis.santos/Documents/GitHub/stochastic_scenario_generator/data_generation.py", line 252, in main
    list_of_dataframe_with_instances)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 96, in wrapper
    result = map_result.get()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
OverflowError: math range error

Process finished with exit code 1
```

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by lguilhermers** [comment]
Following one comment from the stack overlow above, changing from `math.exp` to `np.exp` seems to solve the issue, as "Numpy handles overflows more gracefully".

Even with the error gone, maybe would still be appropriate to look for the values being produced and see if they are making sense, but this is a bit beyond my capabilities and resources at the moment.
