### ISSUE TITLE
Flask dependency error after creating conda environment

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#3138]
Creating a new conda environment for cea now returns this error when running `cea dashboard`

```
(cea) ➜  CityEnergyAnalyst git:(master) cea dashboard
City Energy Analyst version 3.28.0
Running `cea dashboard` with the following parameters:
- general:debug = False
  (default: False)
- server:project-root = /Users/reynoldmok/Documents
  (default: /Users/reynoldmok/Documents/GitHub/CityEnergyAnalyst)
- server:protocol = http
  (default: http)
- server:host = 127.0.0.1
  (default: 127.0.0.1)
- server:port = 5050
  (default: 5050)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cea/bin/cea", line 33, in <module>
    sys.exit(load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')())
  File "/Users/reynoldmok/Documents/GitHub/CityEnergyAnalyst/cea/interfaces/cli/cli.py", line 70, in main
    script_module = importlib.import_module(cea_script.module)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cea/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/reynoldmok/Documents/GitHub/CityEnergyAnalyst/cea/interfaces/dashboard/dashboard.py", line 1, in <module>
    from flask import Flask
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/cea/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/opt/homebrew/Caskroom/mambaforge/base/envs/cea/lib/python3.8/site-packages/jinja2/__init__.py)
```
I created it using conda on mac, so I'm not sure if this applies to windows as well. But I would think it does.

This is mainly caused by a recent update of one of the dependencies of Flask.
https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0 [Released 2022-03-24]

There are 2 ways to solve this:
1) Upgrade Flask to version 2
- Newer versions of Flask do not use that particular module that is causing the error. However this would require rewriting some of the code related to Flask since (if I recall correctly) one of the related Flask modules that we use, flask-restplus, only supports Flask version 1

2) Tag `jinja2<3.1.0` in dependencies
- Easiest way to do it

**Comment by reyery** [comment]
Related issue https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/3008
