### ISSUE TITLE
Error when parsing building year value in zone helper

### ISSUE THREAD

**Issue by Iskenderzeynalov** [architecture-building-systems/CityEnergyAnalyst#3183]
Trying to create a basic scenario of Linz city but receive an error message saying: Error Message:
zone_helper: ('We could not cast the value', '799').

My selected region is 98 km squared.

Any suggestions?
![Capture](https://user-images.githubusercontent.com/107115308/172604742-dbd5755a-933f-4d96-abc4-b169f5678f69.PNG)

**Comment by reyery** [comment]
@Iskenderzeynalov, there seems to be a bug where the script did not parse the building year correctly and I have just made a fix for it. 

You could try installing the fix by entering this in the CEA console
```bash
pip install git+https://github.com/architecture-building-systems/CityEnergyAnalyst.git
```

Let me know if it works

**Comment by Iskenderzeynalov** [comment]
> ```shell
> pip install git+https://github.com/architecture-building-systems/CityEnergyAnalyst.git
> ```



> @Iskenderzeynalov, there seems to be a bug where the script did not parse the building year correctly and I have just made a fix for it.
> 
> You could try installing the fix by entering this in the CEA console
> 
> ```shell
> pip install git+https://github.com/architecture-building-systems/CityEnergyAnalyst.git
> ```
> 
> Let me know if it works
![second](https://user-images.githubusercontent.com/107115308/173298176-31a30635-8b78-4dd6-9cdc-819fc69f9bb1.PNG)

I installed the fix successfully in the console but I still receive an error.

**Comment by reyery** [comment]
Seems like a different bug now. Would you be able to show what is within the details portion of the error?

**Comment by Iskenderzeynalov** [comment]
Details:
Traceback (most recent call last):
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 176, in post
    cea.api.zone_helper(config)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\zone_helper.py", line 333, in main
    zone_helper(locator, config)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\zone_helper.py", line 165, in zone_helper
    calculate_typology_file(locator, zone_df, year_construction, occupancy_type, typology_output_path)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\zone_helper.py", line 189, in calculate_typology_file
    typology_df['STANDARD'] = calc_category(standard_database, typology_df['YEAR'].values)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\zone_helper.py", line 172, in calc_category
    category = np.vectorize(category_assignment)(year_array)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\numpy\lib\function_base.py", line 2192, in _vectorize_call
    outputs = ufunc(*inputs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\zone_helper.py", line 170, in category_assignment
    return (standard_DB[(standard_DB['YEAR_START'] <= year) & (standard_DB['YEAR_END'] >= year)].STANDARD.values[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 186, in post
    raise Exception(f'{tool}_helper: {e}') from e
Exception: zone_helper: index 0 is out of bounds for axis 0 with size 0

**Comment by reyery** [comment]
I have merged a new fix. Try running this again

```
pip install git+https://github.com/architecture-building-systems/CityEnergyAnalyst.git
```

**Comment by reyery** [comment]
It seems like it is still running the old code. The line causing the issue has been changed in the `main` branch. Did you run that command in the CEA console? It should install the new version.

**Comment by Iskenderzeynalov** [comment]
I ran the command in the console. But it showed the same problem

**Comment by reyery** [comment]
That's strange. The only other way I can think to update your CEA is to manually clone the repository to your machine or download the zip from https://github.com/architecture-building-systems/CityEnergyAnalyst/archive/refs/heads/master.zip (and extract it), then run `pip install PATH_TO_CEA` in the CEA console, where `PATH_TO_CEA` is the path to where that local repository is.

**Comment by Iskenderzeynalov** [comment]
![pip](https://user-images.githubusercontent.com/107115308/175241336-0a73674b-d62b-4890-9532-983f66822ed5.PNG)
I tried but it gives me some error. What am I doing wrong?

**Comment by reyery** [comment]
Did you download and extract from https://github.com/architecture-building-systems/CityEnergyAnalyst/archive/refs/heads/master.zip ?
if the extracted folder is in `C:\Users\user\Downloads\CityEnergyAnalyst-master`
then run `pip install C:\Users\user\Downloads\CityEnergyAnalyst-master`

**Comment by Iskenderzeynalov** [comment]
So I did all that and managed to download new version and everything worked when  I did a rough drawing of the region, but now I made the lines more precise and I received another error:

Traceback (most recent call last):
  File "fiona\ogrext.pyx", line 1133, in fiona.ogrext.WritingSession.start
  File "fiona\_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_AppDefinedError: Failed to create file C:\Users\iskan\AppData\Local\Temp\tmp4ihyaw5z\temp_scenario\inputs\networks\streets.shp: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 180, in post
    cea.api.streets_helper(config)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\streets_helper.py", line 92, in main
    geometry_extractor_osm(locator, config)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\streets_helper.py", line 78, in geometry_extractor_osm
    data[['geometry']].to_file(shapefile_out_path)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 1114, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\io\file.py", line 393, in _to_file
    with fiona.open(
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\fiona\env.py", line 408, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\fiona\__init__.py", line 272, in open
    c = Collection(path, mode, crs=crs, driver=driver, schema=this_schema,
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\fiona\collection.py", line 165, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 1141, in fiona.ogrext.WritingSession.start
fiona.errors.DriverIOError: Failed to create file C:\Users\iskan\AppData\Local\Temp\tmp4ihyaw5z\temp_scenario\inputs\networks\streets.shp: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\iskan\OneDrive\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 186, in post
    raise Exception(f'{tool}_helper: {e}') from e
Exception: streets_helper: Failed to create file C:\Users\iskan\AppData\Local\Temp\tmp4ihyaw5z\temp_scenario\inputs\networks\streets.shp: No such file or directory

**Comment by Iskenderzeynalov** [comment]
So should I run in the Console each of them one by one?
