### ISSUE TITLE
Bug report - Simulation

### ISSUE THREAD

**Issue by IngridMorais30** [architecture-building-systems/CityEnergyAnalyst#3292]
Error Message:
data_initializer: [Errno 22] Invalid argument

Traceback (most recent call last):
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 133, in post
    cea.api.data_initializer(config, databases_path=databases_path)
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 32, in script_runner
    cea_script.print_script_configuration(config)
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\scripts.py", line 40, in print_script_configuration
    print('City Energy Analyst version %s' % cea.__version__)
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\ingri\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 135, in post
    raise Exception(f'data_initializer: {e}') from e
Exception: data_initializer: [Errno 22] Invalid argument

**Comment by lguilhermers** [comment]
Hi Ingrid,
Can you provide a little bit more context to your issue?
When did the error appear? Were you able to run any successful scenarios using CEA?

**Comment by lguilhermers** [comment]
No worries. We have some tutorials in the CEA website that helps in the very first steps, but it seems you are further from that already! Good luck!
