### ISSUE TITLE
Optimization Supply System Part I (decentralized) - IndexError : single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by AfonsoGoncalves888** [architecture-building-systems/CityEnergyAnalyst#3343]
**Describe the bug**
There is an error when trying to run (either in CEA Dashboard and the CEA Console) the Optimization Supply System Part I (decentralized) in CEA 3.33.0 

**To Reproduce**
1. Lauch a scenario
2. Run **Data Management > Demand Forecasting > Energy Potentials** (Photovoltaic panels & Solar
collectors)
3. Run **Optimization Supply System Part I (decentralized)**

**Error Message**

Traceback (most recent call last):
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 131, in __apply_func_with_worker_stream
    result = func(*args)
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\optimization\preprocessing\decentralized_buildings_heating.py", line 222, in disconnected_heating_for_building
    Capex_a_FC_USD, Opex_fixed_FC_USD, Capex_FC_USD = FC.calc_Cinv_FC(Qnom_W, supply_systems.FC)
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\technologies\cogeneration.py", line 508, in calc_Cinv_FC
    Inv_a = FC_cost_data.iloc[0]['a']
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\optimization\preprocessing\decentralized_building_main.py", line 56, in main
    disconnected_building_main(locator=locator,  total_demand=total_demand,
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\optimization\preprocessing\decentralized_building_main.py", line 37, in disconnected_building_main
    decentralized_buildings_heating.disconnected_buildings_heating_main(locator, total_demand,
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\optimization\preprocessing\decentralized_buildings_heating.py", line 59, in disconnected_buildings_heating_main
    cea.utilities.parallel.vectorize(disconnected_heating_for_building, config.get_number_of_processes())(
  File "c:\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 96, in wrapper
    result = map_result.get()
  File "C:\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
IndexError: single positional indexer is out-of-bounds

**Hardware (please complete the following information):**
 - Windows 10
 - Version of CEA v. 3.33.0

**Comment by shizhongming** [comment]
@AfonsoGoncalves888 
Did you encounter this error in another scenario?
