### ISSUE TITLE
error when running the Building Solar radiation

### ISSUE THREAD

**Issue by chun533** [architecture-building-systems/CityEnergyAnalyst#3358]
When I running the Building Solar radiation, the error came out.
The information below is from 'more info' box.

Traceback (most recent call last):
  File "c:\users\melod\onedrive\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\melod\onedrive\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\melod\onedrive\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\melod\onedrive\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 65, in __getattribute__
    self._runner = script_wrapper(self._cea_script)
  File "c:\users\melod\onedrive\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 16, in script_wrapper
    script_module = importlib.import_module(module_path)
  File "C:\Users\melod\OneDrive\CityEnergyAnalyst\Dependencies\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\melod\onedrive\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\main.py", line 17, in <module>
    from cea.resources.radiation import daysim, geometry_generator
  File "c:\users\melod\onedrive\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation\daysim.py", line 21, in <module>
    from pyarrow import feather
ModuleNotFoundEr

I draw the polygon from osm, and had already completed to run Archetypes Mapper and weather helper. 
When doing the third job 'building solar radiation',  it failed.

windows 10
CEA 3.33.0

Thank you

**Comment by shizhongming** [comment]
Hi @chun533 
We have circulated a CEA newsletter including a solution to this error.

Please use the CEA Console and run:
`
python -m pip install pyarrow
`

**Comment by YuchunSu** [comment]
The problem solved~~Thank you!!
