### ISSUE TITLE
`archetypes_mapper`: "ValueError: The truth value of a Series is ambiguous"

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#3363]
Some times `archetypes_mapper` would throw this error.

```
Traceback (most recent call last):
  File "/mnt/storage/staging/datastore-2/proc-repositories/3547284d15c4d062d9534fee9e67fdecfa12ab190832d996867c4117c232cd04/dcn-cea/processor_sim/CityEnergyAnalyst/cea/datamanagement/archetypes_mapper.py", line 412, in main
    archetypes_mapper(locator=locator,
  File "/mnt/storage/staging/datastore-2/proc-repositories/3547284d15c4d062d9534fee9e67fdecfa12ab190832d996867c4117c232cd04/dcn-cea/processor_sim/CityEnergyAnalyst/cea/datamanagement/archetypes_mapper.py", line 100, in archetypes_mapper
    calc_mixed_schedule(locator, building_typology_df, buildings)
  File "/mnt/storage/staging/datastore-2/proc-repositories/3547284d15c4d062d9534fee9e67fdecfa12ab190832d996867c4117c232cd04/dcn-cea/processor_sim/CityEnergyAnalyst/cea/datamanagement/schedule_helper.py", line 77, in calc_mixed_schedule
    schedule_new_data, schedule_complementary_data = calc_single_mixed_schedule(list_uses, occupant_densities, building_typology_df, internal_loads, building, schedule_data_all_uses, list_var_names, list_var_values, metadata)
  File "/mnt/storage/staging/datastore-2/proc-repositories/3547284d15c4d062d9534fee9e67fdecfa12ab190832d996867c4117c232cd04/dcn-cea/processor_sim/CityEnergyAnalyst/cea/datamanagement/schedule_helper.py", line 110, in calc_single_mixed_schedule
    [np.array(schedule_data_all_uses.schedule_complementary_data[use]['MONTHLY_MULTIPLIER'])
  File "/mnt/storage/staging/datastore-2/proc-repositories/3547284d15c4d062d9534fee9e67fdecfa12ab190832d996867c4117c232cd04/dcn-cea/processor_sim/CityEnergyAnalyst/cea/datamanagement/schedule_helper.py", line 110, in <listcomp>
    [np.array(schedule_data_all_uses.schedule_complementary_data[use]['MONTHLY_MULTIPLIER'])
  File "/mnt/storage/staging/datastore-2/proc-repositories/3547284d15c4d062d9534fee9e67fdecfa12ab190832d996867c4117c232cd04/dcn-cea/processor_sim/micromamba/envs/duct-cea/lib/python3.8/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

It could be due to duplicated building names.

**Comment by shizhongming** [comment]
Maybe we can include a screening script of duplicated building names before executing `achetypes_mapper`
The screening script could check: for duplicates, building height and floor numbers that don't make sense, etc.
