### ISSUE TITLE
Problems occuring simulating energy demand

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3477]
The project of Issue #3469 now produces some other problems. 
Unfortunatly, I still cannot see the database in GUI. 
I can simulate solar radiation as well as occupancy. 
Problems occur simulating the energys demand: 

Job Output for 10 - demand
City Energy Analyst version 3.35.1
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\Geske\Desktop\CEA-Dateien\wise21
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- demand:buildings = ['C004', 'C007', 'C009', 'C010', 'C0135', 'C09A', 'C09B', 'C11A1', 'C11A2', 'C11B', 'C11C1', 'C11C2', 'C13A1', 'C13A2', 'C13B1', 'C13B2', 'C13C1', 'C13C2', 'C13D1']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = True
  (default: True)
Running demand calculation for scenario C:\Users\Geske\Desktop\CEA-Dateien\wise21
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation for the following buildings=['C004', 'C007', 'C009', 'C010', 'C0135', 'C09A', 'C09B', 'C11A1', 'C11A2', 'C11B', 'C11C1', 'C11C2', 'C13A1', 'C13A2', 'C13B1', 'C13B2', 'C13C1', 'C13C2', 'C13D1']
read input files
Traceback (most recent call last):
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\demand_main.py", line 145, in main
    demand_calculation(locator=locator, config=config)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\demand_main.py", line 82, in demand_calculation
    building_properties = BuildingProperties(locator, weather_data, building_names)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\building_properties.py", line 79, in __init__
    prop_HVAC_result = get_properties_technical_systems(locator, prop_hvac).set_index('Name')
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\building_properties.py", line 750, in get_properties_technical_systems
    on='Name').merge(df_emission_dhw[fields_emission_dhw],
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\Geske\Desktop\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\indexes\base.py", line 5941, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['class_dhw'] not in index"

**Comment by ShiZhongming** [comment]
Hi @Mar-Ges 

This is a known/expected error. We have included the solution to this error in the last CEA Newsletter.
If you are using a CEA file that worked for older CEA versions, you need to make the following updates on your database to make it work for CEA v.3.35.0 or later.

- Nagivate to CEA File > technology > assemblies > HVAC.xlsx > Tab HOT_WATER;
- Add the Column ['class_dhw'] with values = NONE, LOW_TEMP, MEDIUM_TEMP, or HIGH_TEMP, then save;
- Execute CEA demand.

Please also pay attention to the soon to be commited German DE Database. Thank you!

Regards, Zhongming

**Comment by Mar-Ges** [comment]
Perfect! Thanks a lot :)
