### ISSUE TITLE
Error using the simplified radiation model 

### ISSUE THREAD

**Issue by yameima** [architecture-building-systems/CityEnergyAnalyst#3519]
**Describe the bug**
the report : ModuleNotFoundError: No module named 'cea.resources.radiation.simplified'

**To Reproduce**

**Expected behaviour**
because when i use other choose to simulate the radiation, my computer always can't work,so I want use the  simplified radiation model to help me finish this simulation of energy demand
**Screenshots**
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150877623/92fe1a55-9542-40bf-ba9f-1a4aac6616fb)

**Hardware (please complete the following information):**
 - OS and version: [Windows 10]
 - Version of CEA you are using [e.g. v. 3.35.3]

**Comment by Mar-Ges** [comment]
Hi @yumeima, 
as I learned from #3517 - the simplified radiation model needs a selection of buildings (at least one must be unselected). Have you tried this?

**Comment by ShiZhongming** [comment]
Thanks @Mar-Ges 
The issue of @yameima seems to be an older one happned in V3.34.0. @yameima I would like to ask to fill the template with details before posting it. Thank you.

**Comment by yameima** [comment]
thanks @Mar-Ges,I've tried, but it doesn't work,the same error occurred
@ShiZhongming, I didn't install an older version of CEA, this is the first version I installed，V3.35.3
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150877623/1bbe82fc-6341-43f7-a8b8-571e6f5ce972)

**Comment by yameima** [comment]
Hi, @ShiZhongming ,  this is the script running error, may I ask how to solve this problem? Does this need to be addressed by providing missing files, or I still need to reinstall the software, but the version I installed is 3.35.3. I don't know why this happens

Traceback (most recent call last):
  File "D:\CEA\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "D:\CEA\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "D:\CEA\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "D:\CEA\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 65, in __getattribute__
    self._runner = script_wrapper(self._cea_script)
  File "D:\CEA\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 16, in script_wrapper
    script_module = importlib.import_module(module_path)
  File "D:\CEA\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cea.resources.radiation.simplified'
