### ISSUE TITLE
could not save changes in schedules 

### ISSUE THREAD

**Issue by Abhi01999** [architecture-building-systems/CityEnergyAnalyst#3541]
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask_restx\api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask\views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask_restx\resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\interfaces\dashboard\api\inputs.py", line 200, in put
    data = data.append(df, ignore_index=True)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

**Comment by reyery** [comment]
Hi @Abhi01999, thanks for reporting this issue. Would you be able to provide us with more information on how you would reproduce this issue?

**Comment by reyery** [comment]
Closed because issue is stale. Kindly reopen if this is still and issue.
