### ISSUE TITLE
Can't open Use-types

### ISSUE THREAD

**Issue by moaapplepie** [architecture-building-systems/CityEnergyAnalyst#3545]
Hi!

I have some problems with the databases, when I try to open Use-types I get the error message as attached below. It started when I tried to make a new use type in the database, I only copied an existing and tried to import it, that's when the problem started. Now I can't open any database, either the one I just worked with or a default (eg. CH). 

Thanks for the help :) //Moa

USE-TYPES
Something went wrong.
Detaljer
TypeError: Cannot convert undefined or null to object

    at $re (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-ZeiyF05R.js:245:12834)
    at div
    at Dre (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-ZeiyF05R.js:245:12187)
    at Pre (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-ZeiyF05R.js:245:11715)
    at <anonymous> (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-D7mzYQjW.js:158:14169)
    at div
    at div
    at Yre (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-ZeiyF05R.js:245:17709)
    at jre (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-ZeiyF05R.js:245:16499)
    at div
    at div
    at Bre (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-ZeiyF05R.js:245:15534)
    at <anonymous> (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-D7mzYQjW.js:158:14169)
    at Suspense
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:18800)
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:19765)
    at div
    at div
    at div
    at PD (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-D7mzYQjW.js:158:62165)
    at TD (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-D7mzYQjW.js:158:62879)
    at Suspense
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:18800)
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:19765)
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:17026)
    at u (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:33032)
    at a (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:34512)
    at x (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:77:6586)
    at B5 (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:81:472)
    at g7 (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-d_6V_B_w.js:83:1220)

**Comment by ShiZhongming** [comment]
I hope this is resolved with the CEA releases later. Please reopen it if you have this issue (again).
