### ISSUE TITLE
MemoryError when running demand script

### ISSUE THREAD

**Issue by marianajanuario97** [architecture-building-systems/CityEnergyAnalyst#3547]
Hey, i'm trying to install CEA but i'm getting the following error when i try to open the dashboard : 
![Captura de ecrã 2024-04-11 141305](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/166637343/a3243a9e-8797-4a8a-91a7-b6ebceedf850)

I've had CEA installed before but I have delete it and i'm re-installing since i need the developers version, and the first time I intalled everything was ok. 

Edit: I was finally able to install CEA but now when running the demand it crashes.

**Comment by reyery** [comment]
@marianajanuario97 could you try running demand from the "CEA console" using the command below and see if there are any error messages.
```
cea demand
```

**Comment by marianajanuario97** [comment]
(cea) PS C:\Users\maria\Documents\CityEnergyAnalyst> cea demand
City Energy Analyst version 3.35.6
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\maria\Documents\Projeto\Viana do Castelo - Amorosa
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- demand:buildings = ['BWLD-MS-120889214', 'BWLD-MS-120889245', 'BWLD-MS-120889275', 'BWLD-MS-120889296', 'BWLD-MS-120889318', 'BWLD-MS-120889325', 'BWLD-MS-120889353', 'BWLD-MS-120889357', 'BWLD-MS-120889387', 'BWLD-MS-60810629', 'BWLD-MS-60810652', 'Bosm-w210107537', 'Bosm-w210107538', 'Bosm-w210107539', 'Bosm-w210107545', 'Bosm-w210107547', 'Bosm-w210107549', 'Bosm-w210107553', 'Bosm-w210481762', 'Bosm-w210481763', 'Bosm-w210481764', 'Bosm-w210493828', 'Bosm-w210493833', 'Bosm-w210493834', 'Bosm-w210493837', 'Bosm-w210493839', 'Bosm-w210493844', 'Bosm-w210493845', 'Bosm-w210493850', 'Bosm-w210493851', 'Bosm-w210493853', 'Bosm-w210497541', 'Bosm-w210497543', 'Bosm-w210497544', 'Bosm-w210497545', 'Bosm-w210497546', 'Bosm-w210497547', 'Bosm-w210497549', 'Bosm-w210497550', 'Bosm-w210497551', 'Bosm-w210497552', 'Bosm-w210497554', 'Bosm-w210497555', 'Bosm-w210497556', 'Bosm-w210497557', 'Bosm-w210497558', 'Bosm-w210497559', 'Bosm-w210497560']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = True
  (default: True)
Running demand calculation for scenario C:\Users\maria\Documents\Projeto\Viana do Castelo - Amorosa
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation for the following buildings=['BWLD-MS-120889214', 'BWLD-MS-120889245', 'BWLD-MS-120889275', 'BWLD-MS-120889296', 'BWLD-MS-120889318', 'BWLD-MS-120889325', 'BWLD-MS-120889353', 'BWLD-MS-120889357', 'BWLD-MS-120889387', 'BWLD-MS-60810629', 'BWLD-MS-60810652', 'Bosm-w210107537', 'Bosm-w210107538', 'Bosm-w210107539', 'Bosm-w210107545', 'Bosm-w210107547', 'Bosm-w210107549', 'Bosm-w210107553', 'Bosm-w210481762', 'Bosm-w210481763', 'Bosm-w210481764', 'Bosm-w210493828', 'Bosm-w210493833', 'Bosm-w210493834', 'Bosm-w210493837', 'Bosm-w210493839', 'Bosm-w210493844', 'Bosm-w210493845', 'Bosm-w210493850', 'Bosm-w210493851', 'Bosm-w210493853', 'Bosm-w210497541', 'Bosm-w210497543', 'Bosm-w210497544', 'Bosm-w210497545', 'Bosm-w210497546', 'Bosm-w210497547', 'Bosm-w210497549', 'Bosm-w210497550', 'Bosm-w210497551', 'Bosm-w210497552', 'Bosm-w210497554', 'Bosm-w210497555', 'Bosm-w210497556', 'Bosm-w210497557', 'Bosm-w210497558', 'Bosm-w210497559', 'Bosm-w210497560']
read input files
done
Using 19 CPU's
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-9:
Process SpawnPoolWorker-5:
Process SpawnPoolWorker-8:
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from . import lib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\__init__.py", line 26, in <module>
    from . import index_tricks
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\__init__.py", line 4, in <module>
    from . import defmatrix
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\defmatrix.py", line 11, in <module>
    from numpy.linalg import matrix_power
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\__init__.py", line 73, in <module>
    from . import linalg
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\linalg.py", line 34, in <module>
    from numpy.linalg import _umath_linalg
ImportError: DLL load failed while importing _umath_linalg: Não existem recursos de memória suficientes para processar este comando.
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process SpawnPoolWorker-17:
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
Process SpawnPoolWorker-16:
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\__init__.py", line 101, in <module>
    from . import _add_newdocs
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 934, in get_code
  File "<frozen importlib._bootstrap_external>", line 1033, in get_data
MemoryError
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from . import lib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\__init__.py", line 26, in <module>
    from . import index_tricks
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\__init__.py", line 4, in <module>
    from . import defmatrix
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\defmatrix.py", line 11, in <module>
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\__init__.py", line 73, in <module>
    from . import linalg
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\linalg.py", line 34, in <module>
    from numpy.linalg import _umath_linalg
ImportError: DLL load failed while importing _umath_linalg: O ficheiro de estrutura de página é demasiado pequeno para que esta operação seja concluída.
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from . import lib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\__init__.py", line 26, in <module>
    from . import index_tricks
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\__init__.py", line 73, in <module>
    from . import numeric
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\numeric.py", line 2557, in <module>
    extend_all(arrayprint)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\numeric.py", line 2537, in extend_all
    existing = set(__all__)
MemoryError
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 144, in <module>
    from . import lib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\__init__.py", line 26, in <module>
    from . import index_tricks
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\__init__.py", line 4, in <module>
    from . import defmatrix
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\defmatrix.py", line 11, in <module>
    from numpy.linalg import matrix_power
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\__init__.py", line 73, in <module>
    from . import linalg
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\linalg.py", line 34, in <module>
    from numpy.linalg import _umath_linalg
ImportError: DLL load failed while importing _umath_linalg: Não existem recursos de memória suficientes para processar este comando.
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\__init__.py", line 4, in <module>
    from . import defmatrix
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\matrixlib\defmatrix.py", line 11, in <module>
    from numpy.linalg import matrix_power
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\__init__.py", line 73, in <module>
    from . import linalg
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\linalg\linalg.py", line 34, in <module>
    from numpy.linalg import _umath_linalg
ImportError: DLL load failed while importing _umath_linalg: Não existem recursos de memória suficientes para processar este comando.
Process SpawnPoolWorker-21:
Process SpawnPoolWorker-27:
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\__init__.py", line 101, in <module>
    from . import _add_newdocs
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\_add_newdocs.py", line 4970, in <module>
    add_newdoc('numpy.core._multiarray_tests', 'format_float_OSprintf_g',
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\function_base.py", line 529, in add_newdoc
    new = getattr(__import__(place, globals(), {}, [obj]), obj)
ImportError: DLL load failed while importing _multiarray_tests: O ficheiro de estrutura de página é demasiado pequeno para que esta operação seja concluída.
Traceback (most recent call last):
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\multiprocessing\queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\maria\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 9, in <module>
    import numpy as np
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
    from . import overrides
  File "C:\Users\maria\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\core\overrides.py", line 8, in <module>
    from numpy.compat._inspect import getargspec
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 934, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
MemoryError

and shortly after it just crashes..

**Comment by reyery** [comment]
@marianajanuario97, thank you for providing the error log. I think I might have a rough idea why the demand and radiation are crashing now for everyone. I am working on a fix right now and will try to release it soon.

**Comment by reyery** [comment]
Hi @marianajanuario97, could you trying reinstalling CEA using this version and let me know if it helps.

https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.35.6/Setup_CityEnergyAnalyst_3.35.6.exe

**Comment by marianajanuario97** [comment]
Hi @reyery i've installed and now i get the following error when trying to open the dashboard. 
![Captura de ecrã 2024-04-16 103649](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/166637343/9208036c-0705-4d8e-9e34-fbe2f6cac488)
Also when trying to run with the console it starts to run but then it just gets stucked.

**Comment by reyery** [comment]
@marianajanuario97 I am currently building a new setup to solve various issue. I will let you know again once it is done, so that you can test it again.

**Comment by marianajanuario97** [comment]
ok, thank you!

**Comment by reyery** [comment]
I have rebuilt the setup. Let me know if this one works.

https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.35.6/Setup_CityEnergyAnalyst_3.35.6.exe

**Comment by reyery** [comment]
Hi @marianajanuario97, I am wondering if you have tested the new installer and if it solves your issue.

**Comment by reyery** [comment]
Closing because issue is stale. Kindly reopen if you still need help.

**Comment by marianajanuario97** [comment]
Hi @reyery , sorry i wasn't able to test this sooner. 
I've installed and i'm not able to open the dashboard, when i try and run the demand in the console it runs but the folder( where the demand.xlsx should be) stays empty. 
Thank you
