### ISSUE TITLE
could not save changes in schedule 

### ISSUE THREAD

**Issue by Abhi01999** [architecture-building-systems/CityEnergyAnalyst#3556]
could not save the changes made in schedule.
Below pasted is the code occurring when tried to save changes.
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask_restx\api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask\views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\flask_restx\resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\interfaces\dashboard\api\inputs.py", line 200, in put
    data = data.append(df, ignore_index=True)
  File "C:\Program Files (x86)\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```
Screenshot
![Screenshot 2024-04-19 150655](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/165277518/dc3f1454-6bd3-44c0-a511-3076fe22553c)

**Hardware (please complete the following information):**
 - OS and version: [OS Name	Microsoft Windows 11 Pro]
 - Version of CEA you are using [e.g. CEA3.35.5*]

**Comment by reyery** [comment]
This issue has been fixed and you can download the pre-release setup here if you need it.

https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.35.6/Setup_CityEnergyAnalyst_3.35.6.exe
