### ISSUE TITLE
Error in solar radiation analysis

### ISSUE THREAD

**Issue by anjaWill** [architecture-building-systems/CityEnergyAnalyst#3597]
**Describe the bug**
Running the solar radiation on one of my students computers creates the following error:
```
City Energy Analyst version 3.36.1
Running `cea radiation` with the following parameters:
- general:scenario = /Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm
  (default: {general:project}/{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- radiation:buildings = ['B1001', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1009', 'B1010', 'B1404']
  (default: [])
- radiation:use-latest-daysim-binaries = True
  (default: True)
- radiation:albedo = 0.2
  (default: 0.2)
- radiation:roof-grid = 10
  (default: 10)
- radiation:walls-grid = 200
  (default: 200)
- radiation:zone-geometry = 2
  (default: 2)
- radiation:surrounding-geometry = 5
  (default: 5)
- radiation:consider-floors = True
  (default: True)
- radiation:neglect-adjacent-buildings = False
  (default: False)
- radiation:rad-ab = 4
  (default: 4)
- radiation:rad-ad = 512
  (default: 512)
- radiation:rad-as = 32
  (default: 32)
- radiation:rad-ar = 20
  (default: 20)
- radiation:rad-aa = 0.15
  (default: 0.15)
- radiation:rad-lr = 8
  (default: 8)
- radiation:rad-st = 0.5
  (default: 0.5)
- radiation:rad-sj = 0.7
  (default: 0.7)
- radiation:rad-lw = 0.05
  (default: 0.05)
- radiation:rad-dj = 0.7
  (default: 0.7)
- radiation:rad-ds = 0.0
  (default: 0.0)
- radiation:rad-dr = 0
  (default: 0)
- radiation:rad-dp = 32
  (default: 32)
- radiation:daysim-bin-directory = /
  (default: /)
- radiation:n-buildings-in-chunk = 100
  (default: 100)
- radiation:write-sensor-data = True
  (default: True)
Using Daysim binaries from path: /Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/resources/radiation/bin/darwin
Using Daysim data from path: None
verifying geometry files
zone: /Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm/inputs/building-geometry/zone.shp
surroundings: /Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm/inputs/building-geometry/surroundings.shp
Getting geometry materials
Creating 3D geometry and surfaces
Saving geometry pickle files in: /Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm/outputs/data/solar-radiation/radiance_geometry_pickle
Standardizing coordinate systems
Reading terrain geometry
Creating 3D building surfaces
Calculating terrain intersection of building geometries
/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/shapely/constructive.py:881: RuntimeWarning: invalid value encountered in simplify_preserve_topology
  return lib.simplify_preserve_topology(geometry, tolerance, **kwargs) Using 9 CPU's Calculation of terrain intersection for building 1 completed out of 9 Calculation of terrain intersection for building 2 completed out of 9 Calculation of terrain intersection for building 3 completed out of 9 Calculation of terrain intersection for building 4 completed out of 9 Calculation of terrain intersection for building 5 completed out of 9 Calculation of terrain intersection for building 6 completed out of 9 Calculation of terrain intersection for building 7 completed out of 9 Calculation of terrain intersection for building 8 completed out of 9 Calculation of terrain intersection for building 9 completed out of 9 Using 9 CPU's Calculation of terrain intersection for building 1 completed out of 5 Calculation of terrain intersection for building 2 completed out of 5 Calculation of terrain intersection for building 3 completed out of 5 Calculation of terrain intersection for building 4 completed out of 5 Calculation of terrain intersection for building 5 completed out of 5 Generating geometry for surrounding buildings Generating geometry for buildings in the zone of analysis Using 9 CPU's Generating geometry for building 1 completed out of 9 Generating geometry for building 2 completed out of 9 Generating geometry for building 3 completed out of 9 Generating geometry for building 4 completed out of 9 Generating geometry for building 5 completed out of 9 Generating geometry for building 6 completed out of 9 Generating geometry for building 7 completed out of 9 Generating geometry for building 8 completed out of 9 Generating geometry for building 9 completed out of 9 Creating radiance material file Creating radiance geometry file Converting files for DAYSIM Transforming weather files to daysim format Running command `epw2wea "/Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm/inputs/weather/weather.epw" "/Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm/outputs/data/solar-radiation/cea_radiation/common_inputs/weather_60min.wea"`

b''
Traceback (most recent call last):
  File "/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/worker.py", line 146, in worker
    run_job(config, job, server)
  File "/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/api.py", line 38, in script_runner
    script_module.main(config)
  File "/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/resources/radiation/main.py", line 183, in main
    cea_daysim.execute_epw2wea(weather_file)
  File "/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/resources/radiation/radiance.py", line 154, in execute_epw2wea
    epw2wea_result = self.run_cmd(command, self.daysim_dir, self.daysim_lib)
  File "/Users/lenaguddat/Documents/CityEnergyAnalyst/envs/cea/lib/python3.8/site-packages/cea/resources/radiation/radiance.py", line 125, in run_cmd
    raise subprocess.CalledProcessError(process.returncode, cmd)
subprocess.CalledProcessError: Command 'epw2wea "/Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm/inputs/weather/weather.epw" "/Users/lenaguddat/Library/Mobile Documents/com~apple~CloudDocs/Documents/Uni/Master FRA UAS 23-25/Semester 2 24/Spiekeroog/Test/Bestand - Turm/outputs/data/solar-radiation/cea_radiation/common_inputs/weather_60min.wea"' died with <Signals.SIGTRAP: 5>.
```

When I run the same weather file in the same scenario on my computer, the solar radiation is running and creating results - no errors occur. 
Can you help to identify the error?

Thanks a lot. Anja

**Comment by reyery** [comment]
Hi @anjaWill, based on the given error message, I suspect it has to do with the scenario being located on an iCloud drive location. 
Could the student try running the scenario from another location on their hard drive, and let us know if that works.
At the same time, we can see what we can do to solve this issue. Thanks!

**Comment by anjaWill** [comment]
Hi @reyery, running the scenario from another location does not solve the problem. Do you have any other idea what the reasons for the problem is?

**Comment by peppenappi** [comment]
Hello @anjaWill, i ran into a similar problem lately. My radiation script was failing during the DaySim simulation, at a later stage compared to your case. This was my error:

Traceback (most recent call last):
  File "D:\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation\main.py", line 198, in <module>
    main(cea.config.Configuration())
  File "D:\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation\main.py", line 188, in main
    run_daysim_simulation(cea_daysim, zone_building_names, locator, config.radiation, geometry_staging_location,
  File "D:\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation\main.py", line 91, in run_daysim_simulation
    daysim.isolation_daysim(
  File "D:\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation\daysim.py", line 316, in isolation_daysim
    daysim_project.execute_gen_dc()
  File "D:\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation\radiance.py", line 425, in execute_gen_dc
    CEADaySim.run_cmd(command1, self.daysim_bin_directory, self.daysim_lib_directory)
  File "D:\GitHub\CityEnergyAnalyst\CityEnergyAnalyst\CityEnergyAnalyst\cea\resources\radiation\radiance.py", line 125, in run_cmd
    raise subprocess.CalledProcessError(process.returncode, cmd)
subprocess.CalledProcessError: Command 'gen_dc "D:\CEATesting\THESIS TEST CASES BASE\Commercial high-rise\outputs\data\solar-radiation\cea_radiation\projects\chunk_0\chunk_0.hea" -dir' returned non-zero exit status 3221226505.

However, as you can see in my directories, the folder names are full of spaces. I tried re-running the script after removing them and the problem was solved. So my guess is that in a recent update of the DaySim library it became more sensitive to spaces in path directories, and i see that you also have many spaces in your folder names, so maybe you could try again after removing these spaces.

**Comment by anjaWill** [comment]
Hi @reyery @peppenappi removing spaces and relocating the folder to a computer drive solved the problem. Thanks a lot!
