### ISSUE TITLE
Error: can´t convert float NaN to integer

### ISSUE THREAD

**Issue by anjaWill** [architecture-building-systems/CityEnergyAnalyst#3603]
**Describe the bug**
when running building energy demand the following error occurs: can´t convert float NaN to integer. Any clue what might be the problem? Appears in one of my students projects but not in any other project that uses the same weather data, location etc. 

![Image20240606162448](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150787078/d12bee1f-8ad5-4ba2-bc5c-650f150a5e1d)

**Comment by anjaWill** [comment]
This is the complete error message: 

City Energy Analyst version 3.35.5
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\Anja.Willmann\Documents\05 FRA-UAS 2023\03 Lehre\03 SoSe24\Spiekeroog\CEA\Vanessa_Bestand_mit_Entwurf_einzeln
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = False
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- demand:buildings = ['B1000', 'B1001', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011', 'B1012', 'B1013', 'B2001', 'B2002', 'B2003']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = False
  (default: True)
Running demand calculation for scenario C:\Users\Anja.Willmann\Documents\05 FRA-UAS 2023\03 Lehre\03 SoSe24\Spiekeroog\CEA\Vanessa_Bestand_mit_Entwurf_einzeln
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=False
Running demand calculation for the following buildings=['B1000', 'B1001', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1008', 'B1009', 'B1010', 'B1011', 'B1012', 'B1013', 'B2001', 'B2002', 'B2003']
read input files
done
Warning! The following list of buildings have less than 100 m2 of gross floor area, CEA might fail: ['B1000', 'B1005', 'B1011', 'B1012', 'B1013', 'B2003']
Using single process
Building No. 1 completed out of 16: B1000
Building No. 2 completed out of 16: B1001
Building No. 3 completed out of 16: B1003
Traceback (most recent call last):
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\demand_main.py", line 145, in main
    demand_calculation(locator=locator, config=config)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\demand_main.py", line 106, in demand_calculation
    calc_thermal_loads(
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\utilities\parallel.py", line 149, in wrapper
    result = func(*instance_args)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\thermal_loads.py", line 142, in calc_thermal_loads
    tsd = hotwater_loads.calc_Qww_sys(bpr, tsd)  # system (incl. losses)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\hotwater_loads.py", line 102, in calc_Qww_sys
    Qww_dis_ls_r_W = np.vectorize(calc_Qww_dis_ls_r)(T_int_C, tsd['Qww'].copy(), Lsww_dis, Lcww_dis, Y[1], Qww_nom_W,
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2329, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2415, in _vectorize_call
    res = asanyarray(outputs, dtype=otypes[0])
ValueError: cannot convert float NaN to integer

**Comment by anjaWill** [comment]
The same problem now appreared in another projekt when running the building energy demand: 

City Energy Analyst version 3.35.5
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\Anja.Willmann\Documents\05 FRA-UAS 2023\03 Lehre\03 SoSe24\Spiekeroog\CEA\Sophie_Bestand ohne B1000-8-10-11-12 - Network - V1 - 00
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = False
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- demand:buildings = ['B1001', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1009', 'B1010', 'B1012']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = False
  (default: True)
Running demand calculation for scenario C:\Users\Anja.Willmann\Documents\05 FRA-UAS 2023\03 Lehre\03 SoSe24\Spiekeroog\CEA\Sophie_Bestand ohne B1000-8-10-11-12 - Network - V1 - 00
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=False
Running demand calculation for the following buildings=['B1001', 'B1003', 'B1004', 'B1005', 'B1006', 'B1007', 'B1009', 'B1010', 'B1012']
read input files
done
Warning! The following list of buildings have less than 100 m2 of gross floor area, CEA might fail: ['B1005']
Using single process
Building No. 1 completed out of 9: B1001
Traceback (most recent call last):
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\demand_main.py", line 145, in main
    demand_calculation(locator=locator, config=config)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\demand_main.py", line 106, in demand_calculation
    calc_thermal_loads(
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\utilities\parallel.py", line 149, in wrapper
    result = func(*instance_args)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\thermal_loads.py", line 142, in calc_thermal_loads
    tsd = hotwater_loads.calc_Qww_sys(bpr, tsd)  # system (incl. losses)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\hotwater_loads.py", line 102, in calc_Qww_sys
    Qww_dis_ls_r_W = np.vectorize(calc_Qww_dis_ls_r)(T_int_C, tsd['Qww'].copy(), Lsww_dis, Lcww_dis, Y[1], Qww_nom_W,
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2329, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\Anja.Willmann\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2415, in _vectorize_call
    res = asanyarray(outputs, dtype=otypes[0])
ValueError: cannot convert float NaN to integer

**Comment by ShiZhongming** [comment]
Hi @anjaWill 
Can you send one problematic scenario's inputs folder to me via email?
