### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by andywang65384** [architecture-building-systems/CityEnergyAnalyst#3604]
**Describe the bug**
I try to install following the Installation guide, but the problems still happens.

**Screenshots**
![Screenshot 2024-06-10 111307](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/52534103/a0d06d03-dbcb-42d6-b02d-240bed7956c4)

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10] Windows 10
 - Version of CEA you are using [e.g. v. 2.31.1] v 3.36.1

**Comment by andywang65384** [comment]
Here is the details:

Output folder: C:\Users\XXXX\Documents\CityEnergyAnalyst
Extract: cityenergyanalyst.tar.gz
Output folder: C:\Users\XXXX\Documents\CityEnergyAnalyst\dependencies
Extract: cea-env.7z
Extract: cea-env.bat... 100%
Extract: micromamba.exe... 100%
Output folder: C:\Users\XXXX\Documents\CityEnergyAnalyst
Output folder: C:\Users\XXXX\Documents\CityEnergyAnalyst\dependencies
Delete file: C:\Users\XXXX\Documents\CityEnergyAnalyst\dependencies\cea-env.7z
Output folder: C:\Users\XXXX\Documents\CityEnergyAnalyst
warning  libmamba Hook installed, now 'manually' execute:
warning  libmamba        CALL "C:\\Users\\XXXX\\Documents\\CityEnergyAnalyst\\dependencies\\micromamba\\condabin\\mamba_hook.bat"
Collecting pip
  Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
  Rolling back uninstall of pip
  Moving to c:\users\XXXX\appdata\roaming\python\python38\scripts\pip.exe
   from C:\Users\XXXX\AppData\Local\Temp\pip-uninstall-xla4825a\pip.exe
  Moving to c:\users\XXXX\appdata\roaming\python\python38\scripts\pip3.10.exe
   from C:\Users\XXXX\AppData\Local\Temp\pip-uninstall-xla4825a\pip3.10.exe
  Moving to c:\users\XXXX\appdata\roaming\python\python38\scripts\pip3.8.exe
   from C:\Users\XXXX\AppData\Local\Temp\pip-uninstall-xla4825a\pip3.8.exe
  Moving to c:\users\XXXX\appdata\roaming\python\python38\scripts\pip3.exe
   from C:\Users\XXXX\AppData\Local\Temp\pip-uninstall-xla4825a\pip3.exe
  Moving to c:\users\XXXX\appdata\roaming\python\python38\site-packages\pip-23.1.2.dist-info\
   from C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\~ip-23.1.2.dist-info
  Moving to c:\users\XXXX\appdata\roaming\python\python38\site-packages\pip\
   from C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\~ip
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\commands\install.py", line 449, in run
    installed = install_given_reqs(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\req\__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\req\req_install.py", line 800, in install
    install_wheel(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\operations\install\wheel.py", line 731, in install_wheel
    _install_wheel(
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\operations\install\wheel.py", line 648, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\distlib\scripts.py", line 436, in make_multiple
    filenames.extend(self.make(specification, options))
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_internal\operations\install\wheel.py", line 429, in make
    return super().make(specification, options)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\distlib\scripts.py", line 425, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\distlib\scripts.py", line 325, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\distlib\scripts.py", line 249, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\XXXX\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\distlib\scripts.py", line 404, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
pip installing CityEnergyAnalyst==3.36.1
failed to create process.
pip install cityenergyanalyst==3.36.1 returned 0
Delete file: C:\Users\XXXX\Documents\CityEnergyAnalyst\cityenergyanalyst.tar.gz
'cea' is not recognized as an internal or external command,
operable program or batch file.
"cea --help" returned 1
Installation failed - see Details

**Comment by reyery** [comment]
Hi @andywang65384, thank you for reporting this issue. Based on the error message, it seems that there was an issue setting up pip for the CEA python environment.

Could you try clearing the cache for pip first by running this command in your command prompt:
```
pip cache purge
```
Then try installing again to see if that solves the issue. Thanks!

**Comment by andywang65384** [comment]
> Hi @andywang65384, thank you for reporting this issue. Based on the error message, it seems that there was an issue setting up pip for the CEA python environment.
> 
> Could you try clearing the cache for pip first by running this command in your command prompt:
> 
> ```
> pip cache purge
> ```
> 
> Then try installing again to see if that solves the issue. Thanks!

Hi,@reyery, thanks for your reply.  I tried clearing the cache, but the same problems still there. 

I also tried to upgrade setuptools befoe installation, which also not working.
`pip install --upgrade setuptools `

**Comment by reyery** [comment]
Hmmm I am still not able to reproduce this issue on multiple machines. 
Would you be comfortable with creating the CEA conda environment manually for the time being? The steps can be found in our docs [here](https://city-energy-analyst.readthedocs.io/en/latest/installation/installation-on-windows-manual.html)
We would try to investigate this issue further.
