### ISSUE TITLE
Invalid argument error 22 for solar radiation 

### ISSUE THREAD

**Issue by xingao747** [architecture-building-systems/CityEnergyAnalyst#3670]
**Error message:**   
The problem is that in total there are 87 buildings and the solar radiation is run for 86 buildings only. It says that the simulation is completed for 86 buildings and then below error message pops up. 
....
Calculation of terrain intersection for building 86 completed out of 86
Using 23 CPU's
Calculation of terrain intersection for building 1 completed out of 71Traceback (most recent call last):
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\resources\radiation\main.py", line 168, in main
    tree_surfaces) = geometry_generator.geometry_main(config,
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\resources\radiation\geometry_generator.py", line 642, in geometry_main
    geometry_3D_zone, geometry_3D_surroundings = building_2d_to_3d(zone_df, surroundings_df, architecture_wwr_df,
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\resources\radiation\geometry_generator.py", line 186, in building_2d_to_3d
    surroundings_building_solid_list = calc_building_solids(surroundings_buildings_df, surroundings_simplification,
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\resources\radiation\geometry_generator.py", line 130, in calc_building_solids
    out = cea.utilities.parallel.vectorize(process_geometries, num_processes,
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\utilities\parallel.py", line 95, in wrapper
    stream_from_queue(queue)
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\utilities\workerstream.py", line 69, in stream_from_queue
    sys.stdout.write(msg)
  File "C:\Users\xingao\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 84, in write
**print("cea-worker: {str}".format(**locals()), end='', file=self.stream)
OSError: [Errno 22] Invalid argument**

**To Reproduce**
1. Go to solar radiation 
2. Click on run (I did not change any of the settings) 
3. Scroll down to 'Job Output'

**Expected behaviour**
The solar radiation should be shown for all 87 buildings. 

**Screenshots**
![image](https://github.com/user-attachments/assets/2930af67-1afd-435d-b93d-869ac7b9353d)

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10] -> Windows 11 in the computer room of IDP course 
 - Version of CEA you are using [e.g. v. 2.31.1] -> newest one from the IDP course 
Thank you in advance! 
@reyery

**Comment by reyery** [comment]
@xingao747 it seems that there is a bug for when the app is trying to read/write the output after the stream is closed. We will be pushing a new update soon that should fix this.

**Comment by ShiZhongming** [comment]
Hi @xingao747 Does this problem persist?

**Comment by xingao747** [comment]
Hi

No the problem is fixed, thank you.

Kindly,
Xinge
________________________________
Von: Zhongming Shi ***@***.***>
Gesendet: Dienstag, 12. November 2024 18:27
An: architecture-building-systems/CityEnergyAnalyst ***@***.***>
Cc: Gao Xinge ***@***.***>; Mention ***@***.***>
Betreff: Re: [architecture-building-systems/CityEnergyAnalyst] Invalid argument error 22 for solar radiation (Issue #3670)


Hi @xingao747<https://github.com/xingao747> Does this problem persist?
