### ISSUE TITLE
Archetype Mapper runs with error with user-defined zone file input

### ISSUE THREAD

**Issue by yiqiaowang-arch** [architecture-building-systems/CityEnergyAnalyst#3672]
When creating a new scenario, I prefer not to use the OSM data, so I tried to mimic the zone.shp structure and have my zone.shp also with the Name, floors_ag, height_ag, floors_bg, height_bg and imported to CEA. CEA reads the buildings correctly, but did not show anything in the geometry bar, and suggested me to run archetype mapper first.

![image](https://github.com/user-attachments/assets/139b9aca-e9df-4e0e-bd8b-b73b95d57469)

However, the archetype mapper results in an error which I cannot easily interpret, so I am writing to ask for help:
```
Job Output for 6 - archetypes-mapper
City Energy Analyst version 3.38.0
Running `cea archetypes-mapper` with the following parameters:
- general:scenario = D:\OneDrive\ETHY3FW\semesterProjectYiqiaoWang\CEA\Altstetten\Basecase
  (default: {general:project}\{general:scenario-name})
- archetypes-mapper:input-databases = ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules']
  (default: ['comfort', 'architecture', 'air-conditioning', 'internal-loads', 'supply', 'schedules'])
- archetypes-mapper:buildings = ['B160768', 'B160774', 'B160775', 'B160776', 'B160778', 'B160778', 'B160779', 'B160780', 'B160781', 'B160782', 'B160783', 'B160784', 'B160786', 'B160787', 'B160788', 'B160789', 'B160790', 'B160791', 'B160792', 'B160793', 'B160794', 'B160795', 'B160796', 'B160797', 'B160798', 'B160799', 'B160800', 'B160801', 'B160802', 'B160803', 'B160804', 'B160806', 'B160807', 'B160808', 'B160810', 'B160811', 'B160812', 'B160813', 'B160814', 'B160815', 'B160816', 'B160817', 'B160818', 'B160819', 'B160820', 'B160822', 'B160823', 'B160824', 'B160825', 'B160826', 'B160827', 'B160828', 'B160829', 'B160830', 'B160831', 'B160833', 'B160835', 'B160836', 'B160837', 'B160838', 'B160839', 'B160840', 'B160842', 'B160843', 'B160844', 'B160845', 'B160848', 'B160849', 'B160850', 'B160851', 'B160852', 'B160853', 'B160861', 'B160862', 'B160863', 'B160864', 'B160865', 'B160871', 'B160872', 'B160873', 'B160874', 'B160875', 'B160876', 'B160877', 'B160878', 'B160879', 'B160880', 'B160881', 'B160882', 'B160883', 'B160884', 'B160885', 'B160886', 'B160887', 'B160888', 'B160889', 'B160890', 'B160891', 'B160892', 'B160893', 'B160895', 'B160896', 'B160897', 'B160898', 'B160899', 'B160900', 'B160901', 'B160902', 'B160903', 'B160904', 'B160905', 'B160907', 'B160908', 'B160909', 'B160910', 'B160911', 'B160912', 'B160917', 'B160918', 'B160919', 'B160920', 'B160921', 'B160922', 'B160923', 'B160924', 'B160925', 'B160926', 'B160928', 'B160930', 'B160931', 'B160932', 'B160933', 'B160935', 'B160936', 'B160937', 'B160938', 'B160939', 'B160941', 'B160942', 'B160944', 'B160945', 'B160946', 'B160947', 'B160948', 'B160949', 'B160950', 'B160951', 'B160952', 'B160953', 'B160954', 'B160955', 'B160956', 'B160957', 'B160958', 'B160959', 'B160960', 'B160962', 'B160963', 'B160964', 'B160965', 'B160966', 'B160969', 'B160970', 'B160971', 'B160972', 'B160973', 'B160974', 'B160978', 'B160979', 'B160980', 'B160981', 'B160983', 'B160984', 'B160985', 'B160986', 'B160987', 'B160988', 'B160989', 'B160991', 'B160992', 'B160993', 'B160995', 'B160996', 'B160997', 'B160998', 'B160999', 'B161000', 'B161001', 'B161004', 'B161009', 'B161010', 'B161011', 'B161012', 'B161013', 'B161014', 'B161015', 'B161016', 'B161017', 'B161018', 'B161019', 'B161020', 'B161021', 'B161022', 'B161023', 'B161025', 'B161026', 'B161027', 'B161029', 'B161030', 'B161031', 'B161032', 'B161033', 'B161034', 'B161037', 'B161038', 'B161039', 'B161040', 'B161041', 'B161042', 'B161043', 'B161044', 'B161045', 'B161046', 'B161066', 'B161067', 'B161068', 'B161069', 'B161070', 'B161071', 'B161072', 'B161073', 'B161074', 'B161075', 'B161076', 'B161077', 'B161078', 'B161079', 'B161080', 'B161081', 'B161086', 'B161087', 'B161088', 'B161089', 'B161090', 'B161091', 'B161092', 'B161093', 'B161094', 'B161095', 'B161096', 'B161097', 'B161098', 'B161100', 'B161101', 'B161102', 'B161109', 'B161110', 'B161138', 'B161139', 'B161143', 'B161149', 'B161150', 'B161151', 'B161152', 'B161266', 'B161267', 'B161268', 'B161269', 'B161274', 'B161275', 'B161276', 'B161277', 'B161278', 'B161279', 'B161280', 'B161281', 'B161282', 'B161288', 'B161290', 'B161291', 'B161293', 'B161295', 'B161328', 'B161329', 'B161331', 'B161333', 'B161334', 'B161335', 'B161377', 'B161379', 'B161381', 'B161382', 'B161383', 'B161384', 'B161385', 'B161387', 'B161389', 'B161390', 'B161391', 'B161392', 'B161393', 'B161397', 'B161399', 'B161400', 'B161400', 'B161401', 'B161403', 'B161404', 'B161405', 'B161406', 'B161407', 'B161419', 'B161420', 'B161474', 'B161480', 'B161481', 'B161482', 'B161483', 'B161484', 'B161485', 'B161486', 'B161487', 'B161488', 'B161489', 'B161490', 'B161491', 'B161492', 'B161493', 'B161494', 'B161495', 'B161503', 'B161505', 'B161521', 'B161522', 'B161524', 'B161525', 'B161526', 'B161527', 'B161529', 'B161958', 'B161959', 'B161960', 'B161962', 'B161964', 'B161967', 'B161969', 'B161970', 'B161971', 'B161972', 'B161974', 'B161975', 'B161976', 'B161977', 'B161978', 'B161979', 'B161980', 'B161982', 'B161983', 'B161984', 'B161985', 'B161986', 'B161987', 'B161988', 'B161989', 'B161990', 'B161991', 'B161992', 'B161993', 'B161994', 'B161996', 'B161997', 'B161998', 'B161999', 'B162000', 'B162001', 'B162002', 'B162003', 'B162004', 'B162005', 'B162006', 'B162007', 'B162008', 'B162010', 'B162011', 'B162012', 'B162013', 'B162014', 'B162015', 'B162016', 'B162017', 'B162018', 'B162020', 'B162021', 'B162022', 'B162023', 'B162024', 'B162025', 'B162026', 'B162027', 'B162028', 'B162029', 'B162030', 'B162031', 'B162032', 'B162033', 'B162034', 'B162035', 'B162036', 'B162037', 'B162038', 'B162039', 'B162040', 'B162041', 'B162042', 'B162043', 'B162044', 'B162046', 'B162047', 'B162048', 'B162049', 'B162050', 'B162052', 'B162053', 'B162054', 'B162055', 'B162056', 'B162057', 'B162058', 'B162059', 'B162060', 'B162061', 'B162062', 'B162063', 'B162064', 'B162065', 'B162066', 'B162067', 'B162068', 'B162069', 'B162070', 'B162071', 'B162072', 'B162073', 'B162074', 'B162075', 'B162076', 'B162077', 'B162078', 'B162079', 'B162080', 'B162081', 'B162082', 'B162083', 'B162084', 'B162085', 'B162086', 'B162087', 'B162089', 'B162090', 'B162091', 'B162092', 'B162093', 'B162094', 'B162095', 'B162097', 'B162098', 'B162099', 'B162100', 'B162101', 'B162103', 'B162106', 'B162107', 'B162108', 'B162110', 'B162111', 'B162112', 'B162115', 'B162116', 'B162119', 'B162120', 'B162124', 'B162125', 'B162126', 'B162127', 'B162128', 'B162129', 'B162130', 'B162131', 'B162133', 'B162134', 'B162135', 'B162136', 'B162137', 'B162138', 'B162139', 'B162140', 'B162141', 'B162142', 'B162143', 'B162144', 'B162145', 'B162146', 'B162148', 'B162149', 'B162150', 'B162151', 'B162152', 'B162153', 'B162155', 'B162156', 'B162157', 'B162158', 'B162159', 'B162160', 'B162161', 'B162162', 'B162163', 'B162164', 'B162165', 'B162166', 'B162167', 'B162168', 'B162169', 'B162170', 'B162171', 'B162172', 'B162173', 'B162174', 'B162175', 'B162176', 'B162177', 'B162178', 'B162180', 'B162181', 'B162182', 'B162183', 'B162184', 'B162185', 'B162186', 'B162187', 'B162188', 'B162192', 'B162193', 'B162195', 'B162196', 'B162197', 'B162199', 'B162200', 'B162201', 'B162203', 'B162204', 'B162206', 'B162207', 'B162208', 'B162209', 'B162213', 'B162214', 'B162215', 'B162219', 'B162220', 'B162221', 'B162222', 'B162225', 'B162227', 'B162228', 'B162255', 'B162256', 'B162259', 'B162262', 'B162265', 'B162266', 'B162267', 'B162268', 'B162269', 'B162273', 'B162276', 'B162277', 'B162280', 'B162282', 'B162285', 'B162289', 'B162290', 'B162291', 'B162292', 'B162293', 'B162294', 'B162298', 'B162299', 'B162300', 'B162301', 'B162302', 'B162303', 'B162304', 'B162305', 'B162306', 'B162309', 'B162310', 'B162311', 'B162313', 'B162314', 'B162315', 'B162317', 'B162319', 'B162320', 'B162321', 'B162322', 'B162324', 'B162325', 'B162326', 'B162327', 'B162328', 'B162329', 'B162331', 'B162332', 'B162333', 'B162334', 'B162335', 'B162336', 'B162337', 'B162338', 'B162339', 'B162340', 'B162341', 'B162342', 'B162343', 'B162344', 'B162345', 'B162346', 'B162347', 'B162348', 'B162349', 'B162350', 'B162351', 'B162356', 'B162359', 'B162360', 'B162361', 'B162367', 'B162368', 'B162369', 'B162372', 'B162373', 'B162374', 'B162376', 'B162378', 'B162379', 'B162380', 'B162381', 'B162382', 'B162383', 'B162384', 'B162385', 'B162386', 'B162387', 'B162388', 'B162389', 'B162390', 'B162391', 'B162392', 'B162393', 'B162394', 'B162395', 'B162396', 'B162401', 'B162402', 'B162403', 'B162404', 'B162407', 'B162408', 'B162409', 'B162410', 'B162412', 'B162416', 'B162417', 'B162418', 'B162420', 'B162421', 'B162422', 'B162423', 'B162424', 'B162425', 'B162426', 'B162428', 'B162430', 'B162434', 'B162435', 'B162436', 'B162437', 'B162440', 'B162442', 'B162443', 'B162446', 'B162447', 'B162448', 'B162451', 'B162458', 'B162459', 'B162462', 'B162464', 'B162467', 'B162473', 'B162475', 'B162477', 'B162479', 'B162481', 'B162482', 'B162483', 'B162484', 'B162485', 'B162488', 'B162490', 'B162492', 'B162493', 'B162494', 'B162495', 'B162496', 'B162498', 'B162500', 'B162510', 'B162512', 'B162513', 'B162514', 'B162515', 'B162516', 'B162517', 'B162518', 'B162519', 'B162520', 'B162521', 'B162522', 'B162523', 'B162524', 'B162525', 'B162526', 'B162527', 'B162528', 'B162529', 'B162530', 'B162531', 'B162532', 'B162533', 'B162534', 'B162535', 'B162536', 'B162537', 'B162538', 'B162539', 'B162540', 'B162541', 'B162542', 'B162543', 'B162544', 'B162545', 'B162546', 'B162547', 'B162550', 'B162551', 'B162552', 'B162553', 'B162554', 'B162555', 'B162556', 'B162557', 'B162558', 'B162559', 'B162560', 'B162561', 'B162562', 'B162563', 'B162564', 'B162565', 'B162566', 'B162568', 'B162570', 'B162571', 'B162572', 'B162573', 'B162574', 'B162575', 'B162576', 'B162579', 'B162581', 'B162582', 'B162583', 'B162585', 'B162586', 'B162587', 'B162588', 'B162589', 'B162590', 'B162591', 'B162592', 'B162593', 'B162594', 'B162595', 'B162596', 'B162597', 'B162598', 'B162599', 'B162600', 'B162601', 'B162604', 'B162605', 'B162606', 'B162607', 'B162614', 'B162615', 'B162619', 'B162620', 'B162621', 'B162622', 'B162623', 'B162624', 'B162625', 'B162626', 'B162627', 'B162637', 'B162638', 'B162639', 'B162640', 'B162641', 'B162642', 'B162643', 'B162644', 'B162646', 'B162647', 'B162648', 'B162649', 'B162650', 'B162651', 'B162652', 'B162653', 'B162654', 'B162655', 'B162656', 'B162657', 'B162658', 'B162659', 'B162660', 'B162664', 'B162665', 'B162667', 'B162669', 'B162670', 'B162671', 'B162672', 'B162673', 'B162674', 'B162675', 'B162676', 'B162680', 'B162681', 'B162682', 'B162683', 'B162684', 'B162685', 'B162686', 'B162687', 'B162688', 'B162690', 'B162692', 'B162693', 'B162694', 'B162695', 'B162696', 'B162697', 'B162698', 'B162699', 'B162700', 'B162701', 'B162702', 'B162703', 'B162704', 'B162705', 'B162706', 'B162707', 'B162708', 'B162710', 'B162711', 'B162713', 'B162714', 'B162715', 'B162716', 'B162717', 'B162719', 'B162720', 'B162722', 'B162725', 'B162727', 'B162728', 'B162731', 'B162734', 'B162735', 'B162736', 'B162737', 'B162738', 'B162739', 'B162740', 'B162741', 'B162742', 'B162743', 'B162745', 'B162746', 'B162747', 'B162748', 'B162749', 'B162751', 'B162752', 'B162753', 'B162754', 'B162757', 'B162759', 'B162761', 'B162762', 'B162763', 'B162778', 'B162779', 'B162780', 'B162781', 'B162782', 'B162783', 'B162784', 'B162785', 'B162786', 'B162787', 'B162788', 'B162789', 'B162790', 'B162791', 'B162792', 'B162793', 'B162794', 'B162795', 'B162796', 'B162797', 'B162798', 'B162799', 'B162800', 'B162801', 'B162802', 'B162803', 'B162804', 'B162805', 'B162806', 'B162808', 'B162809', 'B162813', 'B162816', 'B162818', 'B162822', 'B162824', 'B162825', 'B162826', 'B162827', 'B162830', 'B162831', 'B162834', 'B162835', 'B162836', 'B162838', 'B162840', 'B162842', 'B162845', 'B162846', 'B162847', 'B162848', 'B162849', 'B162851', 'B162852', 'B162853', 'B162854', 'B162855', 'B162856', 'B162857', 'B162858', 'B162859', 'B162860', 'B162861', 'B162862', 'B162865', 'B162866', 'B162867', 'B162868', 'B162869', 'B162871', 'B162873', 'B162874', 'B162875', 'B162876', 'B162877', 'B162878', 'B162879', 'B162881', 'B162882', 'B162883', 'B162885', 'B162886', 'B162887', 'B162890', 'B162891', 'B162892', 'B162893', 'B162894', 'B162895', 'B162896', 'B162897', 'B162899', 'B162900', 'B162902', 'B162904', 'B162905', 'B162911', 'B162912', 'B162914', 'B162915', 'B162917', 'B162918', 'B162919', 'B162920', 'B162921', 'B162922', 'B162923', 'B162924', 'B162925', 'B162929', 'B162930', 'B162931', 'B162932', 'B162933', 'B162934', 'B162935', 'B162947', 'B162949', 'B162950', 'B162952', 'B162956', 'B162958', 'B162959', 'B162962', 'B162963', 'B162964', 'B162965', 'B162966', 'B162967', 'B162968', 'B162969', 'B162971', 'B162975', 'B162978', 'B162979', 'B162984', 'B162988', 'B162989', 'B162990', 'B162999', 'B163000', 'B163003', 'B163004', 'B163005', 'B163007', 'B163008', 'B163009', 'B163010', 'B163011', 'B163012', 'B163013', 'B163014', 'B163015', 'B163016', 'B163018', 'B163021', 'B163022', 'B163024', 'B163026', 'B163027', 'B163028', 'B163029', 'B163030', 'B163031', 'B163032', 'B163033', 'B163034', 'B163035', 'B163036', 'B163037', 'B163040', 'B163041', 'B163042', 'B163043', 'B163044', 'B163045', 'B163047', 'B163051', 'B163053', 'B163054', 'B163055', 'B163057', 'B163058', 'B163059', 'B163060', 'B163061', 'B163064', 'B163065', 'B163067', 'B163068', 'B163071', 'B163072', 'B163073', 'B163074', 'B163075', 'B163076', 'B163077', 'B163078', 'B163079', 'B163080', 'B163081', 'B163082', 'B163083', 'B163084', 'B163085', 'B163095', 'B163096', 'B163097', 'B163098', 'B163099', 'B163107', 'B163108', 'B163110', 'B163111', 'B163112', 'B163113', 'B163114', 'B163115', 'B163116', 'B163117', 'B163118', 'B163119', 'B163120', 'B163121', 'B163122', 'B163123', 'B163124', 'B163125', 'B163126', 'B163127', 'B163128', 'B163129', 'B163130', 'B163131', 'B163132', 'B163133', 'B163134', 'B163136', 'B163137', 'B163139', 'B163141', 'B163142', 'B163143', 'B163144', 'B163145', 'B163146', 'B163147', 'B163148', 'B163149', 'B163150', 'B163151', 'B163152', 'B163153', 'B163154', 'B163158', 'B163160', 'B163161', 'B163162', 'B163164', 'B163170', 'B163171', 'B163172', 'B163172', 'B163173', 'B163174', 'B163175', 'B163176', 'B163178', 'B163179', 'B163180', 'B163181', 'B163182', 'B163185', 'B163186', 'B163187', 'B163188', 'B163189', 'B163190', 'B163192', 'B163198', 'B163199', 'B163200', 'B163201', 'B163374', 'B163375', 'B163377', 'B163378', 'B163379', 'B163380', 'B163381', 'B163382', 'B163383', 'B163384', 'B163385', 'B163386', 'B163389', 'B163390', 'B163392', 'B163393', 'B163394', 'B163395', 'B163396', 'B163397', 'B163398', 'B163399', 'B163400', 'B163401', 'B163402', 'B163403', 'B163406', 'B163407', 'B163408', 'B163409', 'B163410', 'B163411', 'B163412', 'B163413', 'B163414', 'B163415', 'B163416', 'B163417', 'B163418', 'B163419', 'B163420', 'B163421', 'B163422', 'B163423', 'B163424', 'B163425', 'B163426', 'B163427', 'B163428', 'B163429', 'B163430', 'B163431', 'B163432', 'B163433', 'B163472', 'B163474', 'B163475', 'B163477', 'B163479', 'B163481', 'B163482', 'B163483', 'B163484', 'B163485', 'B163486', 'B163487', 'B163488', 'B163489', 'B163490', 'B163491', 'B163492', 'B163493', 'B163494', 'B163495', 'B163496', 'B163497', 'B163498', 'B163499', 'B163500', 'B163501', 'B163502', 'B163503', 'B163504', 'B163505', 'B163506', 'B163507', 'B163509', 'B163510', 'B163511', 'B163512', 'B163513', 'B163514', 'B163515', 'B163516', 'B163517', 'B163518', 'B163519', 'B163520', 'B163521', 'B163522', 'B163523', 'B163524', 'B163526', 'B163527', 'B163528', 'B163529', 'B163530', 'B163531', 'B163532', 'B163545', 'B163546', 'B163547', 'B163548', 'B163549', 'B163550', 'B163551', 'B163552', 'B163553', 'B163554', 'B163555', 'B163556', 'B163557', 'B163558', 'B163559', 'B163560', 'B163569', 'B163570', 'B163571', 'B163572', 'B163573', 'B163574', 'B163575', 'B163576', 'B163577', 'B163578', 'B163579', 'B163580', 'B163581', 'B163582', 'B163583', 'B163584', 'B163585', 'B163586', 'B163587', 'B163588', 'B163591', 'B163592', 'B163593', 'B163594', 'B163595', 'B163597', 'B163598', 'B163599', 'B163600', 'B163602', 'B163603', 'B163606', 'B163607', 'B163608', 'B163610', 'B163611', 'B163612', 'B163613', 'B163614', 'B163615', 'B163616', 'B163617', 'B163618', 'B163619', 'B163620', 'B163621', 'B163622', 'B163623', 'B163626', 'B163627', 'B163629', 'B163630', 'B163631', 'B163632', 'B163636', 'B163637', 'B163638', 'B163639', 'B163641', 'B163642', 'B163643', 'B163644', 'B163645', 'B163646', 'B163647', 'B163650', 'B163651', 'B163652', 'B163653', 'B163654', 'B163656', 'B163657', 'B163658', 'B163664', 'B163665', 'B163666', 'B163669', 'B163670', 'B163671', 'B163675', 'B163676', 'B163677', 'B163678', 'B163680', 'B163685', 'B163688', 'B163690', 'B163697', 'B163698', 'B163699', 'B163700', 'B163701', 'B163702', 'B163703', 'B163704', 'B163705', 'B163706', 'B163707', 'B163708', 'B163709', 'B163710', 'B163711', 'B163712', 'B163713', 'B163714', 'B163715', 'B163716', 'B163717', 'B163718', 'B163719', 'B163720', 'B163721', 'B163722', 'B163723', 'B163725', 'B163726', 'B163727', 'B163728', 'B163729', 'B163730', 'B163731', 'B163732', 'B163734', 'B163735', 'B163736', 'B163737', 'B163738', 'B163747', 'B163748', 'B163749', 'B163750', 'B163751', 'B163752', 'B163755', 'B163758', 'B163759', 'B163760', 'B163761', 'B163762', 'B163763', 'B163764', 'B163765', 'B163766', 'B163767', 'B163768', 'B163769', 'B163770', 'B163771', 'B163772', 'B163773', 'B163774', 'B163775', 'B163776', 'B163777', 'B163778', 'B163787', 'B2365087', 'B2365616', 'B2365786', 'B2365803', 'B2373341', 'B2373400', 'B2373446', 'B2373452', 'B2373540', 'B2373544', 'B2373702', 'B302011403', 'B302012155', 'B302012842', 'B302012844', 'B302012846', 'B302012848', 'B302012852', 'B302012858', 'B302012859', 'B302012860', 'B302012861', 'B302012863', 'B302012864', 'B302012865', 'B302012866', 'B302012867', 'B302012869', 'B302012870', 'B302012871', 'B302012872', 'B302012873', 'B302012874', 'B302012875', 'B302012876', 'B302012891', 'B302012894', 'B302019336', 'B302019372', 'B302019436', 'B302019678', 'B302019872', 'B302019978', 'B302020031', 'B302020218', 'B302020344', 'B302021378', 'B302021380', 'B302021381', 'B302021382', 'B302021383', 'B302021384', 'B302021385', 'B302021386', 'B302021387', 'B302021388', 'B302021397', 'B302021398', 'B302021399', 'B302021400', 'B302021676', 'B302021677', 'B302022048', 'B302022106', 'B302022192', 'B302022561', 'B302022562', 'B302022773', 'B302022774', 'B302022775', 'B302022778', 'B302022779', 'B302022780', 'B302022781', 'B302022782', 'B302022783', 'B302022784', 'B302023109', 'B302024517', 'B302024523', 'B302024524', 'B302030218', 'B302030219', 'B302030220', 'B302030223', 'B302030224', 'B302030227', 'B302030228', 'B302030229', 'B302030230', 'B302030231', 'B302030232', 'B302030797', 'B302030798', 'B302030799', 'B302030800', 'B302030801', 'B302030802', 'B302030804', 'B302030805', 'B302030806', 'B302030807', 'B302030808', 'B302030809', 'B302030810', 'B302030811', 'B302030812', 'B302030813', 'B302030817', 'B302030818', 'B302030819', 'B302030820', 'B302030821', 'B302030823', 'B302030824', 'B302030825', 'B302030826', 'B302030827', 'B302030828', 'B302030829', 'B302030830', 'B302031593', 'B302031664', 'B302031665', 'B302031666', 'B302031667', 'B302031668', 'B302031669', 'B302031670', 'B302032606', 'B302034055', 'B302034056', 'B302034067', 'B302034130', 'B302034131', 'B302034254', 'B302034550', 'B302034551', 'B302034618', 'B302034627', 'B302034629', 'B302034645', 'B302034724', 'B302034725', 'B302034726', 'B302034727', 'B302060103', 'B302060151', 'B302060242', 'B302060243', 'B302060244', 'B302060367', 'B302060377', 'B302060720', 'B302060786', 'B302061111', 'B302061138', 'B302061139', 'B302061140', 'B302061141', 'B302061142', 'B302061143', 'B302061144', 'B302061145', 'B302061146', 'B302061147', 'B302061148', 'B302061149', 'B302061153', 'B302061154', 'B302061155', 'B302061156', 'B302061157', 'B302061158', 'B302061159', 'B302061160', 'B302061161', 'B302061162', 'B302061163', 'B302061164', 'B302061165', 'B302061166', 'B302061167', 'B302061168', 'B302061169', 'B302061170', 'B302061266', 'B302061316', 'B302061317', 'B302061318', 'B302061319', 'B302061468', 'B302061470', 'B302061536', 'B302061536', 'B302061650', 'B302061814', 'B302061940', 'B302061968', 'B302061982', 'B302062012', 'B302062013', 'B302062014', 'B302062015', 'B302062016', 'B302062017', 'B302062018', 'B302062020', 'B302062021', 'B302062022', 'B302062023', 'B302062024', 'B302062025', 'B302062027', 'B302062028', 'B302062029', 'B302062186', 'B302062187', 'B302062193', 'B302062268', 'B302062340', 'B302062589', 'B302062590', 'B302062610', 'B302062751', 'B302062775', 'B302062776', 'B302062895', 'B302062896', 'B302062983', 'B302063197', 'B302063198', 'B302063229', 'B302063230', 'B302063413', 'B302063428', 'B302063432', 'B302063434', 'B302063435', 'B302063438', 'B302063598', 'B302063645', 'B302063700', 'B302063706', 'B302063821', 'B302063983', 'B302064015', 'B302064016', 'B302064073', 'B302064074', 'B302064134', 'B302064178', 'B302064232', 'B302064458', 'B302064527', 'B302064528', 'B302064529', 'B302064671', 'B302064710', 'B302064714', 'B302064724', 'B302064811', 'B302064895', 'B302064955', 'B302064987', 'B302064988', 'B302065049', 'B302065050', 'B302065241', 'B302065315', 'B3169354', 'B3169355', 'B3169356', 'B3169365', 'B3169387', 'B3169393', 'B3169397', 'B3169399', 'B3169400', 'B3169633', 'B3169634', 'B3169635', 'B3169636', 'B3169638', 'B3169845', 'B3169846', 'B3169847', 'B3169850', 'B3169851', 'B3169852', 'B3169854', 'B3170016', 'B3170017', 'B3170018', 'B3170019', 'B3170145', 'B3170149', 'B3170174', 'B3170175', 'B9001329', 'B9001373', 'B9001388', 'B9001709', 'B9001718', 'B9011517', 'B9083815', 'B9083845']
  (default: [])
Running archetypes-mapper with scenario = D:\OneDrive\ETHY3FW\semesterProjectYiqiaoWang\CEA\Altstetten\Basecase
Traceback (most recent call last):
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\datamanagement\archetypes_mapper.py", line 409, in main
    archetypes_mapper(locator=locator,
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\datamanagement\archetypes_mapper.py", line 97, in archetypes_mapper
    calc_mixed_schedule(locator, building_typology_df, buildings)
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\datamanagement\schedule_helper.py", line 77, in calc_mixed_schedule
    schedule_new_data, schedule_complementary_data = calc_single_mixed_schedule(list_uses, occupant_densities, building_typology_df, internal_loads, building, schedule_data_all_uses, list_var_names, list_var_values, metadata)
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\datamanagement\schedule_helper.py", line 110, in calc_single_mixed_schedule
    [np.array(schedule_data_all_uses.schedule_complementary_data[use]['MONTHLY_MULTIPLIER'])
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\datamanagement\schedule_helper.py", line 111, in <listcomp>
    * building_typology_df.loc[building, var_value] if building_typology_df.loc[building, var_name] == use
  File "C:\Users\wangy\Documents\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

I also tried during the creation of scenario, pass a personalized typology.dbf with my own version, respecting the columns in the original typology.dbf, but still nothing was shown. Attached you can find a .zip file containing my zone.shp and typology.dbf file. Thanks in advance for your kind help!
[bugReport.zip](https://github.com/user-attachments/files/17357448/bugReport.zip)

**Comment by ShiZhongming** [comment]
Hi @yiqiaowang-arch 
Have you made sure the Name column does not have duplicated building IDs?
Your issue usually happens with duplicated Names..

**Comment by yiqiaowang-arch** [comment]
> Hi @yiqiaowang-arch Have you made sure the Name column does not have duplicated building IDs? Your issue usually happens with duplicated Names..

Solved it! After deleting all the duplications, the input files work fine in CEA again.
