### ISSUE TITLE
Can't make new use-types

### ISSUE THREAD

**Issue by moaapplepie** [architecture-building-systems/CityEnergyAnalyst#3717]
Hi!

I have a problem when trying to make new use-types. I copied an existing one (that works), but when I try to open it to edit in CEA, i get an error message and the page gets locked down. This is the error code I get: 

USE-TYPES
Something went wrong.
Detaljer
TypeError: Cannot convert undefined or null to object

    at lne (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-3C0jjdAG.js:245:12640)
    at div
    at sne (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-3C0jjdAG.js:245:11993)
    at ane (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-3C0jjdAG.js:245:11521)
    at <anonymous> (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-DDEITMkt.js:251:14581)
    at div
    at div
    at wne (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-3C0jjdAG.js:245:17519)
    at pne (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-3C0jjdAG.js:245:16305)
    at div
    at div
    at mne (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/DatabaseEditor-3C0jjdAG.js:245:15340)
    at <anonymous> (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-DDEITMkt.js:251:14581)
    at Suspense
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:18810)
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:19766)
    at div
    at div
    at div
    at cH (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-DDEITMkt.js:251:64120)
    at hH (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/HomePage-DDEITMkt.js:251:64834)
    at Suspense
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:18810)
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:19766)
    at t (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:17042)
    at a (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:33011)
    at l (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:34488)
    at C (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:72:6321)
    at WS (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:76:472)
    at EE (file:///C:/Users/moma0061/Videos/dashboard/resources/app.asar/dist/assets/index-D5kdnOX7.js:78:1220)

Thank you for the help!

**Comment by reyery** [comment]
@moaapplepie would you be able to share the new file that you have copied and I would try it on our end to try to debug it.
