### ISSUE TITLE
Demand forcasting

### ISSUE THREAD

**Issue by Ammariooo** [architecture-building-systems/CityEnergyAnalyst#3719]
Hello, 

I'm working on a project where i'm trying to simulate 2 projects (G0006, G0007) using the german_database. I run all the scripts in **Data managment** (Archetypes mapper ... etc) then i run the solar radiation and occupancy. Now i should be able to run the ernergy demand (right?) and when i try it i get the following Error:

```
City Energy Analyst version 3.38.0
Running `cea demand` with the following parameters:
- general:scenario = C:\Users\aba\Documents\CEA_Modell\UMB_Start\Gebäude6+7
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
Traceback (most recent call last):
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'G0006'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 60, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\api.py", line 38, in script_runner
    script_module.main(config)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\demand_main.py", line 145, in main
    demand_calculation(locator=locator, config=config)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\demand_main.py", line 108, in demand_calculation
    [building_properties[b] for b in building_names],
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\demand_main.py", line 108, in <listcomp>
    [building_properties[b] for b in building_names],
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\building_properties.py", line 410, in __getitem__
    supply=self.get_prop_supply_systems(building_name))
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\cea\demand\building_properties.py", line 143, in get_prop_supply_systems
    return self._prop_supply_systems.loc[name_building].to_dict()
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1343, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\indexing.py", line 1293, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\generic.py", line 4095, in xs
    loc = index.get_loc(key)
  File "C:\CityEnergyAnalyst\dependencies\micromamba\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'G0006'

- demand:buildings = ['G0006', 'G0007']
  (default: [])
- demand:loads-output = ['PV', 'GRID', 'GRID_a', 'GRID_l', 'GRID_v', 'GRID_ve', 'GRID_data', 'GRID_pro', 'GRID_aux', 'GRID_ww', 'GRID_hs', 'GRID_cs', 'GRID_cdata', 'GRID_cre', 'E_sys', 'Eal', 'Ea', 'El', 'Ev', 'Eve', 'Edata', 'Epro', 'Eaux', 'E_ww', 'E_hs', 'E_cs', 'E_cre', 'E_cdata', 'Qhs_sen_shu', 'Qhs_sen_ahu', 'Qhs_lat_ahu', 'Qhs_sen_aru', 'Qhs_lat_aru', 'Qhs_sen_sys', 'Qhs_lat_sys', 'Qhs_em_ls', 'Qhs_dis_ls', 'Qhs_sys_shu', 'Qhs_sys_ahu', 'Qhs_sys_aru', 'Qcs_sys_scu', 'Qcs_sys_ahu', 'Qcs_sys_aru', 'DH_hs', 'Qhs_sys', 'Qhs', 'DH_ww', 'Qww_sys', 'Qww', 'DC_cs', 'Qcs_sys', 'Qcs', 'DC_cre', 'Qcre_sys', 'Qcre', 'DC_cdata', 'Qcdata_sys', 'Qcdata', 'NG_hs', 'COAL_hs', 'OIL_hs', 'WOOD_hs', 'SOLAR_hs', 'NG_ww', 'COAL_ww', 'OIL_ww', 'WOOD_ww', 'SOLAR_ww', 'Qcs_sen_scu', 'Qcs_sen_ahu', 'Qcs_lat_ahu', 'Qcs_sen_aru', 'Qcs_lat_aru', 'Qcs_sen_sys', 'Qcs_lat_sys', 'Qcs_em_ls', 'Qcs_dis_ls', 'Qhpro_sys', 'Qcpro_sys', 'QH_sys', 'QC_sys']
  (default: [])
- demand:massflows-output = ['mcpww_sys', 'mcptw', 'mcpcs_sys', 'mcphs_sys', 'mcpcs_sys_ahu', 'mcpcs_sys_aru', 'mcpcs_sys_scu', 'mcphs_sys_ahu', 'mcphs_sys_aru', 'mcphs_sys_shu', 'mcpcre_sys', 'mcpcdata_sys']
  (default: [])
- demand:temperatures-output = ['T_int', 'T_ext', 'theta_o', 'Tww_sys_sup', 'Tww_sys_re', 'Tcre_sys_re', 'Tcre_sys_sup', 'Tcdata_sys_re', 'Tcdata_sys_sup', 'Ths_sys_sup_aru', 'Ths_sys_sup_ahu', 'Ths_sys_sup_shu', 'Ths_sys_re_aru', 'Ths_sys_re_ahu', 'Ths_sys_re_shu', 'Tcs_sys_sup_aru', 'Tcs_sys_sup_ahu', 'Tcs_sys_sup_scu', 'Tcs_sys_re_aru', 'Tcs_sys_re_ahu', 'Tcs_sys_re_scu', 'Ths_sys_sup', 'Ths_sys_re', 'Tcs_sys_sup', 'Tcs_sys_re']
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:overheating-warning = True
  (default: True)
Running demand calculation for scenario C:\Users\aba\Documents\CEA_Modell\UMB_Start\Gebäude6+7
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation for the following buildings=['G0006', 'G0007']
read input files
done
```

thank you and Regards.

**Comment by martin-mosteiro** [comment]
Looks like there's an issue in your input files, would you mind uploading them so we can check?

**Comment by reyery** [comment]
Closing this issue now since it is stale. Kindly reopen it again if the issue persists.
