### ISSUE TITLE
Launch tool: Sensitivity analysis

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#712]
[ ] Create interface to sensitivity analysis tool
[ ] Create Tutorial How does the Sensitivity Analysis tool work?

**Comment by daren-thomas** [comment]
@martin-mosteiro - have you been working on this? any pointers?

**Comment by martin-mosteiro** [comment]
@daren-thomas I have - and so have you! you just didn't know you were ;)

**Comment by martin-mosteiro** [comment]
The sampling tool was working when I last tested it last week, now I get the following error, though:
```
Executing: SensitivityDemandSamplesTool Morris 1 'Envelope variables';'Indoor comfort variables';'Internal load variables' 2 4 false C:\5buildings
Start Time: Tue Aug 08 16:33:31 2017
Running script SensitivityDemandSamplesTool...
['C:\\Users\\User\\Anaconda2\\envs\\cea\\python.exe', '-u', '-m', 'cea.cli', 'sensitivity-demand-samples', '--method', 'morris', '--num-samples', '1', '--samples-folder', 'C:\\5buildings', '--envelope-flag', 'True', '--indoor-comfort-flag', 'True', '--internal-loads-flag', 'True', '--grid-jump', '2', '--num-levels', '4']
usage: cli.py [-h] [-s SCENARIO]
              {demand,data-helper,emissions,embodied-energy,mobility,benchmark-graphs,weather-files,weather-path,locate,demand-graphs,scenario-plots,latitude,longitude,radiation,photovoltaic,radiation-daysim,install-toolbox,heatmaps,operation-costs,retrofit-potential,test,extract-reference-case,compile,read-config,write-config,excel-to-dbf,dbf-to-excel}
              ...
cli.py: error: invalid choice: 'sensitivity-demand-samples' (choose from 'demand', 'data-helper', 'emissions', 'embodied-energy', 'mobility', 'benchmark-graphs', 'weather-files', 'weather-path', 'locate', 'demand-graphs', 'scenario-plots', 'latitude', 'longitude', 'radiation', 'photovoltaic', 'radiation-daysim', 'install-toolbox', 'heatmaps', 'operation-costs', 'retrofit-potential', 'test', 'extract-reference-case', 'compile', 'read-config', 'write-config', 'excel-to-dbf', 'dbf-to-excel')

Completed script SensitivityDemandSamplesTool...
Succeeded at Tue Aug 08 16:33:31 2017 (Elapsed Time: 0.09 seconds)
```

**Comment by daren-thomas** [comment]
Huh... That actually works for me.... I'm getting this error instead:

```
['C:\\Users\\darthoma\\AppData\\Local\\conda\\conda\\envs\\cea\\python.exe', '-u', '-m', 'cea.cli', 'sensitivity-demand-simulate', '--scenario-path', 'C:\\cea-reference-case\\reference-case-open\\baseline', '--weather-path', 'c:\\users\\darthoma\\documents\\github\\cityenergyanalyst\\cea\\databases\\weather\\Zug.epw', '--samples-folder', 'C:\\cea-reference-case\\reference-case-open\\samples', '--simulation-folder', 'C:\\cea-reference-case\\reference-case-open\\simulation', '--num-simulations', '16', '--sample-index', '0', '--output-parameters', "[u'Eauxf_MWhyr', u'Eauxf_ve_MWhyr', u'Eauxf_ve0_kW', u'Ef_MWhyr']"]
failed to import from rc_model_sia_cc.pyd, falling back to pure python functions
failed to import from storagetank_cc.pyd, falling back to pure python functions
Setting prop_overrides['win_wall'] to 0.2
Setting prop_overrides['n50'] to 2.66666666667
Setting prop_overrides['win_op'] to 0.666666666667
Setting prop_overrides['U_base'] to 2.0
Setting prop_overrides['U_wall'] to 1.03666666667
Setting prop_overrides['U_roof'] to 0.696666666667
Setting prop_overrides['U_win'] to 3.1
Setting prop_overrides['G_win'] to 0.733333333333
Setting prop_overrides['Cm'] to 80000.0
Setting prop_overrides['e_wall'] to 0.84
Setting prop_overrides['e_win'] to 0.02
Setting prop_overrides['e_roof'] to 0.663333333333
Setting prop_overrides['a_wall'] to 0.85
Setting prop_overrides['a_roof'] to 0.666666666667
Setting prop_overrides['Hs'] to 0.883333333333
Running demand simulation for sample 0
read input files
Building B06 has no heating and cooling system, Hs corrected to 0.
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\cli.py", line 655, in <module>
    main()
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\cli.py", line 651, in main
    parsed_args.func(parsed_args)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\cli.py", line 388, in sensitivity_demand_simulate
    output_parameters=args.output_parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 171, in simulate_demand_batch
    totals, time_series = simulate_demand_sample(locator, weather, output_parameters)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\analysis\sensitivity\sensitivity_demand_simulate.py", line 113, in simulate_demand_sample
    totals, time_series = demand_main.demand_calculation(locator, weather_path, gv)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\demand_main.py", line 67, in demand_calculation
    building_properties = BuildingProperties(locator, gv)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\thermal_loads.py", line 377, in __init__
    gv)
  File "c:\users\darthoma\documents\github\cityenergyanalyst\cea\demand\thermal_loads.py", line 582, in calc_prop_rc_model
    df['Cm'] = self._overrides['Cm_Af'] * df['Af']
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "C:\Users\darthoma\AppData\Local\conda\conda\envs\cea\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5280)
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5126)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20523)
  File "pandas\_libs\hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20477)
KeyError: 'Cm_Af'
```

Any ideas??

**Comment by martin-mosteiro** [comment]
I still get the message above...

**Comment by martin-mosteiro** [comment]
The above error was fixed by @daren-thomas. The sampling and simulation tools are now working. The analysis tool is not working though, and it doesn't work on Pycharm either:

```
C:\Users\User\Miniconda2\envs\cea\python.exe C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/analysis/sensitivity/sensitivity_demand_analyze.py -S C:\5buildings
analyzing sensitivity in C:\5buildings for temporal_scale=yearly
C:\Users\User\Miniconda2\envs\cea\lib\site-packages\numpy\core\_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
C:\Users\User\Miniconda2\envs\cea\lib\site-packages\numpy\core\_methods.py:125: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)

Process finished with exit code 0
```

Any ideas??

**Comment by martin-mosteiro** [comment]
The first issue is completed and merged.
The second issue is replaced by #799.
This issue can therefore now be closed.
