### ISSUE TITLE
Heatmaps tool not working

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#790]
Running the heatmaps tool from the command line, I get the following error:
```
C:\Users\User\Miniconda2\envs\cea\python.exe C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/plots/heatmaps.py
Traceback (most recent call last):
  File "C:/Users/User/Documents/GitHub/CEAforArcGIS/cea/plots/heatmaps.py", line 10, in <module>
    from cea.interfaces.arcgis.modules import arcpy
  File "C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\interfaces\arcgis\modules.py", line 34, in <module>
    import arcpy
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\__init__.py", line 22, in <module>
    from arcpy.geoprocessing import gp
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\__init__.py", line 14, in <module>
    from _base import *
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\_base.py", line 14, in <module>
    import arcgisscripting
ImportError: DLL load failed: %1 is not a valid Win32 application.

Process finished with exit code 1
```

Seems like a 32-bit vs 64-bit problem?

The tool doesn't work for me on ArcGIS either, with the following error message:
```
ERROR 
Traceback (most recent call last): File "", line 672, in updateParameters File "C:\Python27\ArcGIS10.4\lib\site-packages\pandas\__init__.py", line 13, in "extensions first.".format(module)) ImportError: C extension: hashtable not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first. 
```

@daren-thomas any ideas what might be going on?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this still the case @martin-mosteiro ?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Still getting the same issue on my computer

**Comment by JIMENOFONSECA** [comment]
This seems to be a problem of the installation. Could you drop by and ask daren?

Best, Jimeno

On 3 Oct 2017, at 00:40, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> Still getting the same issue on my computer

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro i found the problem.

you need to install background geoprocessing for arcgis @daren-thomas could you help martin on this? it is one of the installers that come with arcgis.

I will include this line into the installation guide.

**Comment by martin-mosteiro** [comment]
After installing background geoprocessing as suggested by @JIMENOFONSECA, the same problem persists.
