### ISSUE TITLE
Error while running radiation_main.py file

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#844]
Here is the procedure I followed while running the radiation_main.py file.

1. Firstly, I unzipped the `reference-case-open.zip` file shipped with CEA present in the folder `cea\examples`. Copied this folder to `C:` drive.
2. Ran the `cea\demand\preprocessing\properties.py` file. It ran successfully.
3. Ran the `cea\demand\demand_main.py` file. It ran successfully.
4. Following this, ran the `cea\resources\radiation_daysim\radiation_main.py` file and encountered the following error:

`'epw2wea' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_daysim/radiation_main.py", line 216, in <module>
    main(locator=locator, weather_path=weather_path)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_daysim/radiation_main.py", line 208, in main
    radiation_singleprocessing(rad, geometry_3D_zone, locator, weather_path, settings)
  File "C:/Users/Bhargava/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_daysim/radiation_main.py", line 167, in radiation_singleprocessing
    daysim_main.isolation_daysim(chunk_n, rad, bldg_dict, locator, weather_path, settings)
  File "C:\Users\Bhargava\Documents\GitHub\CEAforArcGIS\cea\resources\radiation_daysim\daysim_main.py", line 129, in isolation_daysim
    rad.execute_epw2wea(weather_path)
  File "C:\Users\Bhargava\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 528, in execute_epw2wea
    results = open(weaweatherfile, "r")
IOError: [Errno 2] No such file or directory: 'c:\\users\\bhargava\\appdata\\local\\temp\\temp0\\wea\\Zug_60min.wea'

Process finished with exit code 1`

Following this, I requested Shanshan to run it on her computer and she followed the same procedure and did not encounter any error.

**Comment by BhargavaKrishnaSreepathi** [comment]
Fixed the issue, just had to reinstall daysim.
