### ISSUE TITLE
chisqprob is deprecated

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#951]
According to this page: https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.chisqprob.html, the package `chisqprob` is deprecated and we should use `stats.distributions.chi2.sf` instead - I haven't been able to find the documentation online for this yet, but it stands to reason that we need to update our code.

We ran into this problem when upgrading to Ubuntu.

```
$ cea test
Traceback (most recent call last):
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/cmd_base.py", line 380, in execute
    self, params, args)
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/cmd_base.py", line 263, in load_tasks
    return self._load_from(cmd, self.mod_dict, self.cmd_names)
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/cmd_base.py", line 247, in _load_from
    task_list = loader.load_tasks(members, cmd_list, cmd.execute_tasks)
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/loader.py", line 148, in load_tasks
    _process_gen()
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/loader.py", line 140, in _process_gen
    task_list.extend(generate_tasks(name, ref(), ref.__doc__))
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/loader.py", line 314, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/doit/loader.py", line 28, in flat_generator
    for item in gen:
  File "/home/jose/Documents/CityEnergyAnalyst/cea/tests/dodo.py", line 136, in task_run_data_helper
    import cea.demand.preprocessing.data_helper
  File "/home/jose/Documents/CityEnergyAnalyst/cea/demand/preprocessing/data_helper.py", line 14, in <module>
    from cea.utilities.dbf import dbf_to_dataframe, dataframe_to_dbf
  File "/home/jose/Documents/CityEnergyAnalyst/cea/utilities/dbf.py", line 10, in <module>
    import pysal
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/pysal/__init__.py", line 95, in <module>
    import pysal.spreg
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/pysal/spreg/__init__.py", line 1, in <module>
    from ols import *
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/pysal/spreg/ols.py", line 8, in <module>
    import summary_output as SUMMARY
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/pysal/spreg/summary_output.py", line 10, in <module>
    import diagnostics_sp as diagnostics_sp
  File "/home/jose/anaconda2/envs/cea/lib/python2.7/site-packages/pysal/spreg/diagnostics_sp.py", line 7, in <module>
    from scipy.stats.stats import chisqprob
ImportError: cannot import name chisqprob
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas the error comes from importing pysal, maybe a newer version of pysal could do the trick?

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas: were you able to solve this? I am getting the same error when trying to run demand_main.py

**Comment by BhargavaKrishnaSreepathi** [comment]
After i upgraded the pysal, the error is solved

**Comment by daren-thomas** [comment]
@BhargavaKrishnaSreepathi i have a pull request for this... do you want to review it? you'd have to delete your conda environment and then re-create it. or just create a new one (`conda env create --name cea951`), activate it and try it out...

**Comment by BhargavaKrishnaSreepathi** [comment]
@daren-thomas: sure, i will test it.

**Comment by MalithDis** [comment]
I got this error message 

`ImportError: cannot import name 'chisqprob'`

when run below code. how to solve this error? please tell me

```
#Import the necessary Python moduless
import pandas as pd
import geopandas as gpd
import numpy as np
from geopandas.tools import sjoin
import folium
from folium.plugins import MarkerCluster
from folium.element import IFrame
import shapely
from shapely.geometry import Point
import unicodedata
import pysal as ps
```

**Comment by daren-thomas** [comment]
@MalithDis how did you install the cea? what operating system?
